### ISSUE TITLE
Unreads in rules

### ISSUE THREAD

**Issue by Bottersnike** [CyberDiscovery/meta#12]
Instead of having the bot delete every message in the channel and resend every single embed, why aren't we just editing the embeds in the messages? Constantly having unreads every time something changes is really annoying, and doesn't serve a purpose of "prompts you to read the new thing" because there's no indication of what changed

**Comment by teamshortcut** [comment]
The short answer is: because we haven't coded the bot to do this 😅 I fully agree this would be a better system, but until a PR is made (and at the moment, I have enough on my plate right now) it isn't something we can really do much about.

**Comment by thebeanogamer** [comment]
This seems like more of an issue for [CyberDiscovery/cyberdisc-bot](https://github.com/CyberDiscovery/cyberdisc-bot)

**Comment by skiros-habib** [comment]
I'll do it in a bit.

**Comment by teamshortcut** [comment]
Closing as this is an issue for https://github.com/CyberDiscovery/cyberdisc-bot.
