### ISSUE TITLE
The moving of the category entitled 'CyberStart'

### ISSUE THREAD

**Issue by NicholasG04** [CyberDiscovery/meta#17]
Currently I find the 'CyberStart' category to be utterly useless due to the lack of any current parts of the course. Combined with the addition of the 'CyberStart Elite' category I believe it would be appropriate to move it far lower or, in fact, remove it. When discussing the course people tend to use #general and so I therefore find it inappropriate for it to continue to be located in its current position.

**Comment by SSAFuze** [comment]
We do have people (well at least one at the moment) who still use #cyberstart (in this case to seek hints on Game since they are from US). This channel avoids hints being requested in #general which helps maintain a more casual environment in #general.

**Comment by NicholasG04** [comment]
Do you therefore believe it is right that we offer hints for game when the guild is clearly entitled 'Cyber Discovery' - a course only available in the United Kingdom of Great Britain and Northern Ireland? Moreover, if we were to be happily supporting such hints should we not seek the return of #game?

Regardless of all of the above, I'd still stick by my original suggestion of at least moving the category down now due to its lack of use.

**Comment by picapi** [comment]
The CyberStart category was used for Assess, Game and Essentials, and does continue to be used by some members; it's also good to have a dedicated point for program discussion; even if discussion does happen elsewhere at times. The removal of the category/channel also means there is no public specific place to discuss CD; #general is more of a #general-discussion than program specific. I personally feel like the category should remain - channels will be added to it as relevant public events occur I imagine, for example if an online event was announced, and it's possible to mute and collapse the category to make it take up less space on your server list, while not removing it from existence.

**Comment by NicholasG04** [comment]
Indeed that is the case, and I'm not necessarily stating that deletion of the category would be necessarily appropriate. However I find it holds far less value than many of the channels below it and continue to believe that moving it would be appropriate. Thoughts on the movement of the category specifically would also be much appreciated.

**Comment by SSAFuze** [comment]
For a server which is dedicated to CyberDiscovery, I personally feel its important to keep the CyberStart category high up. It would also be moved up each time a new CyberDiscovery stage or related event is announced so it would be pointless to move it down. As @picapi said, collapsing the category is a viable option.

**Comment by NicholasG04** [comment]
However could it not be lowered whilst this section is less relevant? Collapsing the category still takes up a large amount of valuable space. If it was going to be used for the elite stages I'd believe that keeping it raised highly would be appropriate however since it is not I believe switching it would be better.

**Comment by lightspeedana** [comment]
`#general` is obviously often used for other points of discussion apart from the CD Programme itself; however, this is not the case with `#cyberstart`, being specifically made for discussion relating to CD. `#cyberstart` is also still used in multiple ways and the category will again be relevant soon enough - why should it be moved down only to be moved back up again - and the categories already below it are of lower importance considering the server's main purpose is being a discussion centre for students participating in CD. I agree completely with @picapi on it being the only point for specific discussion pertaining to the server's main purpose.

**Comment by teamshortcut** [comment]
#cyberstart is a central channel to the server, @picapi and @lightspeedana make very good points to that effect. It is still regularly used, even if you may not be among these people. @NicholasG04 
> Do you therefore believe it is right that we offer hints for game when the guild is clearly entitled 'Cyber Discovery' - a course only available in the United Kingdom of Great Britain and Northern Ireland?

The server is open to participants of sister programmes, and we welcome US participants or those in other countries. #cyberstart is the only channel that accommodates that. The category was also moved to its current position after people suggested it when Assess/Game began; as those programmes are continuing elsewhere, the category continues to be relevant to many people and to the core purpose of the server.
