### ISSUE TITLE
Addition of meta templates

### ISSUE THREAD

**Issue by NicholasG04** [CyberDiscovery/meta#18]
I believe that a template system for the issues on this repository would aid in the lowering of time required to create an issue and, moreover, mean that the required detail is present in more cases.

There could be multiple of these templates, for example one for 'Feature Requests'.

**Comment by picapi** [comment]
I support this; having templates for some common requests / suggestion types lowers the barrier to entry for new users to contribute, by giving them a structure to build off, as well as potentially making it easier to parse a suggestion and form an opinion on it.

**Comment by lightspeedana** [comment]
This is an interesting idea, how do you propose it could be done? Perhaps a Markdown template? 

It would certainly help by adding necessary headings and templating to make the job easier for both us and you 😄

**Comment by NicholasG04** [comment]
Extremely easily. GitHub has full support for markdown templates.

**Comment by lightspeedana** [comment]
Who would exactly create these though?

**Comment by NicholasG04** [comment]
Anyone.....
Someone with admin permissions for the repository could implement it.

If you so wish we could create a template in the repository and then people could commit as they wish?

**Comment by lightspeedana** [comment]
@thebeanogamer @teamshortcut thoughts?

**Comment by teamshortcut** [comment]
All for this idea; if you make a PR containing a draft template we can go from there.

**Comment by ZomBMage** [comment]
Resolved by #208
