### ISSUE TITLE
Collapsable Group addition

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#19]
For the current channels of #announcments #readme and #meta there is no way to hide these in a category. It would be beneficial to be able to collapse these into a group to save on space when they are rarely updated.

**Comment by lightspeedana** [comment]
Considering all 3 channels are extremely important, I feel it would do more harm than good to be able to collapse them when they should be referred back to frequently by server members, especially `#readme`. Furthermore, `#meta` will be frequently added to as new issues and ideas are developed, and it's better that these aren't collapsible to prevent server members being misinformed.

**Comment by NicholasG04** [comment]
I must say I completely agree with this issue. This, in addition to #12 would definitely help quality of life.

**Comment by NicholasG04** [comment]
> 
> 
> Considering all 3 channels are extremely important, I feel it would do more harm than good to be able to collapse them when they should be referred back to frequently by server members, especially `#readme`. Furthermore, `#meta` will be frequently added to as new issues and ideas are developed, and it's better that these aren't collapsible to prevent server members being misinformed.

Completely disagree. If people choose to use #readme regularly they can leave it uncollapsed. In fact I think it'll encourage people to check #meta more often as they see it has appeared from a collapsed channel.

**Comment by JuliaScythe** [comment]
Also #readme isn't something that needs to be checked that often, most of the time I just use common sense and if I think I might be pushing it, then I refer to readme. I agree with this issue.

**Comment by ZomBMage** [comment]
The channels would already be in a category if they weren't as important as they are. Personally I disagree so that it is immediately clear when #announcements, #readme and #meta may be updated and posted to

**Comment by ghost** [comment]
> The channels would already be in a category if they weren't as important as they are. Personally I disagree so that it is immediately clear when #announcements, #readme and #meta may be updated and posted to

They are important if you choose to follow along with them, many won't look at them, so what difference does it make? It allows people to have a smaller selection of channels view able straight away if they only take part and look in certain channels. Due to the layout of the server, if you wanted to be apart of the years discussion you have to go through the rest of the channels, so being able to collapse will help with activity in some of the 'lesser' channels.

Plus why aren't the 3 'important' channels in the Server-Stuff group, that is surely what the group should be used for...

**Comment by ghost** [comment]
> Considering all 3 channels are extremely important, I feel it would do more harm than good to be able to collapse them when they should be referred back to frequently by server members, especially `#readme`. Furthermore, `#meta` will be frequently added to as new issues and ideas are developed, and it's better that these aren't collapsible to prevent server members being misinformed.

If users wish to not partake in discussion for #meta should they be forced to have to view it at the top without a way to hide it from their view?

**Comment by NicholasG04** [comment]
I actually personally believe that putting them in a category makes it easier to see important updates. The fact that the channel names are only viewable when either uncollapsed or when there is a new message at least alerts me that I need to read that channel.

**Comment by teamshortcut** [comment]
This seems entirely fair; if you could make a PR, we can put it to a vote in #meta before potentially implementing it.

**Comment by lightspeedana** [comment]
@NicholasG04 that's a fair comparison. As @teamshortcut said, a vote could work to sort out who agrees and disagrees with the change 😄
