### ISSUE TITLE
Fortnite

### ISSUE THREAD

**Issue by Avexic** [CyberDiscovery/meta#202]
Fortnite is a massive multiplayer online video game released in July 2017, developed by Epic Games. The game includes three different game modes released as early access: Save the World, Battle Royale, and most recently, Creative. Fortnite Battle Royale is the free 100-player PvP mode in Fortnite. One giant map, a battle bus, building and destructible environments combined with intense PvP combat; the last one standing wins; and Save the World a cooperative shooter-survival game with up to 4-man squad to fight off husks and defend mission objectives with fortifications and defenses. Along with the arrival of Season 7, Creative mode was introduced. For the first time, players could create their own islands with provided prefabs, devices, and standard Battle Royale weapons and items- your island, your friends, your rules.

Fortnite Battle Royale is available on Microsoft Windows, macOS, PlayStation 4, Xbox One, Nintendo Switch, iOS and most modern Android devices while Save the World is only available on PC and consoles platforms (except Nintendo Switch).

As of November 2018 the game has over 200 million registered players. Additionally, Fortnite has won the title for most concurrent players exceeding 10.7 million users online at the same time

**Comment by picapi** [comment]
I don't feel like this is actually suggesting anything...

**Comment by thebeanogamer** [comment]
Closed as spam.
