### ISSUE TITLE
Allow for the recall of admins

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#205]
It may become apparent at some time either in the past, present or future to members that admins are no loner performing their duties as expected. Instead of leaving the decision of when to step down purely a speculative issue for the member concerned or the server owner be able to open an issue of no confidence within a admin to ascertain if they command the support of the server.

This obviously should only be allowed when there is due cause for concern and not as a joke to annoy members in the server.

**Comment by SSAFuze** [comment]
As much as this could be a good idea, there is no framework to exercise control over admins. Admins control the server, so they could implement such a rule but since there is no oversight, they would have no reason to follow said rule if it was triggered.

**Comment by teamshortcut** [comment]
If somebody has a problem with an admin, they can message myself or another Root or Sudo. (if they have a problem with all of us, they can either tolerate it or leave) As @SSAFuze says, practically speaking it's also completely infeasible.

If you have a problem with one of the admins at the moment, a snide GitHub issue is not the most productive way to resolve that.
