### ISSUE TITLE
Introduction of new Root and Sudo(s)

### ISSUE THREAD

**Issue by SSAFuze** [CyberDiscovery/meta#207]
In response to issue #206 , I wrote the following comment:

https://github.com/CyberDiscovery/meta/issues/206#issuecomment-492179420

tldr: introducing a new Root and new Sudo(s) could help with the current issues.

Of course, in response to @teamshortcut, it would be a challenging process but I feel the server is reaching a point where this is required. I'm certain that server members would be willing to consult and participate in this process.

I want to clarify that this suggestion does not suggest any changes to current admins, only the introduction of new ones.

**Comment by teamshortcut** [comment]
To reiterate what I said in the previous issue, personally I'm open to this, but it would need discussion and agreement among current staff before anything was implemented. As a hypothetical though, I personally have no immediate objections.
>I'm certain that server members would be willing to consult and participate in this process.

That would probably be helpful, even more so if it can be done without devolving into `#[user]ForSudo`

**Comment by SSAFuze** [comment]
@teamshortcut thank you for your response. I don't believe it needs immediate action, I just wanted to get the idea out. Unfortunately I can envision it descending into the user for sudo but I have no doubts that the mod team, should it be implemented, will find a way to take the servers opinion without handing control over to the server.

**Comment by ZomBMage** [comment]
> I'm certain that server members would be willing to consult and participate in this process.

please no election 2: electric boogaloo.
Another point, currently year 11s and year 13s are (or at least should be) busy with revision and exams, so the pool for suitable candidates may be reduced. I feel like we could use a google doc for the active server members to perhaps put forward their choice of candidate (to be taken with a heavy pinch of salt), to help the moderation team gauge the community's ideal candidates compared with the decisions of the staff team. Of course, the staff team should be the ultimate deciders (as we know what happened with the original election).

**Comment by NicholasG04** [comment]
I've never seen such a discussion where staff applications can be so simple. For about 2 years now I've been using a simple Google form to get applications before proceeding to an interview stage

**Comment by teamshortcut** [comment]
Lots of good points. I would agree that now is probably not the ideal time to put much into motion due to exams. Both community nominations and treating it more like a job application process (which really is what it is, I suppose) could be effective approaches, or indeed some combination of the two.

**Comment by NateKomodo** [comment]
Can’t make PR from phone soooo
