### ISSUE TITLE
Bring back commands in general

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#209]
Bring back !urban and !rank as they were useful in conversations ongoing in general at times. If the removal of commands was necessary then why are others such as !neveragoodtime still allowed during conversations.

**Comment by thebeanogamer** [comment]
Our main reason for keeping the `!urban` and `!rank` out of #general was the sheer level of their output. Where `!neveragoodtime` always has the same, fairly small output, the others produce a larger output, and especially in the case of `!rank`, each user gets a different output, meaning that it gets run many times.

This has led to an abundance of spam, and from my perspective, redirecting members to other channels when they want to use these commands seems reasonable, but I am of course open to alternatives.

**Comment by ZomBMage** [comment]
They still exist, just can't be used in #general at the moment. I found especially !urban could really clutter the chat if longer descriptions (possibly *rather* NSFW too) are searched for, and !rank typically got spammed in clusters because everyone wanted to check their ranks on impulse (for bragging rights or otherwise). There are more suitable and dedicated places to use these commands already

**Comment by ghost** [comment]
Fair points @thebeanogamer was more of an understanding why certain commands are and aren't allowed. Would be good to clarify which commands work where and  hy some don't work where they are.

**Comment by ghost** [comment]
> (possibly _rather_ NSFW too)

Had just thought of that, so i understand the reasoning more now.

**Comment by thebeanogamer** [comment]
> 
> 
> Fair points @thebeanogamer was more of an understanding why certain commands are and aren't allowed. Would be good to clarify which commands work where and hy some don't work where they are.

Yeah, we've debated internally the merits of a `COMMANDS.md` file, but it would only contain our custom commands so as to remain maintainable and not redunant, and I for one quite like having a few of the commands as secret so people find them by accident.

**Comment by ZomBMage** [comment]
> I for one quite like having a few of the commands as secret so people find them by accident.

~~*Who said you had to document the secrets?*~~
also finding by accident is *unlikely* at best

**Comment by thebeanogamer** [comment]
> also finding by accident is _unlikely_ at best

But that's half the fun!

**Comment by ZomBMage** [comment]
> But that's half the fun!

Most of the commands people find mostly stem from a staff member letting it slip, people don't spam bot commands looking for new commands

**Comment by lightspeedana** [comment]
> > But that's half the fun!
> 
> Most of the commands people find mostly stem from a staff member letting it slip, people don't spam bot commands looking for new commands

I find that this maintains a nice air of mystery, almost like a server easter egg. Whilst people may not actively look for them, it's always a nice small surprise, and I see no harm in not keeping a `COMMANDS.md` file, as most of them are easily explainable.

**Comment by JuliaScythe** [comment]
How about making !rank DM the user the rank image, rather than post it publically?

**Comment by thebeanogamer** [comment]
That's actually kinda a good idea, and Mee6 can do it.

**Comment by teamshortcut** [comment]
If people are satisfied with that (remember it can go into #meta for voting), that may be a good solution to !rank. Both that and a COMMANDS.md could be made into PRs for further refinement before going into #meta.

**Comment by teamshortcut** [comment]
Partially addressed above and resolved by #215
