### ISSUE TITLE
please unmute rejoiners

### ISSUE THREAD

**Issue by maishams** [CyberDiscovery/meta#216]
please unmute rejoiners aka me

### *A description of the issue:*
ok so whenever some people leave and rejoin they get automuted. why

### *Proposed Solution:*
fix whatever dyno/mee6 setting it is. i think its mee6 bc thats how level roles are persistent so like maybe it automuted but idk

### *Additional Comments:*
this isnt that major at all just a bit off. 

~~inb4 maisha just stop leaving literally every 20 seconds you cause roots and sudos hell~~
 
ty xx

**Comment by teamshortcut** [comment]
I'll have a look into this later. To clarify, is it that you're given the Muted role and are unable to send messages, and/or that you're server muted in VCs? (As I think there have been issues with that in some cases, not sure if it's related)

**Comment by thebeanogamer** [comment]
I had this issue when @AnonGuy rejoined to post some very high quality content before leaving again. I presume it's just Dyno persisting the role because they weren't on the server when it should have been removed.

**Comment by maishams** [comment]
yeah i cant msg any channels or join any vcs (pls pls unmute me thanks) i.e yh ive got the muted role

**Comment by maishams** [comment]
i.e yeah ive got the muted role

**Comment by maishams** [comment]
also no beano i wasnt muted before i left so there was no role to preserve; i was given the muted role when i rejoined

**Comment by thebeanogamer** [comment]
Well that's interesting...

**Comment by thebeanogamer** [comment]
Why on earth did it apply it then?

**Comment by maishams** [comment]
i have 0 idea, is it dyno or mee6 tho bc they both assign roles

**Comment by thebeanogamer** [comment]
Dyno

**Comment by maishams** [comment]
if u want u can move dyno's perms to the bottom so it cant add the roles higher than it and ill leave n rejoin n see if im muted

**Comment by maishams** [comment]
oh ok

**Comment by maishams** [comment]
kick dyno lmao

**Comment by thebeanogamer** [comment]
> 
> 
> if u want u can move dyno's perms to the bottom so it cant add the roles higher than it and ill leave n rejoin n see if im muted

That would break all the things.

**Comment by thebeanogamer** [comment]
> 
> 
> kick dyno lmao

You lot run riot enough with automod, I dread to think what it would be like without.

**Comment by maishams** [comment]
delete the server ezpz

**Comment by teamshortcut** [comment]
Not entirely sure why it happened in the first place, but I'm pleased to say it's now fixed!
![image](https://user-images.githubusercontent.com/12185328/58106684-617d4080-7be0-11e9-93ff-16c1ebe25c60.png)
This was a user-specific problem, rather than a bot one, so I'm closing this issue, but if this does happen to anybody else (I still have no idea why this was caused in the first place) we can remove it in the same way.

**Comment by maishams** [comment]
wtf why did i have mute persistence
admin abuse
