### ISSUE TITLE
can i be sudo

### ISSUE THREAD

**Issue by maishams** [CyberDiscovery/meta#217]
### *A description of the issue:*
like genuinely can i be sudo.
id like actually fix up and im online too much
like trial me as sudo for like a week and if u no likey u can go no u and say maisha u are not sudo material

### *Proposed Solution:*
discuss giving me sudoo

### *Additional Comments:*
thank

**Comment by teamshortcut** [comment]
I'm not immediately opposed to this, particularly if it has community support, but I would say that once a solution to #207 is agreed upon, this would probably work better as part of that, rather than a standalone addition.

**Comment by NicholasG04** [comment]
I have some major issues with this. Personally, I wouldn't be necessarily opposed to you becoming almost a trial moderator, but this 'application' I guess is sub-par. Personally if I would apply in this format I'd take some more effort into actually informing the community of why you'd like to become sudo, what you can do to help the server, what attributes you hold distinguishing you from others etc.

As I said, I wouldn't necessarily be opposed to the idea but this looks like you've put no effort in.

Regards.

**Comment by NicholasG04** [comment]
> 
> 
> I'm not immediately opposed to this, particularly if it has community support, but I would say that once a solution to #207 is agreed upon, this would probably work better as part of that, rather than a standalone addition.

Exactly this. A proper application would be a far better style... whether that be through a google form and election by current roots, or through another issue template on the GitHub with questions to be answered and maybe a community discussion.

**Comment by teamshortcut** [comment]
Luckily for @maishams, @NicholasG04 is not in charge of judging applicants or the application process 😉

We have not forgotten about #207, but it will likely be left until at least after exams (for reasons that I hope are obvious), and I would strongly encourage all further staff additions in the immediate future to take place then/as part of that, so that we can manage it properly and give fair consideration to all applicants.

**Comment by NicholasG04** [comment]
> 
> 
> Luckily for @maishams, @NicholasG04 is not in charge of judging applicants or the application process 😉
> 
> We have not forgotten about #207, but it will likely be left until at least after exams (for reasons that I hope are obvious), and I would strongly encourage all further staff additions in the immediate future to take place then/as part of that, so that we can manage it properly and give fair consideration to all applicants.

I totally agree that it'd be unfair to try and manage staff applications at a time when people are so busy.

However, I am disgusted that you have hereby chosen to make a slanderous and clearly ill-informed comment about my views. To suggest that my opinion could in any way be detrimental to the success of Maisha's application disgusts me. I have simply stated that it seems like this application has seen a lack of effort although I have clearly acknowledged that this does not represent my view on the matter as a whole.

**Comment by NateKomodo** [comment]
I’m in favour

**Comment by teamshortcut** [comment]
Should probably have closed this sooner, but please save it for #207. Meta issues is not the right process for it.
