### ISSUE TITLE
Application for sudo

### ISSUE THREAD

**Issue by Bentechy66** [CyberDiscovery/meta#219]
# Potential for me to become sudo

### *Why I believe I'm a good fit for the role of sudo:*
 - I'm online often *(Probably too often for my own good!)* and believe I have some positive ideas for how to improve the community which I would like to discuss with other staff.
 - I've been involved in many community projects - for example, I built from source the iOS version of the CD App, organised the creation of the Community CTF and have helped many people along their journey to completing various challenges.
 - I've been in the community for a long time - since the collm days, and have a good idea of what the community is like.

### *Proposed Solution:*
Discuss the possibility of me becoming sudo

**Comment by maishams** [comment]
copycat
ngl youd probs be better than me anyway
i approve

**Comment by teamshortcut** [comment]
Partly my fault for not closing #217 sooner, but this is not the time or way to do this, as stated in #217. Save it for #207 please.
