### ISSUE TITLE
Stricter rules regarding applications for Sudo

### ISSUE THREAD

**Issue by SSAFuze** [CyberDiscovery/meta#220]
# Stricter rules regarding applications for Sudo

### *A description of the issue:*
As of this moment, there are 2 open issues which are applications for the Sudo role. Whilst it is great to see people keen to put their name forward, as far as I am aware, official proceedings to select a new Sudo have not begun. These issues are people trying to apply to a currently non-existent vacancy. It also clutters the meta issues.

### *Proposed Solution:*
Do not allow any Sudo applications at the current time. If and when the process begins, have a designated system for applying to be a Sudo. My current suggestion would be a form with questions to answer which is then placed in a read-only channel (this is only a suggestion, other options exist). This separates the matter from any other process. This process should not begin until after exams at a minimum, and applications should only be accepted in a certain time period.

### *Additional Comments:*
I am in no way criticising those who have already submitted applications, I just feel a fair and timely process should be used since this will benefit applicants, admins and other server members.

**Comment by teamshortcut** [comment]
Closed #217 and #219 for this reason, which resolves this. Meta issues are not the place for this, sorry if I had left that unclear.
