### ISSUE TITLE
Strange Issue Numbering System on Meta Repo

### ISSUE THREAD

**Issue by Bentechy66** [CyberDiscovery/meta#221]
# Strange Issue Numbering System on Meta Repo

### *A description of the issue:*
For whatever reason, github issues on this repo seem to have jumped to #200+; #24 - #199 just don't seem to exist? This is somewhat confusing and I'm wondering as to whether there is a reason.

### *Proposed Solution:*
Address why this happens, and possibly revert numbering system back to normal

**Comment by maishams** [comment]
someone was spamming the n word lmao thats why

**Comment by Bottersnike** [comment]
> Address why this happens, and possibly revert numbering system back to normal

This is impossible. GitHub run GitHub, and all IDs for things must be unique for obvious reasons. As maisha said, there was someone spamming issues, therefore those issues were deleted. This means that this reall _is_ the 221st issue to be created, just not the 221st issue that still exists.

**Comment by Bentechy66** [comment]
Ah, thanks for clearing it up guys, closing
