### ISSUE TITLE
BritainElects Webhook

### ISSUE THREAD

**Issue by Bottersnike** [CyberDiscovery/meta#223]
Can we have a webhook for https://twitter.com/britainelects added to #overflow so we can get that sweet sweet live results:tm: for things as they happen?

**Comment by thebeanogamer** [comment]
Whilst that may not be an awful idea, under the Fixed Term Parliament Act 2011, the next election will be in 2022, unless one is called early. This means that it will just be poll spam until then.

**Comment by Bentechy66** [comment]
Yes pls

**Comment by teamshortcut** [comment]
I think a https://twitter.com/bbclaurak webhook was once floated as well. If it has a lot of support, I don't mind adding webhooks, but I'd worry that the majority of users would just find them annoying.

**Comment by thebeanogamer** [comment]
In the short term, if you want to keep easy track of political twitter, I'd recomend setting up a Tweetdeck list. I personally use the following:
```@BBCPolitics
@10DowningStreet
@DawnHFoster
@adamfleming
@BethRigby
@SamCoatesSky
@faisalislam
@KateEMcCann
@Stone_SkyNews
@MarkerJParker
@bbclaurak
@SebastianEPayne
@BBCVickiYoung
@BBCkatyaadler
@alexwickham
```

**Comment by teamshortcut** [comment]
The fact that Twitter lists exist also does somewhat negate the need for a webhook.

**Comment by ghost** [comment]
Yes add webhooksfor laurak and preston happy now @thebeanogamer

**Comment by Bottersnike** [comment]
Given the irrelevancy of this now I'm closing the issue.
