### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by NicholasG04** [CyberDiscovery/meta#227]
# Elite Category

### *A description of the issue:*
Elite is important. It is too low. 

### *Proposed Solution:*
Move the Elite category to above 100 Percent

### *Additional Comments:*
Not Applicable

**Comment by thebeanogamer** [comment]
This doesn't seem unreasonable.

**Comment by lightspeedana** [comment]
I am inclined to agree with this proposal 😄

**Comment by teamshortcut** [comment]
If a PR is made we can approve this for voting.

**Comment by NicholasG04** [comment]
Apologies for the lack of detail but I see no reason for any detail... it seems common sense to me.. Sure will do
