### ISSUE TITLE
Laura k Webhook 

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#230]
# Laura k Webhook 

### *A description of the issue:*
Instead of users constantly posting twitter links into #overflow from this user implement webhook instead

### *Proposed Solution:*
Add a webhook for users @bbclauraK and @preston for now into #overflow ideally they'd go into #politics but that isn't likely to happen. Happy to add others

**Comment by thebeanogamer** [comment]
See #223

**Comment by thebeanogamer** [comment]
_Now you've really confused some random developer by tagging them_

**Comment by preston** [comment]
I was thinking the same thing.

**Comment by lightspeedana** [comment]
@preston Apologies 😅

**Comment by ghost** [comment]
Woops! Didn't think it would tag someone sorry for the inconvenience!

**Comment by NicholasG04** [comment]
Really Robert? This poor developer :(

and why would we want the biased BBC to have any content in #overflow

**Comment by thebeanogamer** [comment]
@preston If you want a clue what's going on: https://joincyberdiscovery.com/

But the summery is mute this whilst I shout at @Robertgold

**Comment by ghost** [comment]
Now lets not get into fake news or not @NicholasG04 this is simply a suggestion.

**Comment by thebeanogamer** [comment]
And today on: why we put twitter handles in code tags...

**Comment by lightspeedana** [comment]
This issue now has more comments than it really needs...

**Comment by teamshortcut** [comment]
Before this gets any more out of hand, I'm closing it, as an issue for this (#223) basically exists already. @Robertgold add something there if you feel a need.
