### ISSUE TITLE
A new channel: #Tech

### ISSUE THREAD

**Issue by Trefonix** [CyberDiscovery/meta#233]
There should be a new channel created which would be used to discuss technology.

Currently, there is nowhere to suitably discuss technology. At the moment tech discussions are mostly done in #general; however, it's evident that not all members are as enthusiastic as others about the subject. This means that for those people, general is clogged with discussions they don't care about.

Create a new channel, #Tech.

**Comment by maishams** [comment]
inb4 half of it is apple fights with harry

i think this is a cool idea and should be implemented asap

**Comment by funderpanda** [comment]
yes i'd love to see more apple fights

**Comment by R0w4nS** [comment]
indeed

**Comment by NicholasG04** [comment]
Completely agree
In combination with a #politics channel this would really specialise channels and help the flow of chat.

**Comment by ghost** [comment]
Agreed on condition of #politics being added alongside this. Otherwise I will just say to use #overflow as we have to currently to discuss politics :(

**Comment by maishams** [comment]
i suggest communism - only one text and voice channel instead and all roles gone.

**Comment by Sh3llcod3** [comment]
I agree with @Trefonix, we do need a #Tech Channel :+1:

**Comment by picapi** [comment]
A tech channel certainly fits with the core theme of the server, and I feel could lead to some interesting discussions and learning new things - I'm all for it!

**Comment by teamshortcut** [comment]
Resolved by #239
