### ISSUE TITLE
unban the work 'tiktok'

### ISSUE THREAD

**Issue by maishams** [CyberDiscovery/meta#235]
### *A description of the issue:*
any message with the word 'tiktok' gets deleted. this is highly annoying and i feel like there is no actual reason to do that? like i think it was hahah funny back in the day but now its actually kinda annoying when you wanna talk ab tiktok or even mention it

### *Proposed Solution:*
change the dyno perm 

### *Additional Comments:*
no

**Comment by teamshortcut** [comment]
_yeah fair enough gimme 2 secs_

**Comment by NateKomodo** [comment]
Reban tiktok
