### ISSUE TITLE
Tre wants a #tech

### ISSUE THREAD

**Issue by BoatiestBoat** [CyberDiscovery/meta#237]
# Give Tre a tech, please

### *A description of the issue:*
Tre is sad he doesn't get a #tech and when Tre's sad I'm sad and that's bad

### *Proposed Solution:*
Give the man a #tech 

### *Additional Comments:*
Pretty please

**Comment by Trefonix** [comment]
:this:

**Comment by thebeanogamer** [comment]
Closed as duplicate of #233
