### ISSUE TITLE
More transparency on how #meta works

### ISSUE THREAD

**Issue by Trefonix** [CyberDiscovery/meta#238]
More transparency on how #meta works

Up until recently I was unclear on how #meta works, and I am still a bit confused to an extent.
This is probably a sentiment shared by others.

Solution: Extend #readme to have clear instructions on how #meta works.

**Comment by teamshortcut** [comment]
Do you mean the channel #readme or the repo's readme? The latter is being updated momentarily; for the former, it won't be relevant to most users and we have tried to keep the information in there as easy to read as possible. (while still balancing the question we get asked the most) Perhaps a pinned message in the #meta channel would be better?

**Comment by thebeanogamer** [comment]
Also #234

**Comment by Trefonix** [comment]
#234 addresses my concerns. This is no longer necessary; I suggest closing this issue.
