### ISSUE TITLE
A Very Important Issue!

### ISSUE THREAD

**Issue by maishams** [CyberDiscovery/meta#241]
Good Evening Fellow Cyberists!

It is with remorse I have to inform all members that the user behind the name of 'teamshortcut' refuses to alter his nickname to 'arron' in order to reflect his government name given at birth. As a valued member of this holy server, I know that this is injustice and must be changed at once; many other members of this valuable server might also be in agreement with me - if you are please comment '#arronNotTeamshortcut' as this will ensure I know I have your support during this treacherous time.

Thank you all, and I wish you a blessed evening!

Best,
Maisha

**Comment by teamshortcut** [comment]
🙅‍♂

**Comment by maishams** [comment]
THIS IS RACISM!

**Comment by R0w4nS** [comment]
#arronNotTeamshortcut

**Comment by NicholasG04** [comment]
#arronNotTeamshortcut
