### ISSUE TITLE
Stop purging of #polls

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#242]
# Stop the purging of polls every week

### *A description of the issue:*
Stop the removal of poll suggestions ever week, as there is little purpose to the purging every week. Polls is used in such a manner that shouldn’t and doesn’t require it to be purged weekly

### *Proposed Solution:*
Stop the constant purging.

### *Additional Comments:*
[fill out]

**Comment by maishams** [comment]
i agree highly.

**Comment by teamshortcut** [comment]
The reason it is purged weekly is so that it gives it a regular schedule, so people know when it will be purged. The reason it's purged in the first place is to stop the channel getting clogged up to the point where nobody uses it, to let new polls be more visible. However, I'm happy to put this to a vote in #meta if a PR is made.

**Comment by jerbob** [comment]
What would be the diff of the PR resolving this issue?

**Comment by teamshortcut** [comment]
Simply that PR lets staff approve it, and requires that multiple staff approve it; our process is that we put PRs that pass to a vote, and while for this issue you're right that it would make very little difference, in future in case of far more contentious issues, I'd prefer to maintain a precedent that it has to go to a PR first.

**Comment by jerbob** [comment]
I'm not disagreeing with this, I'm just saying that in order to make a PR, an edit needs to be made to one of the files in the repo. What file would need to be changed?

**Comment by teamshortcut** [comment]
Oh I see, sorry; [MISCELLANEOUS.md](https://github.com/CyberDiscovery/meta/blob/master/MISCELLANEOUS.md) would be the one to edit.
