### ISSUE TITLE
Animated Logo

### ISSUE THREAD

**Issue by ThisIs0xBC** [CyberDiscovery/meta#247]
# Title Of Issue
Animated Logo
### *A description of the issue:*
Create an animated server logo which follows the format that the team signs at Elite Year 1 did, the streaks of colour in the background are falling down almost

### *Proposed Solution:*
Get Alice on the case or something

### *Additional Comments:*
WATER WATER WATER WATER WATER WATER, DRIP
TATER TOTTER, HARRY POTTER, PLEASE GET OFF MY DICK
yeah basically just make an animated logo thanks lads xoxo <3

**Comment by ThisIs0xBC** [comment]
Wait I've just been informed that we have an animated logo but we just don't have the nitro boost anymore. Major F. Although the logo I saw seemed kinda slow, wayyy slower than the signs at elite

**Comment by teamshortcut** [comment]
As you rightly pointed out, we have an animated logo, just not two Nitro boosts.

**Comment by alfiejfs** [comment]
We do have two now! 

@teamshortcut

**Comment by teamshortcut** [comment]
![image](https://user-images.githubusercontent.com/12185328/60772790-351b7600-a0f3-11e9-8e12-433d0904b855.png)
Sadly not...

**Comment by thebeanogamer** [comment]
And mine will expire very soon.
