### ISSUE TITLE
Add a command to the bot for "Fdisk, format, re-install, do-da, do-da"

### ISSUE THREAD

**Issue by ThisIs0xBC** [CyberDiscovery/meta#250]
Add a command to the bot for "Fdisk, format, re-install, do-da, do-da"

Add a command called !jingle or something fitting that just makes the bot say "Fdisk, format, re-install, do-da, do-da"

### *Proposed Solution:*
Add command to bot that triggers "Fdisk, format, re-install, do-da, do-da" text to be sent

**Comment by thebeanogamer** [comment]
No

**Comment by ThisIs0xBC** [comment]
Why? I thought the whole point of the meta was to be professional and allow for constructive criticism and feedback? "No" doesn't really justify you closing the issue whatsoever, especially before anyone else even got a say in it

**Comment by Bottersnike** [comment]
It's an in-joke that about 30 people will get, and both you and espyy going and spamming it in every single channel almost certainly didn't help your cause.

**Comment by ThisIs0xBC** [comment]
There are loads of inside jokes that only some people on the server understand, yet they have their own commands?

**Comment by NilsIrl** [comment]
> There are loads of inside jokes that only some people on the server understand, yet they have their own commands?

We should remove all of them
