### ISSUE TITLE
Updating the Year roles

### ISSUE THREAD

**Issue by picapi** [CyberDiscovery/meta#252]
Currently, we have year roles for members, for years 10 to 13, presumably targeted at the English system given they were established when CD was primarily targeted at England. Things have changed since then, and it's probably time for them to get an update.

Potential changes:
- Including systems outside of England.
In Scotland, secondary years are different from the UK, with S6 being the final year roughly equivalent to Y13, S5 being roughly Year 12 and so on.  In Northern Ireland, the years are one greater, with Year 14 in NI being equivalent to Year 13 in England.
It may be good to clarify the equivalent years in the readme channel in some manner.

- Adding a Year 9/S2/Year 10(NI) role/channel
With Cyber Discovery expanding to 13 yos this September, this incorporates an additional year group, and we should probably make a channel for them alike the other year groups.

**Comment by NicholasG04** [comment]
Agree with adding Year 9. Don't think it's necessary to include BTEC systems like the Scottish or Irish - they can convert themselves

**Comment by picapi** [comment]
A Year 9 role was added; there hasn't currently been any changes regarding other regions of the UK but these changes may jot be needed, at least at this time, and as a result I'm closing my own issue.
