### ISSUE TITLE
Ban use of !rank in #overflow

### ISSUE THREAD

**Issue by AdamBromiley** [CyberDiscovery/meta#253]
# Title Of Issue

### *A description of the issue:*
Similar to !urban being banned in #general, !rank just creates unwanted spam in #overflow.

### *Proposed Solution:*
Ban !rank in #overflow. I've yet to see it contribute to genuine discussions in the channel, people just use it as #bot-commands because they cba to scroll down the channel list.

**Comment by Sockmower** [comment]
who actually unironically cares

**Comment by skiros-habib** [comment]
no we need to just get rid of dyno

**Comment by Sockmower** [comment]
> no we need to just get rid of dyno

I can get behind this

**Comment by thebeanogamer** [comment]
> no we need to just get rid of dyno

But `!rank` is Mee6...

**Comment by skiros-habib** [comment]
Guess Mee6 has to go as well as Dyno

**Comment by Little-Green-Guy** [comment]
Its really annoying when i check #overflow and just see a load of bot commands. I muted #bot-commands because i dont care about them, but i dont want to mute overflow as sometimes there is conversation.

**Comment by lightspeedana** [comment]
This is pretty much inactive now, but a PR can be made if this is still a topic of concern. Otherwise, bot commands and more spammy topics are kind of #overflow's purpose, so we can close this issue now, since it's not really going anywhere.
