### ISSUE TITLE
Remove the longer auto-react messages

### ISSUE THREAD

**Issue by jb3** [CyberDiscovery/meta#254]
Similar to #246 we should remove the longer auto-react messages.

Specifically these auto-reactions:

```py
    "revive": "nou",
    "@here": "who pinged",
    "@everyone": "who pinged"
```

They are noisy and spammy. Discussion in developer general has decided that the single emoji auto-reactions are not bad and can stay but the longer ones are not adding much to the conversation.

Proposed solution is to remove these from the triggers dictionary which I can handle should we give this the go ahead. Please comment below with any additional thoughts on the issue.

**Comment by thebeanogamer** [comment]
Moving them to single emoji doesn't seem like a bad idea, moving `nou` to 🙅, and the pings to `:whopinged:`. As I recall, we have had issues with using server emoji in the past, but I know Dyno supports that.

**Comment by jb3** [comment]
Okay, nice

**Comment by lightspeedana** [comment]
Please, can we do this; the who pinged messages are very annoying at times, especially as they completely take away from the importance of when you're actually pinging everyone for a legitimate reason and are a real pain to remove. Wholeheartedly agree with @thebeanogamer 's suggestion.

**Comment by jb3** [comment]
Okay, are we good to go ahead with this? Willing to write a PR later today :thumbsup:

**Comment by teamshortcut** [comment]
Sounds good, thanks @jos-b!
