### ISSUE TITLE
Change the community dev role colour

### ISSUE THREAD

**Issue by Bentechy66** [CyberDiscovery/meta#255]
# The community dev role colour

### *A description of the issue:*
The community dev colour is a boring and bland dark green resembling the contents of a swamp. To better represent the contributions devs make to the community, it should be changed.

### *Proposed Solution:*
Change to a better colour (For example, light turquoise, I'm open to suggestions)

**Comment by skiros-habib** [comment]
#7e57e5 is a nice purple but may conflict with vet 2019

**Comment by teamshortcut** [comment]
To mirror my comment in #256, if the community can agree a colour then we're happy to change it.

**Comment by lightspeedana** [comment]
This issue is fairly inactive now, unfortunately, but if the devs can agree on a colour and PR it, I'm happy to approve it!
