### ISSUE TITLE
Sort out "Veteran" colours and "Quote Czar"

### ISSUE THREAD

**Issue by AdamBromiley** [CyberDiscovery/meta#256]
### *A description of the issue:*
Namely the Veteran 2018/19 roles looking funny colours and being different.

And this is real nitpicking but "Quote Czar" (a grey role) is higher ranked than "Level X" (a blue role) so is separated from all the other grey roles making it look ugly when viewing people's roles :)

### *Proposed Solution:*
Have a vote on various options in #meta such as:
- Have them the same colour.
- Elite colour.
- Slightly lighter Elite shade so there's not too much of one colour during summer.
- Some other colour(s).

And fix the Quote Czar stuff by making it lower ranked than the Level role or making the Level roles grey I guess?

**Comment by teamshortcut** [comment]
If the community can agree on a colour, we're quite happy to change it; Quote Czar I've just moved down.

**Comment by lightspeedana** [comment]
Somewhat related to #255, but I think we should simply deal with this once new colours are agreed, PRd and voted on 😄
