### ISSUE TITLE
Activity Nights

### ISSUE THREAD

**Issue by fractalpenguin** [CyberDiscovery/meta#257]
# Activity Nights
### *A description of the issue:*
Although server membership steadily keeps increasing, as people join the server upon hearing of the programme, activity either remains stagnant, or decreases, as previously active members end up leaving the server.

### *Proposed Solution:*
Activity nights in order to have "something to do" that is not restricted to what ends up to be the same types of conversations repeatedly.

Examples could include, but are not limited to:

- Multiplayer matches. These could be either short term (Mario Party, Mario Kart) or longer in duration (Civ V, Factorio)
- Movie nights. Server members vote for a movie to watch (within reason), and arrangements are made to stream it.

**Comment by jerbob** [comment]
Mario Party 7 (via Dolphin) sounds like it could be fun, but it only supports up to 4 players at a time. The 8-player deluxe mode requires people to share controllers, which doesn't really work through netplay. Also the multiplayer mode for Mario Kart Double Dash requires splitscreen, which doesn't look great at low (<1080p) resolutions.

Generally, Dolphin games are super fun but we'd need to split people into teams and make appropriate voice channels for them.

Jackbox Party Pack could be pretty fun as an alternative?

**Comment by thebeanogamer** [comment]
This is something I'd absolutely be in support of. Whilst we are expecting to see a bump in activity when year 3 launches on the third, many of those members will stick around for long enough to ask for Assess help then run off. Being more than just a source of help will help the server grow and make life more interesting for existing members.

With regards to movie nights, I'm not sure what (if any) legal issues would arise, but that's something that can be looked into.

Perhaps we could look at integrating a schedule into ![CyberDiscovery/cyberdiscovery.github.io](https://cyberdiscoverycommunity.uk), or just keep it simple with a Google Calendar. A Discord channel of upcoming events might work better for people who are less involved with the server, so they don't have to go anywhere else to get info about upcoming events. All things that can be discussed.

As far as game choice, it would be good to see a mix of premium titles (Factorio, GMod, Civ 5), and free to participate stuff (Pretend You're Xyzzy, Jackbox) so we can get as many people involved as possible. I’m happy to throw some of my free Google Cloud credit into game servers if that’s needed, although we’d probably have to manage it a bit more closely than the most recent Minecraft server which was completely hands off and was left up long after people stopped using it.

![image](https://user-images.githubusercontent.com/3729048/63304552-4ef7cd80-c2db-11e9-98ed-07f9ed112edb.png)
_We are going to need to to TTT at some point though_

**Comment by thebeanogamer** [comment]
> 
> 
> Mario Party 7 (via Dolphin) sounds like it could be fun, but it only supports up to 4 players at a time. The 8-player deluxe mode requires people to share controllers, which doesn't really work through netplay. Also the multiplayer mode for Mario Kart Double Dash requires splitscreen, which doesn't look great at low (<1080p) resolutions.
> 
> Generally, Dolphin games are super fun but we'd need to split people into teams and make appropriate voice channels for them.
> 
> Jackbox Party Pack could be pretty fun as an alternative?

Yeah, Dolphin stuff can be a lot more work, but with sufficient planning, that could be great.

**Comment by jerbob** [comment]
> Yeah, Dolphin stuff can be a lot more work, but with sufficient planning, that could be great.

Agreed, and this might actually be a good time to use the Wiki feature for this repo.
A "Game Night" entry could be useful for people who want a guide for setting up Dolphin etc.

**Comment by thebeanogamer** [comment]
> 
> 
> > Yeah, Dolphin stuff can be a lot more work, but with sufficient planning, that could be great.
> 
> Agreed, and this might actually be a good time to use the Wiki feature for this repo.
> A "Game Night" entry could be useful for people who want a guide for setting up Dolphin etc.

And the living nightmare that is installing Garry's Mod

**Comment by Bottersnike** [comment]
A factorio server would be lit. The headless server is pretty non-intensive, and I believe it won't actually validate user profiles too, so anybody with a less-that-legitimate-copy would still be able to participate.

_Note to self: `verify_user_identity` in `factorio/data/server.settings.example.json`_

**Comment by thebeanogamer** [comment]
> 
> 
> A factorio server would be lit. The headless server is pretty non-intensive, and I believe it won't actually validate user profiles too, so anybody with a less-that-legitimate-copy would still be able to participate.

Grrrr piracy

**Comment by picapi** [comment]
Seems like a fantastic idea; I'd love to take part in some of these - and would also be happy pitching in logistically if needed ;D
I feel like when looking for community games you usually want to look for games with:
- high player lobby counts, so everyone can play together
- either free, such as an MMO or fortnite or ubiquitous enough that people will have it such as Minecraft; lowers the barrier to entry as much as possible
- Keeps people in the game playing for as long as possible eg no permaout conditions or short rounds; means people don't get left by the wayside where possible ;D

I'd also, in reference to above comments, recommend we try to stay within legal constraints - offline modes are cool but distributing cracked stuff I imagine is less so.
Regarding movie nights, it might be a pain to do, but in theory people could locally source the media, and then something of a simulwatch could take place - although this could easily become a bit of a pain with larger numbers I imagine.

**Comment by thebeanogamer** [comment]
>
> 
> either free, such as an MMO or fortnite or ubiquitous enough that people will have it such as Minecraft; lowers the barrier to entry as much as possible

_I'm so sorry_
![image](https://user-images.githubusercontent.com/3729048/63305967-c845ef00-c2e0-11e9-801d-d7618a3c30fa.png)

**Comment by jerbob** [comment]
![image](https://user-images.githubusercontent.com/25161069/63306489-abaab680-c2e2-11e9-98d7-24090b7f6896.png)
> I'm so sorry

same

**Comment by thebeanogamer** [comment]
Server members selected at random so as to not keep repeating them:

![image](https://user-images.githubusercontent.com/3729048/63306236-b153cc80-c2e1-11e9-8b18-1f134d8e0c2f.png)
![image](https://user-images.githubusercontent.com/3729048/63306341-0b549200-c2e2-11e9-93f0-f76b876b48d0.png)
![image](https://user-images.githubusercontent.com/3729048/63306951-8cad2400-c2e4-11e9-872b-f17103b44c31.png)
![image](https://user-images.githubusercontent.com/3729048/63306597-2a075880-c2e3-11e9-9553-343b81479944.png)
![image](https://user-images.githubusercontent.com/3729048/63306771-ed882c80-c2e3-11e9-8916-877f31e641c2.png)
![image](https://user-images.githubusercontent.com/3729048/63306896-58d1fe80-c2e4-11e9-9afe-3cdbf3c723f3.png)
![image](https://user-images.githubusercontent.com/3729048/63307086-004f3100-c2e5-11e9-8660-9d6b0b969831.png)
![image](https://user-images.githubusercontent.com/3729048/63307173-58863300-c2e5-11e9-8de2-b6449098c6b4.png)
![image](https://user-images.githubusercontent.com/3729048/63307234-9c793800-c2e5-11e9-8ed2-548880a3bc9b.png)
![image](https://user-images.githubusercontent.com/3729048/63307359-08f43700-c2e6-11e9-8621-1cc4ad90c669.png)
![image](https://user-images.githubusercontent.com/3729048/63307431-435dd400-c2e6-11e9-8b54-9e18123d0256.png)
![image](https://user-images.githubusercontent.com/3729048/63307596-d860cd00-c2e6-11e9-94c6-45f7f9f44d06.png)


I'm so so sorry.

I suppose this also counts as my suggestions for games.

**Comment by jerbob** [comment]
![image](https://user-images.githubusercontent.com/25161069/63311184-398f9d00-c2f5-11e9-8982-e2ca73ead22c.png)

**Comment by Bentechy66** [comment]
Unironically can we do deathrun on the hive (hivemc.eu) or siij

**Comment by thebeanogamer** [comment]
Another idea:
![image](https://user-images.githubusercontent.com/3729048/63344337-1e9a4880-c348-11e9-9357-b4c5d757278e.png)

**Comment by lightspeedana** [comment]
Whilst the idea very much appeals to me, can we not have an entirely game-centric focus? Some of us can't afford/don't have storage for/simply don't want to get this amount of games, especially if we didn't have any of them to begin with, but still want to be included in the activities. Nonetheless, I'm entirely open to having activity nights, so long as every now and then, the games played/activities done are completely inclusive for everyone, regardless of having certain software or not e.g. Jackbox. 

Also, methinks time for a revive:

![image](https://user-images.githubusercontent.com/17798041/63349665-c9fcca80-c353-11e9-9347-aec34f32ede9.png)

**Comment by lightspeedana** [comment]
Also @thebeanogamer @AnonGuy the amount of time you both have to make these never ceases to amaze me.

**Comment by thebeanogamer** [comment]
> 
> 
> Also, methinks time for a revive:
> 
> ![image](https://user-images.githubusercontent.com/17798041/63349665-c9fcca80-c353-11e9-9347-aec34f32ede9.png)

You raise a good point. Let me know via your platform of choice if you want an invite to the [Steam group](https://steamcommunity.com/groups/cyberdiscovery).

**Comment by NateKomodo** [comment]
Can we get this for the porn discovery server as well

**Comment by thebeanogamer** [comment]
> 
> 
> Can we get this for the porn discovery server as well

I'm almost disapointed it took you this long to come up with that one.

**Comment by NateKomodo** [comment]
@thebeanogamer Actually I only just found out this existed, and the request is genuine

**Comment by thebeanogamer** [comment]
> 
> 
> @thebeanogamer Actually I only just found out this existed, and the request is genuine

For the record, no we are not doing that.

**Comment by lightspeedana** [comment]
Wait, what about Psych? Large lobby count, hilarious in-jokes, only need a phone or tablet, and F2P so everyone can get involved; all they need is the code and it's easy to co-ordinate. Opinions?

**Comment by lightspeedana** [comment]
The only drawback is, are we going for PC so we can screenshare, or are we not restricting ourselves to any specific platform (this could open up the avenue of co-ordinated console gaming matches)?

**Comment by fractalpenguin** [comment]
It could work. I mean, variety is important, but it would probably be a good idea to conduct a survey to gather opinions.

**Comment by Sh3llcod3** [comment]
@thebeanogamer Can confirm I would be more than happy to add a schedule to our site, whether it be via Google Calendar Integration or by hand writing some JS. :+1: 

Edit: I am so sorry, I had to.

![blacklist](https://user-images.githubusercontent.com/28938427/63626655-0c483500-c5fc-11e9-8ebf-33348e421718.png)

**Comment by Bentechy66** [comment]
I'd be happy to make some sort of voting site where people can submit games / activities for a game night, admins can short list them and then a public, anonymous vote is held.

**Comment by thebeanogamer** [comment]
>
> 
> ![blacklist](https://user-images.githubusercontent.com/28938427/63626655-0c483500-c5fc-11e9-8ebf-33348e421718.png)

Oh my God it's glorious.

**Comment by thebeanogamer** [comment]
> 
> 
> I'd be happy to make some sort of voting site where people can submit games / activities for a game night, admins can short list them and then a public, anonymous vote is held.

That would be great. Would it be worth intergrating calendar into this, or is that too much feature creep? If you want, I'll setup a GitHub repo and use Netlify to deploy it onto activities.cyberdiscoverycommunity.uk or similar. Obviously we'd need to agree programming language and whatnot though.

**Comment by lightspeedana** [comment]
These have pretty much been launched now and discussion of them is now almost entirely on the server itself. Safe to say, the meta issue can be closed now since activity nights are now resolved!

**Comment by jerbob** [comment]
I think it's still important to have an issue open for this.

**Comment by jerbob** [comment]
As far as I understand, only one game night has actually been implemented, so it would be nice to have somewhere to continue to plan and aggregate ideas for further game nights. Simply having these discussions in a server channel doesn't guarantee that all interested parties have seen it.

Is there any chance this could be reopened?

**Comment by NicholasG04** [comment]
I completely agree with the aforementioned point of maybe a schedule/plan for future game nights

**Comment by RealJammy** [comment]
I mean, this hasn't been touched in months, but I'd be more than happy to host/help with the organisation of game nights/ tournaments. If this were to happen, would you rather I make brackets via challonge or a system of DMing me on Discord?
