### ISSUE TITLE
Reset the bot's CD dates auto-response

### ISSUE THREAD

**Issue by AdamBromiley** [CyberDiscovery/meta#258]
# Title Of Issue

### *A description of the issue:*
The "when does assess start" etc. auto-response is from last year. We have the dates for the one starting up (albeit they'll probably change).

### *Proposed Solution:*
Change the dates and tense in the bot's auto-response.

### *Additional Comments:*
[fill out]

**Comment by Bottersnike** [comment]
See https://github.com/CyberDiscovery/cyberdisc-bot/pull/246

**Comment by teamshortcut** [comment]
Make a bot PR; I have no idea why you've put this in meta. (cheers @Bottersnike)
