### ISSUE TITLE
Introduce a #competitions channel / calendar

### ISSUE THREAD

**Issue by picapi** [CyberDiscovery/meta#262]
# Introduce a #competitions channel / calendar
**_This issue has been posted on behalf of eohomegrownapps_**

### *A description of the issue:*
Recently, there has been a fair amount of interest regarding STEM-based competitions for teenagers on the server (including but not limited to maths/informatics/science olympiads, Cyber Centurion, Google Code-In, cipher challenge etc). To widen participation and encourage people to take part in these, it could be useful to have a read-only channel with a list of events that people might want to take part of, along with a description of them.

### *Proposed Solution:*
A few solutions, some/all of which could be implemented:

- Make a #competitions or #olympiads channel with read only permissions containing a list of fun events to participate in
- Make a #competitions-discussion or #olympiads-discussion channel to encourage discussion / for people to ask questions about thse events
- Make a calendar (Google Calendar / iCal?) with these events listed
- There exists a Discord server for discussion of maths / informatics olympiads in the UK: perhaps this could be added to #friends-of-CD?

### *Additional Comments:*
n/a

**Comment by Bentechy66** [comment]
watch ractf get rejected from it

**Comment by SSAFuze** [comment]
I'd personally support this. I think it fits in well with the server audience.

**Comment by lightspeedana** [comment]
With the introduction of #events, I feel this issue is fairly resolved now 😄

**Comment by rak1507** [comment]
I disagree
