### ISSUE TITLE
Create an FAQ Channel

### ISSUE THREAD

**Issue by Bottersnike** [CyberDiscovery/meta#264]
# Create an FAQ

### *A description of the issue:*
There are quite a few questions that keep comming up and up again in #assess, such as `Why is "functionName" not executing the function`, to give an especially annoying answer. Without meaning to be rude, these questions are typically asked by users that will ignore any responses of "Google it".

### *Proposed Solution:*
Instead of having to spoonfeed the same answers over and over, or respond with the (ignored) comment of either a lmgtfy link or "Google it", create a #faq channel where common questions can be pooled together and answered by a team of users (the mentors?). This would mean that these somewhat repetative questions can be redirected to that channel, as users are typically far more likely to follow a cross-channel link than take a proactive move and google things.

**Comment by lightspeedana** [comment]
I think this would be more suited to a PR personally, but this is something I'd have no problem with implementing, either as part of #readme or a separate channel. Brilliant idea, closing the issue due to inactivity on the thread, but make a PR for sure!
