### ISSUE TITLE
@RACTF_UK in #social

### ISSUE THREAD

**Issue by Bottersnike** [CyberDiscovery/meta#278]
# @RACTF_UK in #social

RACTF now have a Twitter account, and the plan is that every fortnight or so a small challenge will be posted, each one designed to be fairly easy to solve and take no more than 5 minutes. These challenges would probably be pretty fun for the CD server to solve, so I thought it might be nice to add the acc to the #social feed.

**Comment by AnthonyH26** [comment]
Maybe not social but #challenges as it's designed for uhhh... Challenges

**Comment by NicholasG04** [comment]
Nice advertising Botters by having it to into meta lmaoo

**Comment by lightspeedana** [comment]
I have no issue with this, although I think it would be much more suited to being in #challenges as opposed to #social for maximum recognition - a lot of people have #social muted anyways.

**Comment by Sh3llcod3** [comment]
~~What's an RACTF though?~~ :eyes:

**Comment by jb3** [comment]
Hi guys
