### ISSUE TITLE
Meta is horrendously undemocratic.

### ISSUE THREAD

**Issue by rak1507** [CyberDiscovery/meta#279]
It's ironic that after this was talked about in a previous issue, that was closed by one individual without any real outcome. It feels like 99% of the suggestions in meta are either ignored, or supported but due to the nature of how it's done people can't chime in as much as they should be able to, and then the issue is just closed by one root or sudo. Have any issues lately actually resulted in any change? 
This is why I suggest totally removing meta, and instead implementing an in-discord policy suggestion system, where anyone can suggest something that is then either approved or denied to be put in a channel where people can vote on whether or not the suggestion is good or not, and in addition potentially a new channel where people can discuss the changes.
It seems the same few users were the only ones actually using this current system, and it definitely needs an update.
Obviously, I suspect this issue will simply be closed without any further action, as that is the way this server works apparently.

**Comment by Little-Green-Guy** [comment]
I think integrating it into discord more is a good idea, however I dont think it is exactly undemocratic. Ana went through and cleared up old issues, and for most of these she suggested opening a pr.

That being said, it does almost seem as if the fact that an issue hasnt been commented upon recently gives mods reason to close it because it is inactive, despite people maybe still caring. 

Maybe have a quick vote in #polls or smth before closing to gauge whether it is still an issue? 
I think integrating it into discord would be good, however github allows us to comment on each issue individually, and is better laid out, and I dont see a way how this can be easily replicated in discord.

**Comment by ThisIs0xBC** [comment]
> however github allows us to comment on each issue individually, and is better laid out, and I dont see a way how this can be easily replicated in discord.

Just have a Meta category that has individual channels for each issue, which will be deleted upon changes being enacted (or if the staff decide to ignore it and not make any changes as usual then they can delete it once they've decided that.)
It would have to be at the bottom of the channel list as to not clutter it up

**Comment by Little-Green-Guy** [comment]
yes, although that doesnt allow anyone to freely open a meta issue.

Having a load of channels seems a little wasteful, but I suppose if they are in a category at the bottom, it probably isnt too bad.

**Comment by ThisIs0xBC** [comment]
well you make a meta issue, the mods make a channel for it and remove the meta issue. Problem solved

**Comment by Little-Green-Guy** [comment]
im not quite sure I understand, where do you make the meta issue? Here?
I suppose this does encourage more discussion as the discussion will be in the discord rather than here.
But it does seem a little pointless/annoying that we're still relying on GitHub to make the issue in the first place.

**Comment by Bottersnike** [comment]
![image](https://user-images.githubusercontent.com/7524553/66956385-3813f400-f05c-11e9-8b18-7123cd8cb387.png)
73 total issues. If you want to make 73 channels.. um.. enjoy hitting the maximum channel limit very fast.. :)

**Comment by ThisIs0xBC** [comment]
@Bottersnike Well obviously there wouldn't be 73 channels as 69 of the issues are closed? Duh. It would only be for open issues and once the community had reached a decision they would be closed and the channel deleted. As long as the community makes a decision in a timely manner, this system would be fine.

**Comment by lightspeedana** [comment]
I feel the discord integration is much more evident post-PR, and we have polled multiple times in the past on issues. I'm sorry if you feel the repository is undemocratic, but we are consistently fair and representative in staff discussions and we respond to as many PRs as possible. 

Nonetheless, we also do have lives on top of Discord which we need to manage. At times, it's difficult to immediately respond to and categorise issues - polls and issue voting is free to occur when PRs are made however, and if there is community engagement here, we will definitely address issues.

**Comment by Little-Green-Guy** [comment]
i think at least part of the problem here is the whole thing of having issues and prs
it seems really confusing, or at least i dont understand it. I think re-evaluating this system could help a lot.

**Comment by lightspeedana** [comment]
Please read my magnum opus, and hopefully some of these issues can be overcome.
