### ISSUE TITLE
Ping for Announcements

### ISSUE THREAD

**Issue by AnthonyH26** [CyberDiscovery/meta#280]
# Title Of Issue
Make a role for Announcement pinging
### *A description of the issue:*
I have recently missed several announcements as I have been inactive a bit. I feel like in the #readme channel at the bottom there should be a reaction where if you react you get a special role which whenever admins make an announcement they can ping the announcements role to let the people notified without the mess of @everyone pinging

### *Proposed Solution*
Add a Announcements role and add a react in #readme for the role to be added to you (i'm pretty sure Dyno bot can do this? if not I can probably make a PR in the Cyberdisc bot to do this (if it has perms to add roles))

### *Additional Comments:*
N/A

**Comment by Sh3llcod3** [comment]
I think this would be more suitable as a bot issue. The bot can add roles and we can definitely discuss this. Though it should be noted that for major announcements, i.e. stage opens, `@everyone` will probably still need to be pinged.

**Comment by rak1507** [comment]
Sounds good, are any mods going to acknowledge that this issue exists?

**Comment by thebeanogamer** [comment]
_You literally wrote that as a follow up to a mod commenting..._

**Comment by picapi** [comment]
As a stopgap measure, you can go into Notification Settings in Discord, and choose that for the #announcements channel, all messages should give you a notification. That way, you'll hear the notification sound and receive a notification on mobile every time something is posted into announcements! We're still looking into this though - hopefully we'll be able to update you more soon :)
