### ISSUE TITLE
Give rak the #big brave boy role back

### ISSUE THREAD

**Issue by Bottersnike** [CyberDiscovery/meta#281]
# Give rak the #big brave boy role back

### *A description of the issue:*
Rak and the community want rak to have his role, because he is a brave boy.

### *Proposed Solution:*
Re-add the role and give it to rak

### *Additional Comments:*
polls are unanimous in favour.

**Comment by NicholasG04** [comment]
Y E S

**Comment by ZomBMage** [comment]
Am in support 👍

**Comment by NicholasG04** [comment]
Just remember, [Section 13 of the Equality Act of 2010](http://www.legislation.gov.uk/ukpga/2010/15/section/13) states that:

> (3)If the protected characteristic is disability, and B is not a disabled person, A does not discriminate against B only because A treats or would treat disabled persons more favourably than A treats B.

Basically give Rak all the priviliges he deserves! FOR THE MANYYYYY

**Comment by R0w4nS** [comment]
proud of u rak my g

**Comment by Little-Green-Guy** [comment]
sad to see rak is going so long without recognition.
Stay strong, you are our hero!

**Comment by thebeanogamer** [comment]
No
