### ISSUE TITLE
unban zammo

### ISSUE THREAD

**Issue by flac** [CyberDiscovery/meta#282]
# Title Of Issue
unban zammo
### *A description of the issue:*
idk man can i be unbanned since dave did

### *Proposed Solution:*
[fill out]

### *Additional Comments:*
[fill out]

**Comment by R0w4nS** [comment]
It is clear that Dave's unban took a lot of thought and discussion and I don't think that it's fair for all banned members to suddenly jump on the "unban me" bandwagon.

**Comment by ZomBMage** [comment]
You haven't really done yourself any favours by not justifying your case

**Comment by NilsIrl** [comment]
Why were you banned?

**Comment by thebeanogamer** [comment]
Closed on Zammo's request.
