### ISSUE TITLE
Multiple suggestions to help improve server

### ISSUE THREAD

**Issue by Little-Green-Guy** [CyberDiscovery/meta#283]
# Suggestions to help improve server

## Communication
edit - now mostly covered by #327 
### *A description of the issue:*
I think a large problem is the lack of communication. We suggest things, we dont know if there has been any staff discussion or what has been said or agreed so far. We wait a while, and can become impatient, and end up being right pains in the arse and pressurising staff until we get responses. This isn't good or healthy for anyone, and it is teaching us bad habits.
You guys are humans, and have real lives, and yet its only when we explode and everything is on fire that we actually get a response half of the time. This isn't good, but it is the truth.

### *Proposed Solution:*
This issue is difficult, and doing something like making #staff public would create more problems. I think that if the staff kept us more updated, it could help. A 'we are discussing the issue privately' comment on a meta issue might not be enough, as being assured that a discussion is being had doesn't really help from experience. I think maybe more regular updates after smaller things have been agreed on, or whenever could help, before inputting the final result into the issue (which as a result may not be as long as points were already made above). This could allow the community to critique and give more input, and allow for better discussion.

### *A description of the issue:*
The result of #276 shows that staff do listen to the community and act on larger and more controversial issues as well. Previously, when looking at staff comments showing the issues that had been resolved and acted upon, they all looked very petty.
However, the problem here is that it looks like there was only actually a resolution because we kept pestering and probably drove you mad. This is the reason we pre-empt decisions, because you often don't act. Would dave really be unbanned right now if #general hadn't completely exploded and driven Ana to insanity so she prepared a response? Ultimately, the issue was resolved, and the staff proved that they do act on larger issues, but I feel like the wider issue needs to be properly solved to prevent repeats of this in the future.

### *Proposed Solution:*
I think when certain issues are resolved, a wider change of policy should be implemented to prevent repeats. Of course, this is only valid to certain issues.
For example, for #276, I think that the server would benefit from the introduction of a general amnesty on bans after a set period of time. This allows the staff to prove that it's not just because we can end up being dicks that action is taken, and ultimately, people change over time, they *learn* from mistakes, and I know its cheesy to say, but if people don't make mistakes, they wont learn from them, so I think that provisionally unbanning after a set period of time, be it 1 month to a year (but it should be set), will allow for banned members to learn and try again. The ban period should be long enough to deter simple spammers, and punishment after an unban for the continued breaking of rules showing they haven't learned should be treated more harshly.

~~## Temporary bans
In a similar vein to the previous point, I think that the introduction of temporary bans would allow for a greater range of punishments, the jump from a mute to a permanent ban seems a bit harsh.~~
edit: temporary bans have now been used in the past and are incorporated into the new proposed set of rules.

## Meta issues and PRs
As I mentioned in #279, I think the whole meta system of having both issues and PRs is very confusing, or at least it is to me. I think it would be beneficial to the server and the relationship between staff and the community to review this system.

## Make a #warn-log
edit - mostly covered by #322 
I think creating a TMHC style #warn-log channel could be beneficial. While members can sometimes complain that #logs isn't public, staff explain why it isn't, and their reason is valid. I feel like this would be a good compromise.

## Reform warns
Point from Nick:
> Also, I think that adding in punishments for warnings would be good to make them have a use and that they should be used more sparingly and less as jokes. I was very unhappy to get warned for 'doxing' by posting a CD Steam group as well as two other, in my opinion, slightly strange warns. Warns tend to lack any detail.

## Add webhooks for comments in meta
This could help a little, I believe Fuze originally suggested it, so it has probably already been discussed in #staff but I thought I would also add it here to have a more permanent record of it in an easier to find place.

---
I wanted to finish by saying we appreciate the work you do, and we do recognise that you are also humans. But I think blaming everything on this and not trying to improve these, or ignoring these issues is a mistake. I think that trying to change things like I have suggested above could help the server, and the relationship between the staff and the community, so we don't end up in bloody disputes so often. Thank you.

**Comment by NicholasG04** [comment]
Firstly, I do not support making #staff public. Form my experience of moderating large ish servers (~5k) there's a reason staff conversations are private - to make the server better and ensure that staff can aid the server and its population positively. It'd be very unfair to just force staff to keep everything quite so open and I think it'd be detrimental to both the server and the staff by being so scrutinised for every comment. Also, it'd only load to staff using DMs more so wouldn't change anything in reality.

I think temp bans could be a good idea obviously when used correctly. I don't view them as an alternative to permanent bans, however.

Don't get the point of a warn-log channel. I trust staff judgement and if an individual has an issue with it then talking to the staff member themselves would be a better solution in my opinion. Also, I think that adding in punishments for warnings would be good to make them have a use and that they should be used more sparingly and less as jokes. I was very unhappy to get warned for 'doxing' by posting a CD Steam group as well as two other, in my opinion, slightly strange warns. Warns tend to lack any detail.

I think that people do, however, need to realise the importance of staff discretion. Judgement can be an awful thing, but when applied correctly such as through the brilliant moderation team people should trust this more.

It seems to me that some of the mod team is unhappy by the actions of the community, and this presents a very sad state of affairs. I do believe that we, an a community, are doing something completely wrong to be putting staff in this position of great displeasure and that this is something everyone needs to act on immediately.

My utmost appreciation for all the efforts the staff put into the server and also to yourself for what I think maybe some good suggestions.

**Comment by NicholasG04** [comment]
It doesn't matter what the situation ever is in life, but the people *nearly* always win. If enough people want change to happen and they aren't being unfairly and forcefully held back then some way they will get that change. It shouldn't come to that. Ever.

**Comment by Little-Green-Guy** [comment]
As to the #staff channel, I completely agree that this couldn't work, I didn't express these reasons in the op, but I do agree. I do still think that there is a problem here though, which is why I suggested my update idea, however this is very open to improvement as I'm not sure how much it will help or if it is feasible.

As to #warn-log, I get your points, this idea mostly arose because of the complaints about #logs in the past, but I dont really see that much benefit anymore. I do think that it might be of benefit though.

I like your idea of adding punishment to warns, as they are almost a collectors item, and their purpose is fulfilled by normal 'dont do that' from a member of staff.
I will quote you in the op to make it more obviously a point of discussion for this issue.

Edit: as to your last point, this is probably true most of the time, but it isn't working in Hong Kong!

**Comment by Little-Green-Guy** [comment]
so I was talking to Bros, and I learnt that replies are generally only made after all the mods have discussed it. This makes complete sense, however the issue that this means that we can be left waiting for a long time with no response, as if it hadnt been discussed at all by the staff is still an issue.
Maybe if you dont want to post updates on what had been discussed so far, maybe even just updates on if discussions have started, then updates on when a few people have discussed and then when only a few people are left could help waiting time.
The problem is that we have no idea if its been discussed, and we would rather it had at least started being discussed, because we put time into writing a response, and even if you do have lives and dont check meta the whole time, you have the responsibility to respond to suggestions given to you in the platform you set up within a reasonable timeframe. Of course this will vary because exams, work, etc. But more transparency will help.

**Comment by NicholasG04** [comment]
~~i thought the point of meta was for everyone to be able to discuss together, not for staff to post the official staff view after they've discussed it privately~~

**Comment by Trefonix** [comment]
Hi, 

I'd like to say thanks for the suggestions. We work incredibly hard to make this server the best it can be, and it's great to have another perspective on some issues. I understand if it's a little frustrating to have to wait 2 days for this acknowledgement, but we're all busy people who have to work around other commitments. I'm going to raise this in #staff, and I will get you an official response as soon as possible. 

Regards,

Trefonix

**Comment by Little-Green-Guy** [comment]
Thanks!

**Comment by lightspeedana** [comment]
Hi guys, thanks so much for the suggestions! We've discussed these issues at length and are making sure they get solved ASAP. I'm closing the issue as we resolve these problems, but definitely stay tuned as changes are being made for sure 😄

**Comment by lightspeedana** [comment]
Reopened at @Little-Green-Guy's request.

**Comment by Little-Green-Guy** [comment]
you dont care, i need to stop caring
