### ISSUE TITLE
Make a #TeamTrees announcement

### ISSUE THREAD

**Issue by Little-Green-Guy** [CyberDiscovery/meta#288]
A lot of you have probably seen youtube videos about teamtrees with the goal to raise $20M by 2020, and for every dollar donated, the Arbor Day Foundation will plant a tree.

Lets put an announcement in #announcements for it to help raise more awareness and money!

Website is teamtrees.org

**Comment by skiros-habib** [comment]
Yes @thebeanogamer can we do this please?

**Comment by NicholasG04** [comment]
Ngl I think there are better causes to raise money for

**Comment by Little-Green-Guy** [comment]
I had hoped this would be a quick issue for an announcement that, while not related to the server, is still important.
It hasn't been quick and I'm not sure how much point there is in leaving this open.
If staff come along later and think an announcement for this would be cool, me closing this now will not stop them.
