### ISSUE TITLE
Essential keyword reply in addition to preexisting Essentials

### ISSUE THREAD

**Issue by S10MC2015** [CyberDiscovery/meta#290]
Can you add essential start and end as a keyword reply thing in addition to the preexisting essentials start and end? It will help so much.

also, the issue template isn't showing up for me for some reason.

**Comment by SSAFuze** [comment]
Could you explain what you mean? As far as I am aware, “essentials start” and “essentials end” triggers the bot.

**Comment by SSAFuze** [comment]
On re-reading, I may have misunderstood. Are you suggesting adding “essentials” without the s as a key word?

**Comment by S10MC2015** [comment]
I am suggesting that in addition to the regular "essentials" keyword there could also be "essential" as a keyword that triggers the same text as the "essentials" keyword.

EX
As of the moment: 
essentials start ---> "dialog1"

Proposal:
essentials start ---> "dialog1"
essential start ---> "dialog1"

**Comment by ZomBMage** [comment]
I'm surprised this hasn't been mentioned already, but this isn't really the place for this. A PR to the bot would be much more fitting.

**Comment by lightspeedana** [comment]
I think this has been opened as a bot PR suitably and is now safe to close as a result. Thanks so much for the dev! 😄
