### ISSUE TITLE
Politics channel during election period

### ISSUE THREAD

**Issue by Trefonix** [CyberDiscovery/meta#291]
Politics channel during election period

We send people to overflow for all their shitposting needs. The shitposting and the politics is mixed.

Create a heavily moderated politics channel open during the election period.

Enforce rules on respect for other people's beliefs.

**Comment by NicholasG04** [comment]
:somewhatthis:
#politics channel all the time
I don't think this should be one of those pieces of shit channels where a real debate can't happen but some light rules on not being a dickhead would be good. I don't think heavily moderated is ideal especially when mods are already busy

we just need #politics man lmao

**Comment by Trefonix** [comment]
I'd be happy to be a neutral speaker during a scheduled debate period. All other periods be non chaired.

**Comment by NicholasG04** [comment]
how about we have scheduled voice chat times with priority speaker given to a different speaker every time so we can keep it community involved? it'd be a fun way to do things I think. people can put a msg in #politics if they want to speak and then speaker can unmute them or something????

**Comment by NicholasG04** [comment]
actually no, just priority speaker and then we can have support and shit heard by people

**Comment by NicholasG04** [comment]
OR Me#9187 AS PERMANENT SPEAKER - VERY RESPONSIBLE AND TRUSTWORTHY. ALL IN ALL BEST GUY EVER. ONLY ONE CMA. Doesn't really know what brexit is - adds to the fun!

**Comment by ksambhi** [comment]
Raising my support my some sort of poltics channel

**Comment by ksambhi** [comment]
I think debating and discussion though are two separate things e.g. debating party policy (I believe a recent debate happened on taxes in #overflow?) is different to a discussion of the day's political events, as has been done on e.g. important Commons' votes such as the Brexit deal meaningful votes (which of course you don't want to be as heavily moderatored.

Moreover, a speaker or any moderator would have to be checking the channel all the time as debate just kinda happens.  For example, our discussion on the commons' votes could become debates very quickly if two people ahd opposing views and started well, um, arguing.

Solution:
- two channel: may clog up server
- one channel: remember that discussion can easily turn into debate

**Comment by ksambhi** [comment]
The scheduled debate period sounds good, but yet again  I raise the point of how discussion can very quickly become debate.

**Comment by ksambhi** [comment]
As of an announcement at 20:53 on the 2nd Novemeber, the channel now exists!

**Comment by ksambhi** [comment]
I think an unintended side effect of the politics channel is that it very existence makes it easier for people to take part in political discussion when they otherwise wouldn't.  Hence why #politics can become very quickly become toxic because it is easier and more known that discussion can occur,

**Comment by lightspeedana** [comment]
Tis done.
