### ISSUE TITLE
Ping for Game support

### ISSUE THREAD

**Issue by NicholasG04** [CyberDiscovery/meta#292]
# Ping for support with CyberStart Game

### Feature Request:
Optional role that can be self-added which subscribes you to an @GameSupport ping from others. People can use this role to ask for support with Game such that members of the community can come to their rescue!

### *Additional Comments:*
Obviously not everyone will want this sort of role but for those of us that are bored with no game to do I wouldn't mind it eh

**Comment by rak1507** [comment]
I think this is a decent idea, and I would add that instead of a new role this should be what 'mentor' is now.

**Comment by NicholasG04** [comment]
If I’m honest I personally think that mentor should be re-evaluated anyway with regards to how people are decided for it…..

**Comment by rak1507** [comment]
Exactly, imo it should be something people can choose to be with mods vetoing if they deem someone not suitable, otherwise anyone should be able to be, and it shouldn't have any extra perms or anything.

**Comment by ThisIs0xBC** [comment]
At the rate they act on meta issues, by the time they decide on adding it game will be over anyway 🤷‍♀

**Comment by lightspeedana** [comment]
Mentor has now been nuked, was a fairly unused role. As to this, I will pop it in meta for voting and implement if needed. @NicholasG04 if you could please make a PR updating ROLES.md, it would be much appreciated!

**Comment by NicholasG04** [comment]
Of course, Ana! I am most grateful for your quick response.

**Comment by NicholasG04** [comment]
uh slightly confused, you've made a pr already???

**Comment by NicholasG04** [comment]
merci beaucoup mes amis
