### ISSUE TITLE
Remove Reddit from #social?

### ISSUE THREAD

**Issue by teamshortcut** [CyberDiscovery/meta#296]
# Remove Reddit posts from the #social channel

I don't know how everyone else uses #social, but I use it as a collection of relevant social media posts (basically Twitter), but Reddit posts asking for help don't really fit in there. It wasn't previously much of an issue because few people used the Reddit, but now it clogs up the channel somewhat. Unless other people have a use for it that I'm not seeing it, surely they can be removed? (or moved to their own channel if people still wanted them in Discord I guess)

**Comment by thebeanogamer** [comment]
> I don't know how everyone else uses #social

For most people, I'm told it's an education in muting channels

**Comment by rak1507** [comment]
Remove ~~Reddit from~~ #social

**Comment by Sh3llcod3** [comment]
I would say I agree to removing reddit, many posts are people writing out their methodology, which inherently provides an advantage to anyone reading who haven't done that particular challenge, I delete such posts frequently.

**Comment by Bottersnike** [comment]
Personally, I find having reddit in #social helpful because it means it's possible to respond to some of the dumber questions quickly before someone slides in and posts a full write-up or straight up incorrect information, without having to leave the sub open 24/7. I gather I'm rather unique in _not_ having #social muted anyway though, so /shrug.

**Comment by rak1507** [comment]
I guess for the reason stated above, I would say that removing reddit alone from social would be a bad idea. Preventing full writeups and responding to dumb questions quickly seems like quite a good thing.

**Comment by thebeanogamer** [comment]
Removed.
