### ISSUE TITLE
Clarify Game Support Role

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/meta#297]
# Clarify Game Support Role

### *A description of the issue:*
The new `Game Support` role seems to be being misunderstod quite a lot. Meaning no disrespect, there seem to be a lot of people who have registered for the role despite only starting Game this year. This would suggest that they think the role is for them to recieve support, not to give it. I suspect this comes from people seeing others join the role, but not the announcement.

### *Proposed Solution:*
We've already updated the join message to say `Thank you for volunteering for the Game Support role! You can remove the role at any time with !removegamesupport.` in an effort to help people who see someone else joining but not the announcement, but we think that more can be done.

An idea being discussed is locking the role behind the `HQ`, `Moon`, `Forensics`, and `Volcano` roles, and whilst this would require a bit of development work, certainly nothing insurmountable. It does also raise the question of if we should have a `Game Support` role for each base, as this would kinda seem necessary for such a system. WHY IS THE FEATURE CREEP ALARM GOING OFF?

Separately, the idea of resetting the role may be worth considering, so as to clean out the people who misunderstood, but it needs to be decided a) if it's needed, and b) how we should pick who to keep and who to kick.

**Comment by rak1507** [comment]
In nick's original issue, I did suggest the idea of having Sudos/Roots able to 'veto' people from having the role, and I definitely agree that it is ambiguous about whether or not it is for people who can *give* support, or who want to *receive* it.
Potentially, we could make the base roles pingable? I don't know if there's a way to make a second role that would excuse people from being pinged but if so that'd be good as well. Then someone could ping @HQ if they needed HQ help, etc etc. This would avoid having 4 additional game support roles, just by making use of an unused role system that's already in place.

**Comment by ThisIs0xBC** [comment]
Support role for each base that the user can only volunteer for when they have that base's completed role sounds good. Then people can do @hqhelp in the headquarters channel for example, and have people who actually know what they're doing come and assist. 

A reset sounds good too, with an announcement with it saying what the support roles are, how you get them and how to use them.

This would require minimal code changes on the bot

**Comment by thebeanogamer** [comment]
> we could make the base roles pingable?

I'm not sure I can think of a faster way to discourage people claiming them

**Comment by rak1507** [comment]
> I don't know if there's a way to make a second role that would excuse people from being pinged but if so that'd be good as well.

**Comment by Bottersnike** [comment]
I feel like splitting up the role into three roles probably wouldn't work. Without wanting to sound pretentious, people who are _actually_ going to be useful if you do an @GiveMeHelp are going to be helpful for _all_ bases. If you've just finished HQ, but have no clue about Forensics or Moon, realistically the odds are that someone who's after help is going to get lower quality help.

**Comment by rak1507** [comment]
Sure, but they'll also get lower quality help if they're getting it from a newbie on 40%.

**Comment by ghost** [comment]
@thebeanogamer I see your problem and I agree with rak and think the rank should be by request only. I think it would be smart for people to only have it if they have completed some bases. I do feel people starting this year that have done the challenges are qualified to give hints just as much as veterans. Keep in mind veterans haven’t looked at some of the challenges in a long time. Someone who just completed them will be able to more easily recall exactly how he or she did it making their hints better.

**Comment by Bentechy66** [comment]
Personally I feel like the rank should be avaliable if you have >75% total game completed; by this point you're a fair way in to each base and that seems fair to me.

**Comment by alfiejfs** [comment]
@Bentechy66 makes a good point, but there is no way to tell.

Just make it assignable to someone who has completed at least 1 (or 2) base(s). That seems like the most reasonably achievable way to make sure that the pople giving advice can give advice.

**Comment by thebeanogamer** [comment]
> if you have >75% total game completed

This would mean even more roles for us to have to verify...

**Comment by rak1507** [comment]
IMO, there's not really any *harm* in allowing everyone access who wants it, even if they have only done a tiny amount. I would hope most people who are struggling with lvl 1 HQ won't pretend that they can help with someone stuck on lvl 13, and that most people seeking help would realise if the help they're getting is decent, and if the person they're getting it from is knowledgeable.

**Comment by thebeanogamer** [comment]
This doesn't feel like a problem anymore, the issue can be reopened if this comes up again.
