### ISSUE TITLE
Make Community Developer not pingable

### ISSUE THREAD

**Issue by jb3** [CyberDiscovery/meta#3]
Looking through recent pings for Community Developer I can confirm that non of them are worth the ping.

<img width="187" alt="image" src="https://user-images.githubusercontent.com/20439493/56681067-6eca0c80-66c0-11e9-8b60-6fa70146a75a.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/20439493/56681072-725d9380-66c0-11e9-922b-a8f729a6cd60.png">
<img width="395" alt="image" src="https://user-images.githubusercontent.com/20439493/56681100-80131900-66c0-11e9-94fd-2e2987cf41aa.png">

It's been made clear that the reason the role is pingable is in the event of an emergency, but I can see no serious usage of the role ping. 

I propose that we make the Community Developer role not pingable because so far all it has been used for is spam and ping abuse. Instead, to get the attention of the developers, an `@everyone` ping should be used in the `#developer-general` channel.

**Comment by jb3** [comment]
another one to add the collection

<img width="287" alt="image" src="https://user-images.githubusercontent.com/20439493/56681465-3bd44880-66c1-11e9-8ff1-efde2a3c9422.png">

**Comment by FreddieN** [comment]
I think this is a very serious issue which needs immediate attention.

**Comment by jb3** [comment]
I agree

**Comment by alfiejfs** [comment]
Even as a non community developer, I see the issue here and agree. The excuse for the role being kept (as said in the post) was because it might be an emergency, but you can just ping all in the developer channels. 

Remove the ability to ping.

**Comment by maishams** [comment]
iF yOu'Re sO triGgeRed jUst lEavE thE seRveR

**Comment by fractalpenguin** [comment]
I approve this proposal.

**Comment by picapi** [comment]
I am in agreement that as of late the mention has been misused, and that some changes are likely in order, although I feel that having the ability to contact all Community Devs is important. The suggested solution works well when staff are present, but there may be a scenario where a user needs to contact devs urgently, and no staff are available to pass on the message at the time, in which case we should probably have a failsafe in place

A possible solution which would maintain the functionality while likely reducing the abuse of it would be to apply a similar philosophy as we do for Official Staff mentions, where the bot asks if the user is absolutely sure they wish to execute the mention - and sanctions can then clearly be given for improper use, given that a fair warning is attached before the mention is executed.

**Comment by jb3** [comment]
I'd be in favour of a solution like that, and having guild-wide rate limits so it can only be done once per hour or whatever.

In the short term however, I feel it is probably best to disable the mentioning of the role.

**Comment by ThisIs0xBC** [comment]
What the frick, all I wanted was the JS to show how many exams you had left on essentials, and I knew that one of the community devs made the code, just couldn't remember who.

**Comment by jerbob** [comment]
I'm in agreement with @picapi here, it doesn't seem too difficult to implement this since we're already doing it for Cyber Discovery Staff. If someone wants to make a PR for this, we just need @thebeanogamer to make a fake Comm. Dev role and post the corresponding Role IDs.

**Comment by jb3** [comment]
cc @CyberDiscovery/server-admin-team

**Comment by thebeanogamer** [comment]
I mean, it's doable.

**Comment by thebeanogamer** [comment]
I question if it's needed though, I've never seen it be used legitimately.

**Comment by REDACTED-REDACTED** [comment]
I can't see that a situation would ever arise that needs the urgent attention of all com devs not like our services run peoples life support or anything.  The easiest solution is to make it non pingable but for what ever reason you lot never do anything simply.  So the second easiest solution is to have two identical roles one which can be pinged and a second that can't then just let com devs opt in or out. but realistically just make it none taggable.

**Comment by thebeanogamer** [comment]
And on a related note, we should probably add the ability for people to be blocked from staff tags.

**Comment by jb3** [comment]
Either way, the issue is that community developer is pingable and it probably shouldn't be.

On an unrelated note, maybe we should add rate limits for official staff tags.

**Comment by jb3** [comment]
Also please can we just disable comm dev pings now thanks.

**Comment by jb3** [comment]
@teamshortcut Considering you just muted me for raising the issue, I'd advise you to take a read of the comments on this issue.

**Comment by jerbob** [comment]
@teamshortcut Considering you just muted me for raising the issue, I'd advise you to take a read of the comments on this issue.

**Comment by teamshortcut** [comment]
We've had cases previously where there was legitimate use for pinging Community Developers, but as the size of the server has grown, I'm open to accept that it may not be a brilliant idea to keep the current system. I would be more in favour of a system similar to the Official Staff one, as it would hopefully deter trolls from actually pinging, while retaining the ability to ping if actually needed. However, if enough were in favour _please hold while we implement new suggestions system for voting_ I'd be happy to disable it as pingable; as @jos-b rightly points out, in many cases an @ everyone in #developer-general would accomplish most of the same effect in many cases.

**Comment by jerbob** [comment]
Besides our server growth (which is fairly sub-standard), not all Community Developers are working on the same project. The only "legitimate" use for pinging Community Developers that comes to mind is if the bot dies, and even then people who work solely on the website would be pinged unnecessarily. With an @everyone in #developer-general, we'd still be pinging some staff members who are largely inactive.

Most of our community developers aren't actively working on any of our projects, so in most cases we can just ping people individually.

**Comment by thebeanogamer** [comment]
I'd be inclined to agree with @teamshortcut.

**Comment by jerbob** [comment]
I'd be inclined to agree with @jos-b.

**Comment by jb3** [comment]
I'd be inclined to agree with @AnonGuy

**Comment by REDACTED-REDACTED** [comment]
I'd be inclined to agree with @AnonGuy

**Comment by jb3** [comment]
I'd be inclined to agree with @REDACTED-REDACTED.

**Comment by jerbob** [comment]
I'd be inclined to agree with @jos-b.

**Comment by REDACTED-REDACTED** [comment]
I'd be inclined to agree with @AnonGuy .

**Comment by jb3** [comment]
I'd be inclined to agree with @AnonGuy.

**Comment by jerbob** [comment]
I'd like to hear @joker314's viewpoint on this issue.

**Comment by REDACTED-REDACTED** [comment]
All the pointless pings and emails have just made me think.  Me, George and Joe were the first com devs and to the best of my recollection not one ping I got has ever been relevant to me 😆 plz fix all you have to do is literally toggle a slider.

**Comment by thebeanogamer** [comment]
Are you happy now?
![image](https://user-images.githubusercontent.com/3729048/56850817-8c38e980-68ff-11e9-9476-b102434c975b.png)

**Comment by REDACTED-REDACTED** [comment]
Yes @jos-b @AnonGuy well played boys

**Comment by jerbob** [comment]
Good job team

**Comment by jb3** [comment]
Well done lads, another win.
