### ISSUE TITLE
make a role for modcast

### ISSUE THREAD

**Issue by Little-Green-Guy** [CyberDiscovery/meta#300]
got no time rn but can we have a role thats pinged when modcast
maybe an announcement each tim ethat pings the role
self assign the role and all
kthxbai

edit:
just for clarity, me and I'm sure a few others would like to be pinged when modcast episodes are released. Few things actually get an \@everyone in #announcements, and I'm not sure if modcast would. I also wouldn't mind being pinged when modcast is being recorded in the server, and thats something more likely to go in #general or #voice, and definitely won't be an \@everyone.

A self assigned role allows people to choose if they want to be pinged and doesn't rely on others to try and remember who wants to be pinged.

**Comment by Sh3llcod3** [comment]
Interesting idea, but you know, nothing about this whole `modcast` concept is finalised at all, so we'll have to see I guess?

**Comment by Little-Green-Guy** [comment]
I suppose it all kind of depends on how its released.
But I would like to be pinged whenever modcast is recording and released, and I'm sure a few other people would too, and this is an easy way to keep track of and assign and ping those who do want to be pinged.

**Comment by Sh3llcod3** [comment]
One thing is for sure though @Little-Green-Guy we'll make sure you don't miss it.

**Comment by thebeanogamer** [comment]
Modcast is dead, long live modcast

**Comment by thebeanogamer** [comment]
If modcast ever actually happens we can reopen this

**Comment by Little-Green-Guy** [comment]
bruh :'(
