### ISSUE TITLE
increase repeated character limit

### ISSUE THREAD

**Issue by Little-Green-Guy** [CyberDiscovery/meta#302]
# increase repeated character limit

### *A description of the issue:*
i cant reee properly

### *Proposed Solution:*
of course a character limit should still be in place to stop people reee'ing for a good few lines but i suggest something more sensible. Ultimately it doesnt make much of a difference to people receiving the message when its one line or less, so I suggest increasing it to something like 50. 

### *Additional Comments:*
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by teamshortcut** [comment]
50 may be one line on desktop, but is several on mobile, and seems a ridiculous amount to need for a single message... This also seems like a non-issue, but even if it weren't, 50 is an enormous jump.

**Comment by Bentechy66** [comment]
```
λ python3 -c "print('r'+'e'*50)"
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
```
50 really doesn't seem too many in my opinion.

**Comment by thebeanogamer** [comment]
The limit is hard coded in Dyno, we can't change it even if we want to.

**Comment by thebeanogamer** [comment]
Also, 🤢 Cmder

**Comment by Little-Green-Guy** [comment]
oh can we not even change it in dyno?
that sucks.
unless we disabled it and ported it into our bot

**Comment by Little-Green-Guy** [comment]
also ive just checked on my phone and 50 goes a little over one line
the number to increase it to was of course negotiable, maybe 30 or 40 would be more appropriate

**Comment by Bottersnike** [comment]
That's a lot of effort for something not-important. Reading the issue description I'd sum it up with `please disable some automatic moderation features so I can spam`, which is... uuh..

**Comment by Little-Green-Guy** [comment]
yeah it is quite a bit of effort, i understand the issue being closed.

**Comment by NicholasG04** [comment]
Time to ditch Dyno.....
