### ISSUE TITLE
Christmas Minecraft Server

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/meta#306]
Look, it's almost Christmas, it's Cyber Discovery, it's basically the law that we make a Minecraft server.

In #announcements on the Discord server you can vote between modded and vanilla. Here you can add additional comments (modpack suggestions and the likes).

This is clearly the anthem though, that much is certain: https://www.youtube.com/watch?v=lS-BfZfBbvU

**Comment by NicholasG04** [comment]
no yogscast shit I beg

it should be 'Holidays' by OSCP

**Comment by lightspeedana** [comment]
h o w  a b o u t  n o 
No but seriously what does Christmas have to do with Minecraft?
And is everyone going to actually use this?

**Comment by thebeanogamer** [comment]
> h o w a b o u t n o

Yes

>  No but seriously what does Christmas have to do with Minecraft?

Well, when it's christmas eve and no snow's falling down, and you're all around, no there's no one around, you play minecraft

>  And is everyone going to actually use this?

Yes

**Comment by Little-Green-Guy** [comment]
> And is everyone going to actually use this?

Yes

**Comment by lightspeedana** [comment]
It was you THERE'S the Minecraft Christmas link ☹️ I am very upset and disappointed at having the song in my head @thebeanogamer you should be ashamed and feel awful

**Comment by thebeanogamer** [comment]
It was, I'm sure you are, I am, I do

**Comment by NicholasG04** [comment]
Close I beg lol

**Comment by thebeanogamer** [comment]
Nah

**Comment by Little-Green-Guy** [comment]
vanilla best

**Comment by SSAFuze** [comment]
Please dont make me do what I had to last year which was to ask beano to give me a step by step guide on how to install the mods

**Comment by NicholasG04** [comment]
are you that incapable fuze? lol

**Comment by thebeanogamer** [comment]
> Please dont make me do what I had to last year which was to ask beano to give me a step by step guide on how to install the mods

If we do modded, and we will, I'll make a guide on the activity night wiki

**Comment by ZomBMage** [comment]
I've messaged beano about this, but I'll also go ahead and post this here to offer my two cents and personal experiences, so if you guys do vote for modded, there's already some ideas on the table!
In no particular order, here are *some* recommendations.
```
FTB Ultimate Reloaded - *loads* of mods, something for everyone. Might be a bit hard to run, and isn't conveniently on the technic or twitch launchers.
FTB Stoneblock - My personal favourite so far. Changes quite a few of the mechanics of how you actually play minecraft, with lots of mods and end-game content to add to that. Can be found on Twitch launcher I believe.
RLCraft - If you're after something truly brutal. I wouldn't really recommend this for a CD minecraft server without confirming with anyone interested first, as this modpack is truly just unfair lol. This is also on the Twitch launcher.
Technic Pack is always a safe bet. (Obviously, on the Technic launcher)
Tekkit (regular) can also be similar to the above. Also on the technic server.

Considering another kind - something like Skyblock? This would be more work to set up (which I'd be willing to help with), but would certainly make an interesting change from the types we've run before! Perhaps this could be a nice middle ground - vanilla minecraft, but with variant maps!

Also - CD game nights. Why not bring on a good bit of MC Survival Games to spark things up?```

**Comment by Bottersnike** [comment]
I would probably be wary of skyblock as a fun Christmas server, because it's really hard to actually collaborate on skyblock. You either end up with lots of people on a single island, which gets hectic, or everyone on their own islands, which kills the social aspect of it. Vanilla skyblock is also super dead unless you have stuff like "server shops" etc where you can get actually useful resources, because without that there's little to do other than build huge structures and farms for little purpose.

**Comment by ZomBMage** [comment]
@Bottersnike You raise very fair points - but keep in mind that was just a suggestion. Sure, I agree, Skyblock kills the social, working-together aspect greatly. There are however other alternatives!

**Comment by Bottersnike** [comment]
Haha yeah. I'd have chipped in with modpack suggestions but I haven't played modded in sufficiently long that I can't really rattle off any decent ones (that you don't need a super-powered rig to use) off the top of my head :joy:

**Comment by ZomBMage** [comment]
> (that you don't need a super-powered rig to use)

All of the modpacks I recommended ran easily at 60fps on my 8gb RAM, i5-8250U, MX150 laptop!
I can't say what it would have been for integrated graphics solutions, but they're by no means Hexxit level ;)

**Comment by NilsIrl** [comment]
> 8gb RAM, i5-8250U, MX150

You shouldn't expect people to have such a decent laptop.

**Comment by ZomBMage** [comment]
@NilsIrl I don't - there will be people wkth better, and people with much worse, of course. But it's also fairly likely that a good chunk of the playerbase have better-specced PCs too

**Comment by ghost** [comment]
@thebeanogamer Even if the server is voted to vanilla I would suggest you implement one player sleep so the whole server does not have to wait for it to become day. You can do this with a simple data pack: https://www.madcatgaming.com/one-player-sleep-data-pack/ . And maybe make a new option “slightly modded” for mods that don’t really affect gameplay such as a mod that makes chests into presents etc.

**Comment by Tom-The-Geek** [comment]
If we go with vanilla, could we have a few quality of life datapacks, like the ones at https://vanillatweaks.net/picker/datapacks/  ?

**Comment by ghost** [comment]
Not that many @Geek202 then it’s not vanilla at all anymore.

**Comment by NilsIrl** [comment]
> I would suggest you implement one player sleep so the whole server does not have to wait for it to become day

Not enabling that can also create a sort of challenge. Depends on what the server aims to be.

> chests into presents

That is something that is best done client side using resourcepacks.

**Comment by thebeanogamer** [comment]
> Not enabling that can also create a sort of challenge. Depends on what the server aims to be.

Fun is the goal over all else

> That is something that is best done client side using resourcepacks.

That happens automatically at Christmas. Alternatively: https://bdcraft.net/downloads/xmasbdcraft-minecraft/

**Comment by ZomBMage** [comment]
> I would suggest you implement one player sleep so the whole server does not have to wait for it to become day.

Be very wary of this with a modded server. Sure, easy and simple to implement in a vanilla server build, probably not possible in a modded server. I know Forge doesn't support it, and I'd be surprised if something like CraftBukkit did either.

**Comment by NilsIrl** [comment]
> I know Forge doesn't support it, and I'd be surprised if something like CraftBukkit did either

I have 0 doubt that you could make a Bukkit plugin that would do that

**Comment by ZomBMage** [comment]
> I have 0 doubt that you could make a Bukkit plugin that would do that

I'm not sure you know, but Forge, the most common modded-minecraft binary, doesn't support bukkit plugins

**Comment by thebeanogamer** [comment]
Or, you know... https://www.curseforge.com/minecraft/mc-mods/morpheus

**Comment by ZomBMage** [comment]
> Or, you know... https://www.curseforge.com/minecraft/mc-mods/morpheus

Sure, that works too

**Comment by NilsIrl** [comment]
> I'm not sure you know, but Forge, the most common modded-minecraft binary, doesn't support bukkit plugins

Or you know...

https://www.spigotmc.org/resources/one-player-sleep.31585/
https://dev.bukkit.org/projects/sleep
https://www.curseforge.com/minecraft/bukkit-plugins/singleplayersleep2

**Comment by ZomBMage** [comment]
> > I'm not sure you know, but Forge, the most common modded-minecraft binary, doesn't support bukkit plugins
> 
> Or you know...
> 
> https://www.spigotmc.org/resources/one-player-sleep.31585/
> https://dev.bukkit.org/projects/sleep
> https://www.curseforge.com/minecraft/bukkit-plugins/singleplayersleep2

Again. These are bukkit plugins. Forge does not support these.

**Comment by AnthonyH26** [comment]
Forge does with the help of catserver or something similar ;)
https://github.com/Luohuayu/CatServer

**Comment by ZomBMage** [comment]
> Forge does with the help of catserver or something similar ;)
> https://github.com/Luohuayu/CatServer

I mean, sure, there are hacks to get plugins working with Forge. I can't find any decent documentation on CatServer, nor anyone discussing it on forums (from a quick google search), though
