### ISSUE TITLE
add votes to webhooks in #meta

### ISSUE THREAD

**Issue by Little-Green-Guy** [CyberDiscovery/meta#307]
# add votes to webhooks in #meta

### *A description of the issue:*
there are a number of people that are not happy with the current meta situation, and I do think it can be improved. Some people have suggested that meta should be moved to discord, and although this does fix some issues, I also believe it creates others, and I am unsure how much it would help, whether it would work etc.

### *Proposed Solution:*
Moving meta to discord might help, I'm not sure.
Other than that, I think that adding vote reactions to the webhooks for new issues in #meta would allow people on discord to show support etc much more easily, including on mobile (which github is horrible for). When people want to add to the discussion, they can then go to the trouble of going onto github to reply. In this sense meta being on github may help as it generally means that the extra effort means people think out responses more.

### *Additional Comments:*
This definitely wont fix all the problems with meta, but I think its a good start. Another idea that I have seen suggested is adding webhooks for comments on issues.
I also think the official staff responses often address the original meta issue and not the discussion that happened in the replies often.

**Comment by Bottersnike** [comment]
I think auto-reacting with a #polls-like reaction set on #meta would probably be an awesome idea! I'm not sure how much moving meta into Discord would help, because one of the nice things about having it here is the clear separation of conversation.

**Comment by Little-Green-Guy** [comment]
yeah, github allows things to not be lost, and also keeps issues separated, and an archive when they are closed.

**Comment by picapi** [comment]
We do bring meta issues to polls in the channel on occasion, usually after discussion of them has occured and on a specific implementation. Sometimes meta issues can be in respect to multiple issues, or may not be easily stratified into a small selection of voting reactions - but it would definitely increase the degree to which users on Discord can interact with the issues and pull requests made.

What set would be best for expression - would an emotion set suit better than straight voting, or potentially a custom set for each issue done manually?

**Comment by Little-Green-Guy** [comment]
I think the basic yes/no/maybe as in polls is needed, although more emojis could allow for more interaction without switching platforms.
maybe autoreact with the same emojis as in #polls, but maybe also allow normal reacting? Not sure about that tho.

**Comment by Bottersnike** [comment]
Maybe just encourage mods to add reactions if people ask them to, because I can imagine open-reactions leading to stuff like `N O U` being spelt out on every issue, etc.

**Comment by Little-Green-Guy** [comment]
yeah, not opening them but mods adding more if needed could be a good idea

**Comment by Little-Green-Guy** [comment]
Are there any more thoughts on this? I think just the tick neutral and cross as in #polls would be fine

**Comment by Little-Green-Guy** [comment]
you dont care, i need to stop caring
