### ISSUE TITLE
the final solution

### ISSUE THREAD

**Issue by DillFletch** [CyberDiscovery/meta#311]
Presuming you're referring to the previous issue, I feel the full response we can give is a simple, unemotional no. 

Apologies, but if there's a serious issue you have with a feasible solution, then please do open it.

_Originally posted by @lightspeedana in https://github.com/CyberDiscovery/meta/issues/310#issuecomment-571782818_

### The Final Solution
delete servvvv

**Comment by installgentoolinux** [comment]
stop

**Comment by DillFletch** [comment]
> stop

no

**Comment by Little-Green-Guy** [comment]
overall, despite how great the server can be, i have to support this final solution.

**Comment by DillFletch** [comment]
closing this issue will result in war

**Comment by DillFletch** [comment]
a big one

**Comment by SSAFuze** [comment]
This is really not the place for this incredibly off-topic discussion, come have a moan in the server (probably in #memes it seems).
