### ISSUE TITLE
Nous necessitons un salon pour francais - #français 

### ISSUE THREAD

**Issue by NicholasG04** [CyberDiscovery/meta#314]
# On a besoin d'un nouveau salon...

Dans le monde, il y a une grande problème que beaucoup des gens ne veulent pas apprendre des nouveaux langues. Je pense que c'est nécessaire encourager les gens pour parler dans les autres langues et, par ce que je peux voir, le français est le plus populaire dans ce serveur.

S'il vous plaît, pouvons-nous avoir un salon pour français ou les langues pas anglais ?

Merci !

**Comment by thebeanogamer** [comment]
> We need a new living room ...
>
> Around the world, there is a big problem that many people do not want to learn new languages. I think it is necessary to encourage people to speak in other languages and, from what I can see, French is the most popular on this server.
> 
> Please, can we have a lounge for French or languages not English?
> 
> Thank you !

**Comment by lightspeedana** [comment]
Pardon, mais non. C'est ne pas necessaire.

**Comment by NicholasG04** [comment]
Je ne suis pas d'accord.

**Comment by NicholasG04** [comment]
@lightspeedana C'est dégoûtant que tu ne peux pas voir les importances de cette problème -_-

**Comment by SSAFuze** [comment]
@NicholasG04 well the fact that it seems only 1 moderator can understand you easily may demonstrate one of the issues here....

**Comment by NicholasG04** [comment]
C'est pour les intellectuels @SSAFuze

**Comment by R0w4nS** [comment]
no u
