### ISSUE TITLE
Make Forensics higher priority than HQ to make us feel special

### ISSUE THREAD

**Issue by ir0nstone** [CyberDiscovery/meta#321]
There is a large amount of people with the HQ role at the moment, and I feel like those of us who have finished Forensics would prefer to have it take precedence so that we have a colour that sets us apart.

**Comment by Trefonix** [comment]
HQ is a more challenging base to complete, which is reflected in the ranking in the roles. Fewer people have completed Forensics base because it's more tedious than difficult.

**Comment by ir0nstone** [comment]
I mean I suppose different people find different things harder, because I definitely thought Forensics was harder. Is there any way to enable us to choose? And either way, Forensics role is still more unique due to the quantity of people who have those roles.

**Comment by Denrogh** [comment]
There is a reason why Volcano is locked behind HQ rather than Forensics. There is no way to choose in discord, I would be open to the idea of having a vote in #meta like we have done before and seeing what everyone has to say. I'm open for more debate here or on discord :)

**Comment by R0w4nS** [comment]
forensics base = bad
so forensics below
