### ISSUE TITLE
channel for logging moderator actions

### ISSUE THREAD

**Issue by Little-Green-Guy** [CyberDiscovery/meta#322]
as talked about towards the end of issue #312 I believe a public channel, perhaps of a similar style to #warn-logs in tmhc (as in #283 and mentioned in the comments of a couple of issues) would be beneficial towards the server. To be clear, I am not asking for #logs to be made public, as has been mentioned multiple times in the past, this includes deleted messages and that should not be made public. Here is the previous discussion:

> Yes so basically what I'm asking is for #logs (or a subset of it) to be made public so we can monitor moderators and nothing happens in the dark.

> This would be a great step forward, they could add to the bot so that it also uploads to a channel called #public-logs except it doesn't show deleted messages, only who posted and deleted them.

> i was thinking of something like #warn-log in tmhc where moderators manually write when people get warned, banned etc and a reason why, although actually i think your suggestion of maybe a redacted version of #logs which is made public may be better.

> Yes there should also be the reason why the people got banned because otherwise it's almost useless.

> Your points are valid, however, we try to balance fair discussion with each moderator having room for discretion. In my opinion, the improvement can be made to documenting each case and providing a short, clear justification which doesn't seem unreasonable to me.

---
Rewriting the entirety of the server rules and #readme? naa, dont think you'll get away with it that easily.
/s thank you for listening, your work is very much appreciated

**Comment by will-lynas** [comment]
Yes this would be very useful.

**Comment by Little-Green-Guy** [comment]
this solution could take a few forms, probably a channel where moderators notify when an action has been taken and provide a short reason, another idea i had recently is simply a slightly more redacted version of #logs. Discord's built in audit logs show when messages are deleted and who deleted them, so assuming dyno/which ever bot does #logs can pick up reasons for bans etc, maybe just partially mirroring #logs to a public channel, removing possibly sensitive content such as the content of deleted messages could work. this has the benefit of being automated so not taking up more of moderators time. of course i dont know exactly what #logs contains, it could just be deleted messages for all i know, so if it is the public version would need to have more than this obviously.

**Comment by Little-Green-Guy** [comment]
you dont care, i need to stop caring
