### ISSUE TITLE
clarify classification of nsfw

### ISSUE THREAD

**Issue by Little-Green-Guy** [CyberDiscovery/meta#325]
can we have clarification on what is allowed, and what is classed as nsfw?
obviously actual porn, or something with nudity is not allowed
something maybe from a clip, with suggestion but no nudity is obvs very boarderline, and i can accept that being removed
in terms of words - it feels silly to censor the word 'porn' or brands such as PornHub, you cant deny they exist
and then this carries over to logos as well. dont forget the PD server exists and beano is very proud of the colour scheme and has talked a lot about it
so can we have some clarification (and with that comes consistency) on what is and isnt classed as nsfw, maybe update the rules to clarify?

**Comment by Trefonix** [comment]
Coincidentially, this is something that we had begun to discuss over the last few days as there is genuine ambiguity. Maybe we could produce a more detailed list of things we consider acceptable and things we consider unacceptable for each channel, as well as things we always find unacceptable.

All these things need to be taken with the context that we're an open community serving 14+ year olds.

**Comment by Bottersnike** [comment]
One thing I learnt from my time moderating a server with a target market of age 10+ is that one important issue that needs remembered is that some parents will often check their child's Discord, especially in the case where it's a child doing CD with their parent's support, and the Discord account was made specifically for CD. Although not the primary focus, it's also important to think `what would a parent think if they saw this`, or even `what would the CD staff think if they saw this`.

**Comment by Little-Green-Guy** [comment]
In the meantime, i think it would be highly beneficial to both moderators and the community if moderators would notify users when their boarderline messages are deleted.

Ive said it before and i'll say it again. If i dont know that the message was deleted and i forget, i will continue to post them, creating more work for moderators, and more anger for me when i do notice.

I just noticed one of my memes had been deleted. I only noticed because i went out of my way to check for the more edgy memes that had been deleted. And frankly, i dont think saying the word 'penis' should be grounds for deletion. Around half of the population has one, and if we're honest over half of the population of the server has one.

I keep bringing up this thing of notifying users and giving reasons for deleted messages, and heres why - sometimes there truly is a need for it. Of course, for every deleted message it is excessive, but for boarderline messages it could really help. It will let the users know, so they are less likely to send similar messages - so there are fewer messages for mods to delete. They can be discussed, and maybe put into rules if necessary, clarifying our set of rules. Of course there needs to be some slack and wiggle room in the rules, as mentioned by botters multiple times, but too much slack means these messages continue to be sent, users dont know, and it doesnt to anything to reduce the gap between moderators and the community. Clarifying the rules is also how you tell users which of these boarderline messages (and which of the ones that seem not boarderline) arent allowed - *thats what the rules are there for*.

I recognise thats longer than i wanted so TD;DR: notify users when *boarderline* messages are deleted, and allow for discussion and clarification of rules. Its in everyones interests.

**Comment by skiros-habib** [comment]
what definition of nsfw do u need other than

"if you wouldnt want your parents or ur boss to see it, then its nsfw"
?

**Comment by Little-Green-Guy** [comment]
different people have different parents. I also think there's plenty that has been said by roots and other moderators of the server that I wouldnt want my parents to see, although they probably wouldnt be surprised if they did see.

**Comment by Little-Green-Guy** [comment]
If wanted i can draft what i think a more clarified set of rules/guidance about this could be, but ultimately its the mods decision and i dont think any final version would be influenced by mine ~~and i dont want to give myself hope that they will~~

**Comment by Little-Green-Guy** [comment]
you dont care, i need to stop caring
