### ISSUE TITLE
#food

### ISSUE THREAD

**Issue by Bottersnike** [CyberDiscovery/meta#326]
Long stretch, but it'd be interesting to see how much use a #food would get where people can just post pictures of their delightful concoctions they put together for lunch and make people hungry (or pictures of a nice 5* meal). Terrible pitch, but you get the idea.

**Comment by JX-CW** [comment]
Let's be honest it'd just turn into disgusting food if there was a dedicated channel. #general is good enough.

**Comment by Sh3llcod3** [comment]
Food, *where* :eyes:

**Comment by thebeanogamer** [comment]
🍏 🍎 🍐 🍊 🍋 🍌 🍉 🍇 🍓 🍈 🍒 🍑 🍍 🥭 🥥 🥝 🍅 🍆 🥑 🥦 🥒 🥬 🌶 🌽 🥕 🥔 🍠 🥐 🍞 🥖 🥨 🥯 🧀 🥚 🍳 🥞 🥓 🥩 🍗 🍖 🌭 🍔 🍟 🍕 🥪 🥙 🌮 🌯 🥗 🥘 🥫 🍝 🍜 🍲 🍛 🍣 🍱 🥟 🍤 🍙 🍚 🍘 🍥 🥮 🥠 🍢 🍡 🍧 🍨 🍦 🥧 🍰 🎂 🍮 🍭 🍬 🍫 🍿 🧂 🍩 🍪 🌰 🥜 🍯 🥛 🍼 ☕️ 🍵 🥤 🍶 🍺 🍻 🥂 🍷 🥃 🍸 🍹 🍾 🥄 🍴 🍽 🥣 🥡 🥢

**Comment by thebeanogamer** [comment]
Closed in favour of #345
