### ISSUE TITLE
Improved Meta System

### ISSUE THREAD

**Issue by elliottpp** [CyberDiscovery/meta#330]
I have come up with a concept to replace the current meta system
This could be used for inspiring the staff etc.

Basically it aims to ensure transparency and a sense of clarity when you submit an issue. Some people complain about their issues being ignored or not properly solved.

The trello is simplistic and clear.
All issues are submitted via discord and the following commands:
- initialise with` !meta`
- add a title with `!title <your title>`
- add a description with `!desc <your description>`
- submit with `!submit`

This automatically gets put into the trello list "Backlog" and is unapproved until a staff member checks over it. Then it will go through the system

Thanks!

trello: https://trello.com/b/uGAs78EI
discord to test: dm @specatron#6969

**Comment by Bentechy66** [comment]
What's the issue with the current meta system?

**Comment by elliottpp** [comment]
> What's the issue with the current meta system?

Some issues are left unanswered or felt ignored, and from what I've gathered people want more transparency with how staff sort their issues and review them

**Comment by Bottersnike** [comment]
This is literally significantly harder to use, with little gain. Conversation on Trello is tough, and significantly less open than issues here. GitHub contains a system to label issues right within it (pic related). Trello is designed for teams to track things they're working on, or bugs, not to discus said things - that's what GitHub (or usually JIRA) issues (tickets) are for. Trello is a step backwards in encouraging discussion. I'd be curious how Trello is meant to "inspire" the staff team.

![image](https://user-images.githubusercontent.com/7524553/75822787-71919580-5d98-11ea-9d32-ad6ce8fc9d43.png)

**Comment by Little-Green-Guy** [comment]
I really like this concept. Assuming this is used to replace/or integrated with the current meta system, it helps with integration between discord and github, which people have complained about for a few reasons (need to set up an account on gh to avoid dox, hard to interact on mobile, those are the only ones i had). I also like the lists you set up (backlog, to do, doing, etc), which could be integrated into github with labels, which also help with communication on the current status of staff looking at it (typically only an 'official' response is received right before the solution is done).

This could probably take form in a few ways, maybe it could be used for the 'project boards to track server changes', but i see that less likely. Maybe github has a similar api that could be used, allowing interaction with the meta through a bot, reducing the barrier for entry, or maybe meta could be moved to trello. idk, but i think its a cool concept and i hope it can act as inspiration.

**Comment by elliottpp** [comment]
>  how Trello is meant to "inspire" the staff team.

as in the concept, not trello.

**Comment by Bottersnike** [comment]
@Little-Green-Guy Trello still requires an account to use. A common way to login to Trello is using a GitHub account :).

**Comment by elliottpp** [comment]
> @Little-Green-Guy Trello still requires an account to use. A common way to login to Trello is using a GitHub account :).

You only need an account to comment, and github requires an account as well so...

**Comment by Little-Green-Guy** [comment]
yeah, when looking at that demo, u have to log into trello to make a comment

however you dont need a trello/gh account to make the issue, or you at least dont have to switch apps on mobile and struggle with gh's mobile site (although their alpha app is much better)

**Comment by Bottersnike** [comment]
And yes, GitHub has this built it. It calls them Project Boards (the name is a hint about what they're for). The key word to search around on Google for is "kanban".

> You only need an account to comment, and github requires an account as well so...

Right, but the whole point of /meta is ordered and structured discussion about issues.

**Comment by lightspeedana** [comment]
@Bottersnike I actually really like the idea, but I do agree that it's less open - perhaps it's something that we could use as a staff team and integrate it into existing discussion. We could definitely use an organisational tool, and since Trello has GH login functionality, I think it's a brilliant step in the right direction which we can use as a team to enhance our discussion and organisation here.

**Comment by elliottpp** [comment]
> contains a system to label issues right within it 

so does trello

**Comment by Bentechy66** [comment]
I currently have no problems with the github mobile site. What problems are you encountering?

**Comment by elliottpp** [comment]
> Right, but the whole point of /meta is ordered and structured discussion about issues.

To have a discussion on trello, you need an account. You don't need an account to create an issue.
Trello has a structured commenting system so?

**Comment by elliottpp** [comment]
> I currently have no problems with the github mobile site. What problems are you encountering?

I heard the problems from other people, not myself.

**Comment by Little-Green-Guy** [comment]
@Bentechy66 i always found it a pain to have to log in and type up on a site that while fine on desktop really feels like a desktop site scaled down that was too clunky
i think in the end desktop is easier full stop because you have a full keyboard etc, and the mobile site was usable, but it always felt like a pain to have to switch apps, log in, click the link in the email for the new log in location, and then navigate to the repo and issue before being able to respond and it was much slower on mobile.

**Comment by Bentechy66** [comment]
Can't you stay logged in?

**Comment by Little-Green-Guy** [comment]
well it will log you out after a while either way and generally i dont use github enough to stay logged in
plus this isnt my main github account so i keep having to switch
plus my cookies are cleared every time i close my browser, so no i really cant, but i recognise thats only my problem.

**Comment by 0xAda** [comment]
Honestly I feel like this is just finding fault for the sake of finding fault. The current meta system works fine, most people have GitHub accounts, issues not being answered won't magically be fixed by moving platform.

**Comment by ZomBMage** [comment]
> plus my cookies are cleared every time i close my browser

Is that something that most of us do? I haven't heard of anyone else doing that.
It doesn't make sense to change an established system to accommodate one or two people who could reasonably compromise?
As for mobile support, I've had no issue with it.
As for "doxes" through setting up a github account, as was said before, that's entirely on you, that was your choice when you created your account, and I don't think it's reasonable for the whole system to move just because you put your personal details on the internet

**Comment by elliottpp** [comment]
> > plus my cookies are cleared every time i close my browser
> 
> Is that something that most of us do? I haven't heard of anyone else doing that.
> It doesn't make sense to change an established system to accommodate one or two people who could reasonably compromise?
> As for mobile support, I've had no issue with it.
> As for "doxes" through setting up a github account, as was said before, that's entirely on you, that was your choice when you created your account, and I don't think it's reasonable for the whole system to move just because you put your personal details on the internet

it's not to accomodate for one or two people, it's for a wider range of people. I made it because people were saying their issues weren't being answered etc. and other problems. 

as I said in my first post, it's a concept for staff to magpie off of

**Comment by Little-Green-Guy** [comment]
> Is that something that most of us do? I haven't heard of anyone else doing that.

I would be surprised if many other people did it, read that bit right after what you quoted and you can see that i brought this bit upon myself

> change an established system

Yeah id rather a similar setup with github, where you can interact with it without leaving github, if such a setup id possible. It may not, i havent had time to look into it.

Also it really isnt just me. Personally, ive generally been in support of the gh meta system, however there are a handful of people who believe that instead it should  be wholely on discord. Ive never supported this, but i have looked for ways to integrate github into discord more as a way to make life more convenient for everyone, and also act as a compromise for those that would rather it would be on discord.

Of course switching from gh to trello is a bigger move than just adding some bot integration, and im not proposing we rush into something like that.

> As for mobile support, I've had no issue with it.

Well others have, and while it was not unusable, it was clunky. Personally, for me, this is less of an issue with the new github app, hopefully some things can be cleared up and it can come out of alpha soon.

> As for "doxes" 

Github is a platform for hosting and tracking changes etc in code. Cyber Discovery is a cyber security server where people will at least become more aware to doxing and osint, please forgive people if they dont want to make it easy to dox themselves by linking it to a more professional account they likely made when they werent thinking about questionable people on a cyber sec server doxing them for asking questions.



As i said in the testing server and here, i dont know how the mods can fit this into the current meta system or the project tracker, but i think this is a cool demo and it would be great if it could be implemented somehow, preferably through github if replacing meta (and if possible with gh).

**Comment by thebeanogamer** [comment]
As a short term plan, we've implemented some project boards on this repo ([this is the one you care about](https://github.com/CyberDiscovery/meta/projects/1)). We'll try and implement the best parts of this into there, and are very open to feedback.

**Comment by elliottpp** [comment]
just to be clear, this can be done as gh. I just used Trello as it looked more visually appealing to me but both work the same functionality wise.

**Comment by Little-Green-Guy** [comment]
looking at the github api endpoints i think it would be possible to replicate this with github instead of trello, however im not good at this kinda stuff so i probably couldnt do it myself or identify issues someone may have when developing it.

**Comment by thebeanogamer** [comment]
If I'm honest, this feels like complexity for complexity's sake. I'm not sure what real benefit we gain, and the function lost by supporting it doesn't feel worth the effort. Within GitHub, all we'd be able to do is make cards, not issues or pull requests so we wouldn't be able to make proper use of the system.

Revision of the meta system is something we're very much open to, but I'm just not sure that the bot side of this is what we need. That being said, the board style approach is something I'm more than happy to trial, and we've setup boards on this repository to relfect that.

**Comment by ghost** [comment]
To be honest github is absolutely fine especially if you have the mobile app. It’s really easy to comment from the app. You literally just have to make an account once.

**Comment by thebeanogamer** [comment]
I think we've all agreed that this isn't happening...
