### ISSUE TITLE
Stale label in code

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/meta#334]
The stale label needs to be added to the labels file and given a colour

**Comment by lightspeedana** [comment]
Stake 👀

**Comment by thebeanogamer** [comment]
🥩

**Comment by thebeanogamer** [comment]
Ana hex code for Stale plz

**Comment by lightspeedana** [comment]
HhHHHH

**Comment by lightspeedana** [comment]
Did you use the colours I gave you yesterday or someone else's?

**Comment by lightspeedana** [comment]
Because mine had a pattern so I could give you another based off that

**Comment by thebeanogamer** [comment]
Some of them, not all

**Comment by lightspeedana** [comment]
Otherwise, give me the other codes you used

**Comment by thebeanogamer** [comment]
See .github/labels.json

**Comment by thebeanogamer** [comment]
Resolved by #355
