### ISSUE TITLE
Change the stale label

### ISSUE THREAD

**Issue by Little-Green-Guy** [CyberDiscovery/meta#338]
Okay so  I'm going to start with some possible solutions to make it clear what I'm asking.
These aren't exhaustive, as always the aim is to start a discussion to find a solution that works for everyone.

1. Just don't close the issues
2. Create a 30 day reply policy (or another length) for mods and the community.
3. Just remove the stale label

Okay so onto why

1. I don't really see the point of it
2. Just because an issue no longer has any interaction, doesn't mean its not an issue
3. It just adds insult to injury. I generally respond to replies to my meta issues within a few days, if I have something to add. I don't get replies from mods that often. If one of my meta issues hasn't received activity its most likely because I'm waiting for mods to reply. Then closing (or making me interact before its closed) is kind of like punishing me for the mods not replying.
4. Even if it only closes if the last interaction was a mod, and its like 'punishing' for not replying to the mod, theres still no 'punishment' for the mods if they don't reply.

Of course I use the word punishment loosely, its not really a punishment, but its the best word I could think of to describe it.

And when talking about reasons for mod responses taking so long, please bear in mind my suggestions in previous issues to help fix this.

**Comment by 0xAda** [comment]
I think it's quite clear why the label is there. If you look at the issues list, it's a total mess. There's NINE whole issues open, there's just too many issues being created to keep track of them all without marking them as stale.

**Comment by Little-Green-Guy** [comment]
closing issues that haven't been solved doesnt solve them though. I think just closing these issues is ignoring a larger problem, which is that some issues just arent getting solved/replied to, and I think improving the communication would help with this, rather than just closing the issues.
Even if improving communication isnt the say to solve this problem, closing the issues definitely isnt.

**Comment by 0xAda** [comment]
yes but its clearly getting out of hand. There's TEN issues now, thats an 11% increase in 6 hours. If this rate continues, we will have 1.4843934e+67 issues open by the end of the year, cd is a 4 year program, if it gets renewed, we're going to have more issues than times you've complained about the server.

**Comment by Little-Green-Guy** [comment]
ah shit
you got me
guess i should just close this then

**Comment by Little-Green-Guy** [comment]
oh no thats another issue in even less time
the growth rate must be exponential
dave pls do the maths

**Comment by Little-Green-Guy** [comment]
Also apologies for the lack of label/template, obviously githubs app doesnt support this yet.

**Comment by Little-Green-Guy** [comment]
you dont care, i need to stop caring
