### ISSUE TITLE
Ana has not bothered me enough, what legal options are open to me?

### ISSUE THREAD

**Issue by SSAFuze** [CyberDiscovery/meta#339]
I was promised ana would bother me. She only induced happiness. Can I sue her? AITA?

**Comment by lightspeedana** [comment]
I will take this forward to the appropriate authorities (my superiors in the staff team). Hopefully we can come to a conclusion regarding this and I apologise for my poor conduct as a moderator in not maintaining my side of the bargain.

**Comment by lightspeedana** [comment]
Would you like to be bothered at a future occasion?

**Comment by SSAFuze** [comment]
Future bother would be agreeable

**Comment by Little-Green-Guy** [comment]
reeeeeeeeeeeeeeeeeeeeeeeeeeee
spamming meta issues 
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
bannnnnnnnnnnnnnnnnnnnn himmmmmmmmmmmm

**Comment by Trefonix** [comment]
Hi SSAFuze! 

Thank you for contacting CD Customer support. I'm sorry you haven't recieved the service that we promised, and I would like to take this opportunity to apologise on behalf of the entire staff team. We will undertake a full audit of lightspeedana's activities and take the appropriate action. In the meantime, please accept this enclosed voucher for 1 free argument. 

Regards,

Trefonix
Cyber Discovery Community Customer Relations Officer

**Comment by Little-Green-Guy** [comment]
also ESH, you had it coming

**Comment by lightspeedana** [comment]
ITA ;);)

**Comment by 0xAda** [comment]
Ana is an employee of Really Awesome Technology Ltd, you are only a mere intern, we've started an internal investigation, if it turns out she hasn't been bothering you enough, her salary will be reduced by 50% for the next month, you're also fired for not bothering ana into bothering you.

**Comment by Sh3llcod3** [comment]
![](https://media1.tenor.com/images/66c06bddaa7b5ab1807387e95302542e/tenor.gif?itemid=13172811)
