### ISSUE TITLE
#UnbanFuze

### ISSUE THREAD

**Issue by Little-Green-Guy** [CyberDiscovery/meta#340]
this is a grave miss-carriage of justice

\#UnbanFuze

\#FuzeDidNothingWrong

**Comment by SSAFuze** [comment]
I like it actually >:(

**Comment by Little-Green-Guy** [comment]
shut up fuze no one asked

**Comment by Little-Green-Guy** [comment]
do you really think you know what you want?

**Comment by Sh3llcod3** [comment]
Fuze has now been 'unbanned' (I think it was a joke, yes?)

**Comment by Sh3llcod3** [comment]
Closing as solved, if Fuze happens to get 'banned' in the near future, let us know??
