### ISSUE TITLE
Remove some rarely used emojis

### ISSUE THREAD

**Issue by JX-CW** [CyberDiscovery/meta#342]
I really want a sunglas emoji. But sadly at the current boost level, there aren't enough slots.
Currently thanks to nitro users (will) it has 9 uses. The last use was last thursday.
After the day it was first added, :breathtaking: has had 8 uses. The last use was 2 months ago (apart from my discussion of it)
After the day it was first added, :blobross: has had 7 uses. The last use was last sunday.
This is without mentioning the many duplicate emoji, or even ones conveying a similar feel.
Aster the day it was first added, :bloblovers: has has 0 uses (apart from my discussion of it)
There is no emoji like sunglas.
There will never be an emoji like sunglas.
That is, unless we take action here and now, and clean up Linus' blob collection.

**Comment by JX-CW** [comment]
![image](https://user-images.githubusercontent.com/60669186/77216964-8dc26000-6b16-11ea-946a-16639a9a3194.png)
sunglas

**Comment by NicholasG04** [comment]
I would very strongly advocate against that emoji being added.

**Comment by thebeanogamer** [comment]
> 
> 
> I would very strongly advocate against that emoji being added.

I would also do this thing

**Comment by Sh3llcod3** [comment]
Hello yes, I would like to point out that my blobs already provide plenty of sunglasses for you to display. 

![](https://cdn.discordapp.com/emojis/594261222434537472.png?size=128)

I would also say that most of the ones you have mentioned are not added by me, but if there are any ones which I have added, ping me and I will be happy to remove them. ~~Speaking of which I really need to update meta emotes list.~~

**Comment by Trefonix** [comment]
Thank you for your beautiful artwork. After careful consideration, I have decided our server will be a happier place with a badly drawn sunglass emoji.

**Comment by thebeanogamer** [comment]
_Tref you put `with` not `without`_

**Comment by NicholasG04** [comment]
i'm gonna kms

**Comment by JX-CW** [comment]
:hypers:
