### ISSUE TITLE
Ban all the alts!

### ISSUE THREAD

**Issue by woaisthisgit** [CyberDiscovery/meta#344]
There's too many alts in general. I don't even care if they're real people, it's bloody annoying. Let's just ban them all :blobhero:

**Comment by rag7** [comment]
woa why
i mean some of them are the mods alts, and half of them legit dont do anything, and plus we dont even know if some of them are alts are not. Imagine if you just ban a random person who wasnt an alt. also people wouldnt like this bc theyd be ip banned

**Comment by woaisthisgit** [comment]
Rag I'm talking about the ones which literally have alt in their name. If they aren't an alt that's a pretty dumbass move from them

**Comment by rag7** [comment]
ah ok

**Comment by Sh3llcod3** [comment]
I mean as far as I believe, the policy on alts is that they're allowed, unless its a banned member trying to evade a ban with an alt, in which case we ban. I mean the issue with banning any alt is that they're IP is blacklisted from the server meaning if their main somehow left, they wouldn't be able to join back. However if it's a particularly disruptive alt, we will do anything to address this, i.e. kicking them or muting them as required in accordance with #readme. Please alert/ping as needed. Thanks for attending this seminar. :blobstriker:
