### ISSUE TITLE
#food and #photos

### ISSUE THREAD

**Issue by elliottpp** [CyberDiscovery/meta#345]
**Is your feature request related to a problem? Please describe.**

nah not really, some channels are stale tho ngl

**Describe the solution you'd like**

people like robert are good at photography and we need a channel to appreciate the gods work
also food is kinda nice and yummy

**Describe alternatives you've considered**

adding #photos and #food 
**Additional context**

robert good at photography

**Comment by RealJammy** [comment]
Yeah I think this is a really good idea, as especially since we're in quarantine,  we need something to remind us of the outside world, and just to show our artistic talents through photography

**Comment by SSAFuze** [comment]
More dead channels, joyous

**Comment by elliottpp** [comment]
yeah its probably not essential, maybe delete other stale channels? just a suggestion

**Comment by Sh3llcod3** [comment]
*food* :eyes:

**Comment by Sh3llcod3** [comment]
@specatron111 For #food and #photos, I think #media should suffice, since there would be very few stakeholders interested in such channels, not to mention that it would create additional channels, which would confuse members, but if such a critical need does arise, feel free to reopen this one.
