### ISSUE TITLE
Webhooks for #gaming and #tech

### ISSUE THREAD

**Issue by Sh3llcod3** [CyberDiscovery/meta#348]
**Is your feature request related to a problem? Please describe.**

So, I like to curate some various content in those aforementioned channels. Although I track content from hundreds of sites, and many YouTube channels using a variety of means, I do understand that's somewhat tedious to do so by hand. **If this is something members want**, then I propose adding a webhook to those channels (mainly from YouTube, but certain sites would be great as well) from a select few high quality sources of information, this can be voted on if needed. Then I'll supplement that with other interesting articles as I find by hand.

**Describe the solution you'd like**

Webhooks for #tech & #gaming

**Describe alternatives you've considered**

The alternative is to carry on posting by hand for all of them.

**Additional context**

We all want the latest information as soon as it comes in. Whenever the next big Game is announced (looking at you Crysis remake) or teased I'm sure we all would like to know. Same goes for technology. The strides and innovations are far too great in number and complexity for me to grapple alone.

**Comment by ghost** [comment]
Don't see why not.

**Comment by thebeanogamer** [comment]
See, my problem with this is that it just turns into a link dump. #tech isn't too bad, but #gaming is currently just the "Stuff that Linus likes" show, and there are almost no messages that aren't links to YouTube, I'm not sure encouraging that would be a good thing. It pushes people to mute channels if they're just link spam, hell, I've muted #tech and #gaming for that reason.

**Comment by ghost** [comment]
Actually beano has raised some good points. I agree it would probably encourage the muting of channels so maybe not the best idea.

**Comment by n3bb** [comment]
I mean if you're arguing #gaming is a link dump, #social exists

**Comment by thebeanogamer** [comment]
Yes but that's the point of #social
