### ISSUE TITLE
Change Nitro Boost Colour

### ISSUE THREAD

**Issue by woaisthisgit** [CyberDiscovery/meta#349]
Me and Tony want the Nitro Boost to be purple. As two of four people who this change would even affect we basically have majority. So uhhh... yeah. Change please :blobreach:

**Comment by woaisthisgit** [comment]
update: we now have 3/5, confirmed majority. please implement staff

**Comment by Bottersnike** [comment]
Is there a particular shade of purple you want? (Hex colours being ideal)

**Comment by lightspeedana** [comment]
Can we please also ensure that this hex colour is different from Vet 2019?

**Comment by woaisthisgit** [comment]
Alright, mind revealing the vet 2019 and hq hex colours then?

**Comment by Alpheeexx** [comment]
Vet 2019 is #ad5dff
HQ is #a393ff

**Comment by NicholasG04** [comment]
smh what's up with the standard pink

**Comment by woaisthisgit** [comment]
weve agreed on #cc66ff
