### ISSUE TITLE
Lower the quote deletion back to 5 :thumbsdown:

### ISSUE THREAD

**Issue by woaisthisgit** [CyberDiscovery/meta#350]
No quote is reaching 10 downvotes realistically. The quotes during the 5 downvote required period were objectively better and it stopped haha funny sex. The quotes that remained were quality. Now we have stuff like 
![image](https://user-images.githubusercontent.com/62507306/79734300-6665db00-82ee-11ea-9ea1-ae5e129f99dd.png)
which isnt funny, just pi being dumb. I don't think it's quoteworthy.

**Comment by NicholasG04** [comment]
nah bro

**Comment by ZomBMage** [comment]
The issue we were having with only having the criteria being 5 downvotes is the same 5 people were downvoting virtually every quote that was made, regardless of merit.

**Comment by woaisthisgit** [comment]
Just not true :/
If you look back the good quotes got kept
At least lower it to 7, 10 is way too high

**Comment by Bottersnike** [comment]
We've already got evidence that 10 works, because quotes _have_ been reaching the threshold of 10. The thing is, you just can't see them because, well, they got deleted. (Remember, the definition of "good quotes" is very subjective, and just because _you_ vote to delete a quote, it doesn't mean others agree)

**Comment by Sh3llcod3** [comment]
@woaisthisgit I'd be compelled to agree there with Botters and Bax, 5 is too low for a deletion count, the quotes are disappearing left and right. 10 is definitely a more acceptable number.

**Comment by lightspeedana** [comment]
@woaisthisgit problem is, that only keeps quotes that are good in the view of those members - ofc, our aim is to ensure the deletion system satisfies a lot of people, but with the same people deleting the quotes only they don't find funny, the system was essentially rendered useless. As for now, this new system means the same 5 can still downvote whilst opening it up democratically to more people - still achieves the same purpose, but now everyone is happier and more quotes that other people find funny are maintained! It's a two-way street imo; different people have different senses of humour, and increasing the threshold not only lets us preserve that, but also opens it up to new opinions - is that not a favourable outcome? 😄

**Comment by Denrogh** [comment]
As the person who quoted that I have to say it is bloody hilarious. That is all

**Comment by woaisthisgit** [comment]
well i guess its not happening :blobcry: i tried my best
