### ISSUE TITLE
Migrate poll system to CDBot for custom reactions

### ISSUE THREAD

**Issue by woaisthisgit** [CyberDiscovery/meta#352]
Migrate poll sytstem to CDBot for custom reactions.

**Comment by Bentechy66** [comment]
thumbsup

**Comment by n3bb** [comment]
tbh this is a good idea

**Comment by thebeanogamer** [comment]
This is really more of an issue for https://github.com/cyberdiscovery/cyberdisc-bot

**Comment by lightspeedana** [comment]
This is a good idea, but @woaisthisgit I'd appreciate it if you could open it as an issue on https://github.com/CyberDiscovery/cyberdisc-bot/issues, just so we can add it as a feature request. Great idea nonetheless 😄
