### ISSUE TITLE
Opt-in VCS role

### ISSUE THREAD

**Issue by clubby789** [CyberDiscovery/meta#354]
**Is your feature request related to a problem? Please describe.**
With VCS, we've had a lot of new people joining the server and asking questions. When they ask about dates, we usually have to clarify if they're VCS or not due to the different systems/dates.

**Describe the solution you'd like**
A bot (or admin) given role showing that that user is doing VCS.

**Comment by SSAFuze** [comment]
Could work, but I fear that some of our members might instead see it as badge of mockery. It's nothing that can't be resolved quickly in a conversation anyway

**Comment by rag7** [comment]
Would probably be a pain to go around finding out whos in VCS and whos not tbh

**Comment by lightspeedana** [comment]
I can see where you're coming from, but I also see the drawbacks from this as mentioned by @SSAFuze. However, @rag7 honestly a bot given role isn't too difficult to give out. I can get behind it, but having a separate system entirely for people running through the non-cyberstart route is difficult for us to manage as a staff team, and if you have a solution I would love to hear it so we can get some sort of solution implemented 😄 @clubby789

**Comment by Sh3llcod3** [comment]
I mean to clear up the confusion, we could add a bot feature where if someone types `:vcs` it DMs them a series of embeds explaining the TLDR, thoughts?

**Comment by thebeanogamer** [comment]
I mean. Given that Y4 has started, is this really needed?
