### ISSUE TITLE
Add new roles for STEM subjects

### ISSUE THREAD

**Issue by EuanB26** [CyberDiscovery/meta#355]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could have some roles that people could ping when they are in need of help with some school work related to our STEM DOJO subjects, such as Maths, Science and Comp. Sci. Since we are in quarantine, people aren't going to have the normal support from their teachers, and as we all know they take ages to reply back to any email sent, which is pretty frustrating.

**Describe the solution you'd like**
Having these roles means that when someone is in need of help related to that subject, they could ping us. We would then be able to fill in the teacher position, so to speak, and would be able to help them with the question they have in a lot quicker time than an email to a teacher would be.

**Additional comments**
This role can be optional so that people can join and leave the role as they would like. Unless, of course, you guys would like to designate roles to whoever is active in the subjects?

**Comment by thebeanogamer** [comment]
I'm not at all opposed to this idea.

In terms of role assignment, I think these would work fine as self assign provided we explain them better than we did Game Support. `<subject> teacher` might work, although people could think they are an actual teacher rather than just a volunteer which would cause problems.

Open to suggestions.

**Comment by ghost** [comment]
We could use ```<subject> Student ``` or ``` <subject> Expert ``` To make sure nobody mistakes anyone for an actual teacher.

**Comment by thebeanogamer** [comment]
I like expert

**Comment by lightspeedana** [comment]
This sounds good, I can get behind it. How would we go about selecting for each role? It would be nice to have a voting process seeing as people can then pick who they would like for help and who is best suited to it and people can volunteer to be part of this selection pool.

**Comment by ZomBMage** [comment]
This is giving me very mentor-y vibes, and we know how mentor went

**Comment by lightspeedana** [comment]
I feel like Mentor was too broad but also no one really wished for cyber-y help in a one-on-one format. This is a much more focused idea and I think people ask for subject help far more often than cyber help, and this is often aimed at someone who they know is able to do the specific subject. The server is focused on cyber but we're all still students at the end of the day, and after all, we could all use some subject help in quarantine (having it taught is incredibly beneficial) whereas infosec has plenty of self-teaching resources available online.

**Comment by SSAFuze** [comment]
If it's a thing, self-assign is fine - all it is a way to be summoned if someone needs help in the STEM dojo. One way to advertise it better might be to make people realise that they will just get pings so they might not be interested. Formal selection seems a little overkill as long as advertised accurately, it sounds good

**Comment by ghost** [comment]
If this becomes a thing it might be a good idea to make more channels for some more subjects too, English maybe?

**Comment by lightspeedana** [comment]
I feel like having a selection is better than self-assign; you want people who are able to help with all sorts of queries in their subject domain - if, for example, a year 9 self-assigns the role, they may not be able to help if someone asks for A Level help. It also kind of makes pings redundant and will just lead to the death of the role if everyone starts giving themselves an expert role just for the sake of it. Volunteering and then selection in my opinion would definitely help ensure that those who have the role are not only willing to do it, but are able to as well.

**Comment by lightspeedana** [comment]
> If this becomes a thing it might be a good idea to make more channels for some more subjects too, English maybe?

I can get behind this, but we're already hitting loads of channels and then people may ask for channels for their subjects which only they will use, leading to a few becoming fairly obsolete and just clogging things up. I'm happy to make STEM Dojo into an Academics category though and open things up to more general help.

**Comment by ZomBMage** [comment]
If we make the expert roles pingable, that's a decent way of making sure people don't sign up for it if they aren't willing to help, and it's also good for people looking for help, as they can ping the role and those who have signed up to help will see it.

**Comment by ghost** [comment]
_We could have a rating system for experts_. If you get too many dislikes then you get the role removed by a bot or something. This would help reduce the amount of unqualified people with the role. (Ok this is maybe a little over thinking. Tbh this is probs too much effort)

**Comment by ZomBMage** [comment]
It's overthinking, and I fear that's more effort than it's worth

**Comment by Bottersnike** [comment]
My personal feelings on this are quite mixed. I think if the roles _aren't_ pingable they have no worth. Nobody would, while in the middle of getting help, check if the person giving them help has [subject] role, and if they didn't, ignore them. On the other hand, if the roles are made pingable, I fear there'd be the same issue as with Game Support, where the intersection of "wants to help" and "wants to be spam-pinged constantly" is incredibly small, and the people who end up with the role aren't the people you actually want to summon to help. While I don't see the addition of the roles being harmful, I also don't see them being especially useful in practice either.

And re:voting: as soon as you add something like that you're better off just linking people to the relevant stack exchange because it adds far too much complexity.

**Comment by EuanB26** [comment]
I do agree with LightspeedAna's idea, in that only certain people picked should get the role, as a year 9 most likely wouldn't be able to help a year 12 with their question. However, the STEM channels aren't used as much as the other channels, such as hq and moon, so I feel like it won't be abused. The channel is quite regulated, as there isn't many off topic conversations happening in the channels. Most of the time, in the maths channel, there's only one question being asked at a time, so it's a lot less crowded.

**Comment by NicholasG04** [comment]
I'm opposed to the use of 'expert' in self-assignable roles which, in my opinion, will likely lead to conflict over whether someone should be classed as an 'expert' in certain peoples' opinions. 

Edit: 'enthusiast'?

**Comment by EuanB26** [comment]
Or, if you feel like calling it "expert" or "enthusiast", does it have to be a fancy name? Could it just be called `<subject>`?

**Comment by thebeanogamer** [comment]
> Or, if you feel like calling it "expert" or "enthusiast", does it have to be a fancy name? Could it just be called `<subject>`?

I feel like it does, if its just called the subject name, its not clear if the people with it are those who can provide help or want to receive it.

**Comment by EuanB26** [comment]
Could you name it "<subject> helper" then? It's clear that they're there to help, and can be pinged for help. Yes, it might seem a bit like the mentor role, but it's more just for the specific subjects, rather than everything.

**Comment by EuanB26** [comment]
~~Could it be named "subject helper" then?~~

I would feel a bit demoralised if I had a role that said "I need help with <subject>", so I wouldn't have thought that would work. Also, if you had the role, you would have to ping individual people to get some help, as you wouldn't be able to ping people from the subject that can help. That kinda defeats the point of the role. It's there to allow people to ping it if they need help on the subject. Don't know whether you can do this, but maybe set its permissions to only be pinged in certain channels? Ie. you can only ping maths in the maths channel, computer science in comp. sci. etc.

Edit: didn't see that my message 12 hours ago when through, sorry

**Comment by euanong** [comment]
I think one way to decrease the likelihood of abuse is to remove any signalling benefits someone might gain from having the role (e.g. if the role were named 'expert' or 'helper')... and sometimes there might be an interesting problem in one of the STEM channels that you might not necessarily be able to solve from a 'teacher' / 'mentor' perspective but that you might want to be notified about just so you can enjoy solving problems with other people... 

I'd perhaps be slightly in favour of having just `<subject name>` as I'm not sure how much value there is in creating a mentor/mentee distinction (especially for harder problems that are posted) -- but I don't have a particularly strong opinion on this.

**Comment by ghost** [comment]
> I think one way to decrease the likelihood of abuse is to remove any signalling benefits someone might gain from having the role (e.g. if the role were named 'expert' or 'helper')... and sometimes there might be an interesting problem in one of the STEM channels that you might not necessarily be able to solve from a 'teacher' / 'mentor' perspective but that you might want to be notified about just so you can enjoy solving problems with other people... 
> 
> 
> 
> I'd perhaps be slightly in favour of having just `<subject name>` as I'm not sure how much value there is in creating a mentor/mentee distinction (especially for harder problems that are posted) -- but I don't have a particularly strong opinion on this.

Yep I back this fully, just ``<subject name>`` would be the best option here

**Comment by thebeanogamer** [comment]
We have carefully considered the idea of STEM roles as staff, but due to multiple reasons, we feel this isn't a good idea right now. We are open to other possibilities and suggestions, but we will be closing this issue due to the following reasons:


- We're not sure that the roles are currently needed
- The roles deviate from the purpose of the Discord
- Based on History, the Mentor role served a similar purpose and it didn't end up seeing much use
- The people who give out help check the respective channels quite frequently anyways, meaning a ping isn't usually necessary. 


Thank you to everyone for discussing this idea with us, we hope to hear more from you all in the future. We are open to any alternate suggestions surrounding the same topic, so if you have any other ideas you think are good feel free to make a new meta suggestion.
