### ISSUE TITLE
Ban MEE6

### ISSUE THREAD

**Issue by woaisthisgit** [CyberDiscovery/meta#356]
I thought staff wanted to get rid of external bots? Levels are bad and I dont like them therefore they should be removed for everyone. Also I think it'll be funny if we stop Ana from achieving level 80

**Comment by lightspeedana** [comment]
Too bad so sad ++ I will make sure cdbot gets levels too >:(

**Comment by woaisthisgit** [comment]
Mod abuse

**Comment by RealJammy** [comment]
Dear mod team, this is an extremely important issue at the core of the communities' heart. The mod team should reopen this issue immediately and provide a proper response.

**Comment by woaisthisgit** [comment]
![image](https://user-images.githubusercontent.com/62507306/82484183-76313480-9ad1-11ea-91f6-4105a9f1a2c4.png)
this truly is a tragic day

**Comment by thebeanogamer** [comment]
Alex play despacito

**Comment by lightspeedana** [comment]
Alex says no, don't you @Trefonix
