### ISSUE TITLE
Create the Cyberdiscovery Community Server Spoiler Police Force [CCSSPF]

### ISSUE THREAD

**Issue by HEELcaT666** [CyberDiscovery/meta#357]
It is imperative that in order to maintain the health of the server we must keep #hq, #moon, #forensics and #volc always spoiler free, so an order of CD zealots ready to protect the server from wrongdoers must be established.

The solution: The Cyberdiscovery Community Server Spoiler Police Force, trusted members with the spoiler police role that can downvote any spoiler they identify to be a threat to be removed by a bot with enough downvotes. Most encouters are usually ended peacefully, but if the wrongdoer resists and if the mods are not vigilant, the Police can quickly deal with them.

**Comment by Bentechy66** [comment]
ah i see no possible way this goes wrong

**Comment by NicholasG04** [comment]
🚨🚨🚨🚨🚨🚨🚨 Spoiler Police 🚨🚨🚨🚨🚨🚨🚨

it's like the license police but for spoilers. and that was very successful. great idea!

**Comment by thebeanogamer** [comment]
I'm sorry... I don't... What?

**Comment by Bottersnike** [comment]
In an attempt to take this somewhat seriously, I think the whole concept is flawed. If you're trying to have spoilers taken down quickly, requiring a number of votes from a small subset of users is exactly how _not_ to do that. You may want to consider instead pinging @sudo or @root, or even just pinging an online/idle staff member, to achieve the same effect - faster.

**Comment by n3bb** [comment]
Good idea but the acronym would be waaaay too long.

**Comment by thebeanogamer** [comment]
![image](https://user-images.githubusercontent.com/3729048/82742572-054f7e00-9d58-11ea-889e-50b16e18e02d.png)
Good point.
