### ISSUE TITLE
Add the BeanCon readiness scale

### ISSUE THREAD

**Issue by RealJammy** [CyberDiscovery/meta#358]
![image](https://user-images.githubusercontent.com/57639251/82742590-21ebb600-9d58-11ea-9434-f91c3666744a.png)

Whenever our great, loved Cyber Discovery server is raided, we need a system to measure the readiness to respond to another attack against the community. Therefore: I have invented the system named BeanCon to help measure readiness against new threats. This system will have 5 tiers, all named after beans, ranging from Pinto Bean for the least readiness, up to Black Turtle Bean, where all mods are on standby, and ready to react to a situation at a moments notice.

**Comment by thebeanogamer** [comment]
No

**Comment by Bentechy66** [comment]
i can get behind this

**Comment by elliottpp** [comment]
this is good idea

**Comment by thebeanogamer** [comment]
This is not a good idea
