### ISSUE TITLE
Reshuffle emoji

### ISSUE THREAD

**Issue by Bentechy66** [CyberDiscovery/meta#359]
# Move more frequently used emoji into level 1 boost status, or even 0 boost status.

As some of you may have noticed, we've just lost server boost level 2. Now, as you know, this means we lose around 50 emoji, some of which are the some of the highest-used on the server. I've compiled a list of emoji and how many times they've been used below, and suggest we reshuffle emoji as to allow for a better emojiing experience, by moving most used emoji into level 1 boost, and moving some of the lesser-used emoji down to level 2. The list is below:
<details><summary>Emoji list (Click to expand)</summary>

**128 uses:** :sunglas:

**111 uses:** :rolf:

**102 uses:** :kekW:

**54 uses:** :kek:

**51 uses:** :blobcatuwu:

**42 uses:** :hypers:

**41 uses:** :hypersH:

**34 uses:** :blobFluffyTwitsHotCoffee:

**21 uses:** :blobwave:

**19 uses:** :thonkharder:, :blobhug:, :sadglas:

**18 uses:** :blobcatlove:

**17 uses:** :reeeee:, :blurryeyes:, :blobnotlikethis:

**16 uses:** :BlobUWU:

**14 uses:** :rollsafe:

**13 uses:** :butters:

**12 uses:** :blobstriker:, :blobsob:, :bac:

**11 uses:** :ana:

**10 uses:** :blobcry:

**9 uses:** :blobthinkingglare:, :blobcatnotlikethis:, :blobsad:

**8 uses:** :rip:, :blobskid:, :blobwob:, :blobvoidwalker:

**7 uses:** :blobFluffyTwitsRecursiveChoccie:, :blobtearful:

**6 uses:** :whopinged:

**5 uses:** :god:, :blobreach:, :blobcatcuteevil:, :blobbladedancer:

**4 uses:** :ummmmm:, :quitethoughtful:, :lynesweat:, :bigblueb:, :confusedwat:, :ThisIsFine:, :blobgoodmorning:, :blobcatfbi:

**3 uses:** :PepeKMS:, :KMS:, :thinkingeyes:, :shortcut:, :this:, :blobnobully:, :surprisedpikachu:, :verythis:, :blobban:, :blobokboomer:, :blobhero:, :blobcommunism:, :blobcatsweatsip:

**2 uses:** :eggplanthand:, :dab:, :smirk:, :NoU:, :oof:, :tasty:, :WellHeyyyy:, :weirdtriangle:, :angrybentechy:, :pingthink:, :blobcheer:, :blobonfire:, :blobpatrol:, :blobfear:, :bigblued:, :blobinteresting:, :blobcosyandcomfy:, :blobcaticecream:, :blobportalthonk:, :beano:

**1 uses:** :blobhmm:, :blobhyperthink:, :blobthonk:, :OhRlyNow:, :GodRage:, :notthis:, :AgentQ:, :AngryLyne:, :blobcheeky:, :blobparty:, :blobspy:, :blobthumbsup:, :googlefire:, :DabLyne:, :blobblush:, :blobfeelsevil:, :blobsleeping:, :blobtired:, :blobupset:

**0 uses:** :thot:, :thinkharder:, :fingerguns:, :1337:, :fingerguns2:, :stingrey:, :wtf:, :lyneglasses:, :kali:, :jibhat:, :ablobbongos:, :HMMMMMM:, :BlobbleWobble:, :SuperRotatingThink:, :GoogleAssistant:, :detective:, :spooky:, :disappear:, :meow_party:, :carlton:, :nyancat:, :fbangry:, :ablobeyeroll:, :pwease:, :AwwEyes:, :pingturtle:, :you_tried:, :cat_ree:, :kermithi:, :freerealestate:, :blobidea:, :blobdetective:, :blobhammer:, :blobgo:, :blobmoustache:, :blobnogood:, :bloboutage:, :blobross:, :blobkissheart:, :blobpoliceangry:, :blobwhistle:, :blobzippermouth:, :blobthumbsdown:, :gentleblob:, :somewhatthis:, :eyes1:, :animeanger:, :angryping:, :PepoDance:, :okboomergif:, :yeetusdeletus:, :squidwarddance:, :onix:, :ablobguitar:, :cortana:, :hypeblob:, :angrybear:, :ablobhug:, :ablobexcited:, :blobcoolthonk:, :blobserverboost:, :blobdestinygunslinger:, :blobsmilesweat:, :ablobheadpats:, :ablobwavehello:, :blobokay:, :blobhappythink:, :ablobquitecool:, :ablobsleeping:, :ablobweary:, :danceplaaosert:, :ablobparty:, :blobwink:, :ablobmicrogravity:, :ablobconfused:, :ablobcatsnow:, :ablobsnow:, :ablobsnowballthrow:, :ablobsnowballhit:, :ablobwink:, :ablobgoogly:, :ablobuwu:, :ablobnervous:, :ablobthinking:, :blobawww:, :blobnomcookie:, :blobnervous:, :blobgoodnight:, :ablobraisehand:, :ablobsmile:, :ablobcookie:, :blobfistbumpleft:, :blobfistbumpright:, :blobcatft:, :bloblamp:, :blobcatburger:, :abloblaughing:, :ablobnogood:, :ablobpresents:, :ablobcatparty:, :ablobpanic:, :abloblovers:, :ablobgoodnight:, :ablobfurious:, :ablobwobroll:, :ablobwobwork:, :ablobwob:, :ablobreach:, :ablobwheee:, :ablobsalute:, :ablobbongocatpingspam:, :ablobhungry:, :ablobcry:, :ablobportalthink:, :ablobcarameldansen:, :ablobhyper:, :ablobscratchthink:, :pensivepanic:, :ablobdrool:, :ablobexcitedreverse:, :ablobgift:, :abloblamp:, :ablobmicrophone:, :ablobwavereverse:, :ablobenjoyrain:, :ablobjoy:, :aconfetti:, :ablobmaracas:, :abloblurk:, :ablobgrimace:, :ablobkeyboard:
</details>

**Comment by lightspeedana** [comment]
I can get behind this suggestion, and thanks for the list, but I've also noticed some of those are not server specific (e.g. smirk is a universal emoji). I don't really approve of the selfbotting frankly, and I don't know if you've counted reactions there.

**Comment by NicholasG04** [comment]
How recent are these uses?

**Comment by Bentechy66** [comment]
:smirk: renders because the server has an emoji called that, uses are counted from the past 4 days, one emoji per message, reactions not counted

**Comment by woaisthisgit** [comment]
A lot of the emoji in the 0 use category are animated, which have no effect on the amount of normal emojis servers can use. Should probably filter those out. Also why is only one emoji counted per message?

**Comment by Bentechy66** [comment]
> Why is only one emoji counted per message
![image](https://user-images.githubusercontent.com/19192864/82755894-9cefb380-9dce-11ea-8b5c-08124557d668.png)

**Comment by woaisthisgit** [comment]
So would that message count as a use for sunglas, rolf, or sunglas+rolf?

**Comment by Bentechy66** [comment]
that one message would count as one use for sunglas

**Comment by woaisthisgit** [comment]
Yeah thats my problem. Why doesnt it count as sunglas+rolf?

**Comment by Bentechy66** [comment]
mainly to minimize the effect of people spamming huge emoji chain

**Comment by lightspeedana** [comment]
I can get behind the reshuffling, but we need a more objective way of measuring this as these statistics are (with respect) not very credible due to some of the aforementioned issues.

**Comment by Bentechy66** [comment]
## Statistics since 01/05/2020:
<details><summary>Click to expand</summary>

**20758 uses:** :god:

**934 uses:** :kekW:

**794 uses:** :rolf:

**582 uses:** :sunglas:

**494 uses:** :kek:

**321 uses:** :blobFluffyTwitsHotCoffee:

**309 uses:** :blobcatuwu:

**260 uses:** :hypers:

**201 uses:** :hypersH:

**180 uses:** :thonkharder:

**169 uses:** :blurryeyes:

**155 uses:** :sadglas:

**148 uses:** :blobwave:

**132 uses:** :rollsafe:, :blobstriker:

**122 uses:** :reeeee:

**112 uses:** :blobcatlove:

**95 uses:** :blobthinkingglare:

**83 uses:** :BlobUWU:

**75 uses:** :blobhug:

**73 uses:** :blobnotlikethis:

**71 uses:** :thinkingeyes:

**69 uses:** :blobsad:

**66 uses:** :ummmmm:

**61 uses:** :blobreach:, :blobcry:, :eyes1:

**60 uses:** :blobcatnotlikethis:

**59 uses:** :cat_ree:

**55 uses:** :dab:

**53 uses:** :blobokay:

**48 uses:** :butters:

**44 uses:** :blobhero:, :blobinteresting:

**42 uses:** :blobcommunism:

**41 uses:** :blobcatfbi:

**40 uses:** :rip:, :blobfeelsevil:

**38 uses:** :thinkharder:

**36 uses:** :blobwob:, :blobvoidwalker:

**35 uses:** :blobcaticecream:

**34 uses:** :blobcatsweatsip:

**33 uses:** :blobhyperthink:

**30 uses:** :blobthumbsup:, :blobsob:

**29 uses:** :blobtearful:, :blobskid:

**28 uses:** :blobFluffyTwitsRecursiveChoccie:

**27 uses:** :whopinged:

**26 uses:** :blobdestinygunslinger:

**24 uses:** :blobthonk:, :blobfear:, :blobcosyandcomfy:, :blobcatcuteevil:

**23 uses:** :blobhmm:, :you_tried:, :blobnogood:

**22 uses:** :lynesweat:, :this:

**21 uses:** :PepeKMS:, :DabLyne:, :blobportalthonk:, :beano:

**20 uses:** :blobban:

**19 uses:** :blobokboomer:, :blobbladedancer:

**18 uses:** :tasty:

**17 uses:** :surprisedpikachu:, :bac:

**16 uses:** :thot:, :AngryLyne:

**15 uses:** :ana:

**14 uses:** :1337:, :wtf:, :confusedwat:

**13 uses:** :fingerguns:, :quitethoughtful:, :GodRage:, :blobawww:, :blobgoodnight:

**12 uses:** :WellHeyyyy:, :angrybentechy:, :verythis:, :blobonfire:, :blobpoliceangry:, :blobnomcookie:

**10 uses:** :KMS:, :blobnobully:, :ThisIsFine:, :blobcheer:, :blobcatburger:

**9 uses:** :blobparty:

**8 uses:** :eggplanthand:, :bigblueb:, :pwease:, :blobgoodmorning:

**7 uses:** :smirk:, :NoU:, :lyneglasses:, :weirdtriangle:, :shortcut:, :AwwEyes:, :pingthink:, :blobhammer:, :blobsmilesweat:

**6 uses:** :oof:, :stingrey:, :notthis:, :pingturtle:, :bloboutage:, :blobfistbumpleft:

**5 uses:** :blobcheeky:, :blobkissheart:, :blobzippermouth:, :blobcoolthonk:, :blobwink:, :bloblamp:

**4 uses:** :fingerguns2:, :spooky:, :kermithi:, :blobross:, :googlefire:, :bigblued:, :blobblush:, :blobnervous:

**3 uses:** :blobwhistle:, :somewhatthis:, :blobfistbumpright:, :blobcatft:

**2 uses:** :OhRlyNow:, :kali:, :AgentQ:, :freerealestate:, :blobidea:, :blobpatrol:, :hypeblob:, :blobhappythink:, :blobtired:, :blobupset:

**1 uses:** :detective:, :blobdetective:, :blobgo:, :blobspy:, :blobsleeping:

**0 uses:** :jibhat:, :ablobbongos:, :HMMMMMM:, :BlobbleWobble:, :SuperRotatingThink:, :GoogleAssistant:, :disappear:, :meow_party:, :carlton:, :nyancat:, :fbangry:, :ablobeyeroll:, :blobmoustache:, :blobthumbsdown:, :gentleblob:, :animeanger:, :angryping:, :PepoDance:, :okboomergif:, :yeetusdeletus:, :squidwarddance:, :onix:, :ablobguitar:, :cortana:, :angrybear:, :ablobhug:, :ablobexcited:, :blobserverboost:, :ablobheadpats:, :ablobwavehello:, :ablobquitecool:, :ablobsleeping:, :ablobweary:, :danceplaaosert:, :ablobparty:, :ablobmicrogravity:, :ablobconfused:, :ablobcatsnow:, :ablobsnow:, :ablobsnowballthrow:, :ablobsnowballhit:, :ablobwink:, :ablobgoogly:, :ablobuwu:, :ablobnervous:, :ablobthinking:, :ablobraisehand:, :ablobsmile:, :ablobcookie:, :abloblaughing:, :ablobnogood:, :ablobpresents:, :ablobcatparty:, :ablobpanic:, :abloblovers:, :ablobgoodnight:, :ablobfurious:, :ablobwobroll:, :ablobwobwork:, :ablobwob:, :ablobreach:, :ablobwheee:, :ablobsalute:, :ablobbongocatpingspam:, :ablobhungry:, :ablobcry:, :ablobportalthink:, :ablobcarameldansen:, :ablobhyper:, :ablobscratchthink:, :pensivepanic:, :ablobdrool:, :ablobexcitedreverse:, :ablobgift:, :abloblamp:, :ablobmicrophone:, :ablobwavereverse:, :ablobenjoyrain:, :ablobjoy:, :aconfetti:, :ablobmaracas:, :abloblurk:, :ablobgrimace:, :ablobkeyboard:

<:ablobkeyboard:704191165435478058>: 0 uses
</details>

Includes one instance of each emoji per message (eg: `:sunglas:, :rolf:, :sunglas:` will count as +1 sunglas, +1 rolf)

**Comment by clubby789** [comment]
Should probably filter out messages from bots, since I feel like humans haven't sent :god: 20758 times

**Comment by ghost** [comment]
Yeah there is literally no reason not to take the time to do this. As soon as the kinks with the stats are ironed out then this should be implemented.

**Comment by ThisIs0xBC** [comment]
I approve of this idea, most the emotes we have in the non nitro slots are from ages ago and nobody uses them :/

Things that are extremely context dependant or situation specific such as blobboutage should be moved into nitro emote space. Also, just remove the moderator emotes like :shortcut: etc please, they're useless (the only exception being :stingrey: because long live Jess' legacy)

**Comment by Sh3llcod3** [comment]
The major issue with this idea is purely the fact that right now we are sitting at -50 emoji slots. That means for any kind of rearrangement to take place we will have to axe about 50 emojis unconditionally.

Until we hit boost level 2, we will not be able to add them back and frankly some of them have no source. I've seen the suggestion to copy the URLs from the existing images and upload them later, but that's something I want to avoid, since reuploading emoji that has been copied from an existing emote will result in them being compressed even further which will introduce severe artefacting, compounding the fact that some of them are already pretty grainy. I have promised that I will take a look and rotate some of the unused ones, but they'd number in the 10s or 20s at most.

Also I think there is a small misconception regarding nitro and non-nitro emotes, you can't move still PNGs/JPGs into the nitro emote slots, it only works with animated GIFs. Rearranging would pretty much involve redoing the entire 200~250 emote stack -50 capacity for no immediate gain.

The reasonable, sensible course of action here would simply be to wait until we naturally receive two further boosts and business can return to usual. 😁

**Comment by Trefonix** [comment]
For the above reasons we won't be doing a major emoji re-shuffle, at the very least until we're back at level 2 to add them back.

**Comment by Bentechy66** [comment]
Here's a convenient(tm) zip of all the emojis that my friend sent me for you to reshuffle

https://cdn.discordapp.com/attachments/721897928918171662/721898023784808478/emojis.zip
