### ISSUE TITLE
Add TeXiT

### ISSUE THREAD

**Issue by user-6-28** [CyberDiscovery/meta#360]
**Description of the issue**

Current LaTeX implementation is inadequate and doesn't provide the features of TeXiT. TeXiT provides a much nicer interface for debugging, editing and spoilering latex among other features such as colours and a document-based approach (this stops spams of individual `$x$`s when a variable is referenced a lot in a message).
Furthermore, there is no chance TeXiT will overrun the server, which is apparently a concern?.. you can always limit the permissions if need be.

**Proposed solution**

Add TeXiT and disable the LaTeX cog in CD bot.

**Additional comments**

As nice as implementing something yourself is, when there's a better bot that someone else has made, please, just use it.

**Comment by Bottersnike** [comment]
If you're using discord chat to compose and debug a colourful TeX document, I feel you're entirely missing the point of quick inline snippets of TeX.

**Comment by user-6-28** [comment]
> debug a colourful TeX document

No one is doing that, TeXiT is popular for a reason, because it can provide exactly what is required from a LaTeX bot. Theoretically you could get a decent chunk out, but not _really_. Debugging is also useful in inline latex if you've missed a closing brace etc.

I feel you're entirely missing the point of what latex is actually used for in these channels. Sometimes display latex is required or expressions in the context of explanation is needed rather than having a bot **spam** a load of individual snippets so that, when someone is reading through the message someone sent, they have to keep on trying to search for the rendered LaTeX sent below.. it's just a complete farce.

Furthermore, what's so bad about adding an evidently more advanced LaTeX bot? Even if it is for a few occasions in your eyes (which it really isn't) nothing bad can come from it but more fruitful maths and science conversations.

**Comment by ZomBMage** [comment]
Can you provide some examples of where the mere LaTeX implementation hasn't been sufficient?

**Comment by user-6-28** [comment]
Yes, certainly. Other than the features it lacks which are pretty impossible to show that it doesn't have. Try this and send it to both bots:

```tex
Testing that \LaTeX ... so say we have
$$\frac{dy}{dx} \left[ x^x \right]$$
we can first do the following
\begin{equation} \label{simplification1}
\begin{split}
f(x) & = x^x \
 & = e^{ \ln \left( x^x \right) } \\
 & = e^{ x \ln (x) }
\end{split}
\end{equation}
This makes the differentiation trivial as we can now use the chain rule to resolve $ \frac{du}{dx} \left[ e^u \right] $ where $ u =  x \ln (x) $ \\
The end is left as an exercise for the reader.
```
Other than the obvious display differences, you'll notice that TeXiT gives an error message which will tell you that on the line `f(x) & = x^x \` there needs to be an extra backslash. Edit the message to fix this. Notice how this is impossible on cd bot.

Another useful feature is that you can delete stuff that wasn't supposed to be latex, another thing cdbot can't do.

I hope this helps.

**Comment by ZomBMage** [comment]
This isn't the kind of example I was asking for. Please provide some real-world examples of missing functionality actually impacting an academic discussion in #maths or #science

**Comment by user-6-28** [comment]
https://discordapp.com/channels/409851296116375565/457923834893434881/707581011927760916

here is the first example I could find.
_Note: This is not the latest occurrence only one that I remember allowing me to search exactly for it._

**Comment by ZomBMage** [comment]
![image](https://user-images.githubusercontent.com/29120255/83152612-ea815e80-a0f5-11ea-8c30-76edc9e48975.png)
Okay, cool. A good example - a long message from eo with multiple latex chunks inside it. I don't exactly know what you want the bot to respond with, because discord formatting won't let a bot infix images, so the whole message would have to be treated as LaTeX. This would make a huge image that's so much more cluttered than just using something like `P(X=x)` instead of using LaTeX here.

**Comment by user-6-28** [comment]
Yes that's exactly what TeXiT does - see a message a bit later that has it rendered by TeXiT. It is a lot more readable.

**Comment by ZomBMage** [comment]
Why would we need TeXiT in this case when lambda is a unicode character, and `P(X=x)` is easy enough to write, as is `x`. Just put them in code blocks

**Comment by user-6-28** [comment]
Ok, perhaps that's true for this case, but that's not all that's used in maths and secondly note how cd bot doesn't do more than 3 expressions (misses the fractions that can get reeallly messy with lots of brackets) because even the bot developers think sending image after image is spam? That misses out some expressions towards the end that TeXiT doesn't. I'm not saying that people can't manage without it.. it's about a quality of life improvement.

Yes people can live in a small house, but if they can freely buy a bigger house without any financial issues, do they? Yes.

And TeXiT doesn't cost money or anything so I don't see what's so bad with adding it?

**Comment by thebeanogamer** [comment]
Whilst I am really loving this discussion being spammed into my email, I would point out that the issues you're rasing already have a fix: CyberDiscovery/cyberdisc-bot#450

**Comment by user-6-28** [comment]
That is quite a nice addition - I did not notice that - but there are still some things missing such as editing messages. Perhaps we should create some issues on CD bot side seeing as it's now a lot closer to TeXiT level.. I'm not sure.

**Comment by thebeanogamer** [comment]
I think for the moment this can be closed, as I'd argue that the important functionality of TeXiT is now present in CDbot and dev work on CDbot's LaTeX support continues (see CyberDiscovery/cyberdisc-bot#468), so further suggestions/issues can be opened on CyberDiscovery/cyberdisc-bot.
