### ISSUE TITLE
Unban Me (for reals this time)

### ISSUE THREAD

**Issue by rak1507v2** [CyberDiscovery/meta#361]
Not to flex or anything, but I just got a CCC and elite invite. Without access to the CD server, I will be missing out on a lot of very useful info and support surrounding these things, and there's really no substitute. This is why I'd ask to be unbanned, but restricted solely to elite and CCC related channels, just so I can remain in the loop.

Also ofc, this can be a temporary arrangement, should you decide after a period of time that I still shouldn't be in the server long term.

**Comment by ghost** [comment]
I can get behind this.

**Comment by HEELcaT666** [comment]
I see no reason why not

**Comment by ThisIs0xBC** [comment]
I can't see many people not wanting this, maybe give him the FYOP but allow access to Elite channels and what not?

**Comment by R0w4nS** [comment]
Thanks 👍

**Comment by rak1507v2** [comment]
now that I've been epically unbanned can I be unbanned from the github too, it's a bit of a pain having to switch between my two accounts
thanks xoxo

**Comment by Trefonix** [comment]
We had a discussion about this and we think a reasonable compromise is to allow you access to the elite channels with the possibility of restrictions being removed later down the line. Please treat people on the server with respect and we will not need to ban you again :)

**Comment by rak1507v2** [comment]
will do 👍
