### ISSUE TITLE
Suggestions from the Community for Elite Activities

### ISSUE THREAD

**Issue by lightspeedana** [CyberDiscovery/meta#362]
## Fun Elite Activities for Elite Online 2020!
Hi guys! As you all know, Elite Online is running this year across two weeks, but as a Staff team, we've been discussing how to maintain the spirit of Elite by running a few Elite-wide activities for us all to talk and have fun from the comfort of our homes whilst maintaining the social atmosphere from the nights at in-person Elite. 

So far, we have a few suggestions (e.g. obviously gaming nights) but were wondering **what other activities you guys would want to see on the table for people doing Elite to enjoy.** **_These should be inclusive, and use software that is accessible to everyone, so the maximum amount of people aren't left out._** It would be amazing to have us all act as a group again, despite the online barrier, and I'm sure that we can make Elite as much of an amazing experience as it has been every year.

Thanks, 
Ana (lol this is my account) + Staff Team

**Comment by lightspeedana** [comment]
Also remember most of this is hypothetical - there may be some barriers at the time of Elite and we are but a team of 10 members, so we simply cannot do absolutely everything. Don't necessarily think a suggestion is GOING to happen - it may not :( but we can propose them and try and implement them.

**Comment by maishams** [comment]
scriblio elite themed if u still have that wordlist!

**Comment by maishams** [comment]
a massive paperio room

**Comment by lightspeedana** [comment]
> scriblio elite themed if u still have that wordlist!

This I can get behind, and I do indeed possess that list!

**Comment by NicholasG04** [comment]
late night elite video calls with the lads

**Comment by ghost** [comment]
I can get behind this

**Comment by RealJammy** [comment]
Jackbox

**Comment by thebeanogamer** [comment]
So the only problem with Jackbox I think is the number of people the games can handle.

 https://www.jackboxgames.com/the-ultimate-guide-to-player-counts-in-each-jackbox-game/

Ignoring audience, the games anyone would actually play peak at 8, so we'd have to organise a rotation or something.

**Comment by ghost** [comment]
Mindnight is just so much fun, they are even working on a web version I think. We should play more mindnight. Yes

**Comment by NicholasG04** [comment]
y e s

**Comment by RealJammy** [comment]
while mindnight is an amaing game, it falls under the exact same problem that beano was talking about, the 8 player max

**Comment by SSAFuze** [comment]
Perhaps it’d be more appropriate to do events per course/cohort a la real elite

**Comment by ghost** [comment]
@SSAFuze No I definitely can **not** get behind this. That would mean I can’t do activities with a lot of people from cd as it’s my first year.

**Comment by thebeanogamer** [comment]
> 
> 
> Perhaps it’d be more appropriate to do events per course/cohort a la real elite

We did cross-interact, at least between the age groups though

**Comment by lightspeedana** [comment]
Would you guys perhaps like a quiz night? Can do multiple topics and then the winner gets some kinda prize. I do one every Tuesday with my CF group (with Pi) and so I'd say it's pretty fun and successful, we join a massive VC and do a round for each person and count up points and averages - winner wins a chocolate bar posted to them and the loser gets a singular M&M. Obviously we'd have variations on CD prizes, but I'd be happy to make a quiz and run it if people can get behind it!

**Comment by RealJammy** [comment]
Yeah,  a quiz night  seems like a great idea

**Comment by mariaachim** [comment]
I like the idea of doing a quiz :)

**Comment by SSAFuze** [comment]
What about kahoot? Scalable, good fun and easy to set up

**Comment by kaovd** [comment]
Of course an always on voice channel, especially during the breaks is needed as I still need to scream at 0xBC Ben as I have not forgiven him for taking more than one brownie then not eating the second back at elite bham 2019

**Comment by thebeanogamer** [comment]
> 
> 
> Of course an always on voice channel, especially during the breaks is needed as I still need to scream at 0xBC Ben as I have not forgiven him for taking more than one brownie then not eating the second back at elite bham 2019

Yes good yes hmm yes agreed

**Comment by JoshHeng** [comment]
https://www.thewikigame.com could be good

**Comment by Bentechy66** [comment]
#meta highlight reel: reliving the best and the worst of #meta, a 4 hour cyber discovery special including detailed biographies on influential meta figures, such as teamshortcut

also includes interesting statistics, for example:
 96% of meta issues were closed without resolution
 3% of meta issues were resolved
 1% of meta issues
(numbers for illustration)

**Comment by RealJammy** [comment]
Maybe we could play a fun game of
_Catch the slack invite!_

**Comment by NicholasG04** [comment]
Gambling but with fake money !

**Comment by ghost** [comment]
Yes this, it's quite fun.

**Comment by thebeanogamer** [comment]
Elite is kill

![AggressiveGlumAuklet-max-1mb.gif](https://user-images.githubusercontent.com/3729048/91944494-12382200-ecf6-11ea-82bd-d2528b4c80e5.gif)
