### ISSUE TITLE
A formalised approach to appealing bans

### ISSUE THREAD

**Issue by Trefonix** [CyberDiscovery/meta#363]
Hi all,

Speaking personally, I'm a big believer in second chances. It should then come as no surprise when I say that I think bans should not necessarily be permanent in all situations. As an admin of the server, I wish only to ban as an absolute last resort in the interest of the community as a whole.

For the reasons outlined above, the staff team and I feel there should be a more formalised approach to appealing bans. In the interest of transparency we'd like to share some of our internal ideas for how such a system might work:

Banned users would be able to complete an online google form, and we would consider requests if they met the criteria:

- Banned without a time limit from the server
- The start date of the ban is 6 months or longer from the date of the appeal request
- They have not had an appeal rejected in the last 3 months

A ban appeal would contain the following information:

- Name of account
- Why person thinks they were banned
- A reason why person feels they should be unbanned

This request would be sent to the admin team who, taking into account community opinion, moderator opinion, reason for original ban, actions by person since ban and assessment of information inside the appeal would make a decision, ideally within a few days. If we decide to unban the person, we would likely but not universally apply a probation period where access to channels is limited. We would also decide the length of the probation period on a case by case basis.

If you have an opinion on this process or any additional suggestions, please contribute these below. 

Thanks in advance for reading this far and any contributions, you guys help us make this community the best it can be.

- Trefonix

**Comment by ghost** [comment]
Sounds like a solid plan, I don’t see much room for improvement here at this moment in time.

**Comment by ThisIs0xBC** [comment]
If possible, make it so the appeals are public and visible to all server members, or else how do we know you guys aren't just sweeping stuff under the rug/making decisions that a majority of active users disagree with?
Basically, what I'm trying to say is we want to be kept in the loop and want to be able to give feedback/our opinions on the appeal etc
