### ISSUE TITLE
LTT Webhook for #tech

### ISSUE THREAD

**Issue by n3bb** [CyberDiscovery/meta#364]
Literally every single LTT video gets posted to #tech, so we might as well add a webhook and save Linucks the trouble of adding them by hand.

**Comment by Sh3llcod3** [comment]
<img src="https://discordemoji.com/assets/emoji/9909_uwucat.png" style="height: 120px; width: 120px;" > #348

**Comment by RealJammy** [comment]
Or maybe a channel just for webhooks that isnt social, so live overflow videos and other interesting topics can also go in there

**Comment by Sh3llcod3** [comment]
Absolutely. :+1: for live overflow, definitely falls within my top tier content creators.

**Comment by thebeanogamer** [comment]
Duplicate of #348
