### ISSUE TITLE
Weekly purge of all game channels

### ISSUE THREAD

**Issue by Bottersnike** [CyberDiscovery/meta#366]
In the vein of #341, as per ~~Jammy's~~ Rowan's suggestion, this would entail clearing the game channels on a weekly schedule. Pulling this one out into its own issue because the other one died from inactivity, this is more specific, and also the person who wanted to make this is banned from the GH :P.

Edit: He who shall not be ~~named~~ unbanned let me know it was rowan not jammy

**Comment by rak1507v2** [comment]
mmm myes sensible suggestion getting suggested 18 days ago and nothing happening peak meta

**Comment by n3bb** [comment]
would assess channel be included in this too? #assess is probably most in need of weekly purges due to the mass influx of new users who may unknowingly post spoilers.

**Comment by R0w4nS** [comment]
hello there

**Comment by thebeanogamer** [comment]
To mirror what I wrote in #general, I'm not the biggest fan of this idea, but I suppose if enough people want it we can look at voting on doing it.

**Comment by RealJammy** [comment]
damn rip 😔

**Comment by ThisIs0xBC** [comment]
just stick this in the CD bot, it's uptime is like 99.99999% unless Jack has broken it again, and it isn't too hard to implement it deleting and recreating the channel every week (implementation would just be, get day, if it is monday, delete and recreate channel and reset all role perms on it (maybe there is a duplicate channel api endpoint and then we could dupe it and its permissions but not msg history, then delete old one))

**Comment by JoshHeng** [comment]
> just stick this in the CD bot, it's uptime is like 99.99999% unless Jack has broken it again, and it isn't too hard to implement it deleting and recreating the channel every week (implementation would just be, get day, if it is monday, delete and recreate channel and reset all role perms on it (maybe there is a duplicate channel api endpoint and then we could dupe it and its permissions but not msg history, then delete old one))

I would suggest bulk deleting all the messages every week instead, so permissions/channel positions don't have to be changed and channel references remain intact. This is a method on Discord.Js so I assume it's also implemented in the Python library?
Also, this would probably mean that `Jump to Message` on quotes wouldn't work anymore on purged channels, but that shouldn't really matter

**Comment by ghost** [comment]
Yeah if we want this make an issue on the bot github and I'll write it. Should be easy enough to implement.

**Comment by JoshHeng** [comment]
By the looks of it we can just bulk delete messages older than two weeks, instead of purging everything every week. This could be a better solution because it would mean the channels wouldn't be completely empty on Monday morning?

**Comment by ghost** [comment]
> By the looks of it we can just bulk delete messages older than two weeks, instead of purging everything every week. This could be a better solution because it would mean the channels wouldn't be completely empty on Monday morning?

Can we easily do that with discord.py without it being inefficient?

**Comment by JoshHeng** [comment]
> > By the looks of it we can just bulk delete messages older than two weeks, instead of purging everything every week. This could be a better solution because it would mean the channels wouldn't be completely empty on Monday morning?
> 
> Can we easily do that with discord.py without it being inefficient?

Sorry, misread the documentation.

Discord's API doesn't allow bulk message deletion after 2 weeks through the API, however we could delete messages older than 1 week instead on a nightly or weekly basis.
We can use [Get Channel Messages](https://discord.com/developers/docs/resources/channel#get-channel-messages ) to bulk fetch messages older than one week then put it directly into [Bulk Delete Messages](https://discord.com/developers/docs/resources/channel#bulk-delete-messages) to delete them (would do 100 at a time so would have to iterate).

Alternatively yeah we can just clone the channel then delete the older one, but then again we have the issue of dead channel references

**Comment by ghost** [comment]
Yeah that looks like it would work, how often would you delete the messages like that in bulk?

**Comment by seagull-pat** [comment]
How would this work with pinned messages? There are a lot of pinned either funny or informative messages in all of the channels. Also can someone reopen the issue since it's still, ya know, ~~open~~ closed.

**Comment by RealJammy** [comment]
yay!
