### ISSUE TITLE
Yes, yes I do.

### ISSUE THREAD

**Issue by rak1507v2** [CyberDiscovery/meta#367]
![image](https://user-images.githubusercontent.com/64835684/87193419-966eba00-c2f0-11ea-9437-1d4c3d015aa7.png)
![image](https://user-images.githubusercontent.com/64835684/87193442-9ec6f500-c2f0-11ea-964b-a958794fe6f4.png)

**Comment by Bottersnike** [comment]
no u

**Comment by woaisthisgit** [comment]
hi rak :wave:

**Comment by rak1507v2** [comment]
hi woa xoxo
