### ISSUE TITLE
ben for sudo

### ISSUE THREAD

**Issue by Bentechy66** [CyberDiscovery/meta#368]
finally a meta issue i can nget behind

**Comment by woaisthisgit** [comment]
inb4 closed

**Comment by rak1507v2** [comment]
this has my full support 💯

**Comment by ghost** [comment]
I can get behind this fully.

**Comment by Bottersnike** [comment]
You might find it better to wait for sudo applications to open before trying to apply...

**Comment by NicholasG04** [comment]
lmao

**Comment by woaisthisgit** [comment]
you know what they say botters the early bird gets the worm

**Comment by Bottersnike** [comment]
🪱

**Comment by rak1507v2** [comment]
nice box

**Comment by thebeanogamer** [comment]
Nah
