### ISSUE TITLE
Make #volcano visible to people with the HQ role

### ISSUE THREAD

**Issue by RealJammy** [CyberDiscovery/meta#369]
**Is your feature request related to a problem? Please describe.**
Non HQ people join the channel, and clog up the channel with unfunny 5 6 jokes, or questions that can be answered without going into the volcano chat.

**Describe the solution you'd like**
Just make it mandatory for you to have the HQ role to see volcano.

**Describe alternatives you've considered**
none as of yet

**Additional context**
![volcspam](https://user-images.githubusercontent.com/57639251/87583758-5c2c6080-c6d4-11ea-83ad-f67094041e82.png)

**Comment by RealJammy** [comment]
also to make the channel a lot more on topic

**Comment by ghost** [comment]
Omg how have we not thought of this before, can't see how this could go wrong. I can get behind this.

**Comment by samuelkitson** [comment]
I can totally get behind this. It would be really easy to set up and given the difficulty of volcano base, it would be nice to have a more focussed channel for discussing it. 
I appreciate that some people who haven’t finished hq want to ask questions about volcano, but that should be what the #cyberstart channel is for.

**Comment by woaisthisgit** [comment]
i want to feel like a l33t hacxer for unlocking volcano so i can totally support this.

**Comment by Bottersnike** [comment]
Personally, I don't see this being especially useful. It would mean that people wanting to ask questions about volcano before they reach it (e.g. "what is volcano?" or "how do I unlock volcano?") no longer have a dedicated volcano channel to ask in, and I really don't see the _benefit_ from restricting it. A lot of people posting 5.6 jokes are on volcano already, and just making it HQ-role-only wouldn't allow you to discuss HQ spoilers in there (as much as we try to verify people, it's very possible for someone to fake their way into getting the HQ role).

**Comment by R0w4nS** [comment]
Making volcano only accessible for people with the HQ role would just unnecessarily clog up general with volcano questions and discussion.

**Comment by RealJammy** [comment]
noooooooooo dont let this gooo

**Comment by RealJammy** [comment]
hm

**Comment by RealJammy** [comment]
bye bye issue
