### ISSUE TITLE
Any chance of a birthday un-probation? 🥺🥺🥺

### ISSUE THREAD

**Issue by rak1507v3** [CyberDiscovery/meta#370]
So yeah a while ago tref said I could maybe be un-probated on the 13th if I was good, and while I accept my behaviour hasn't always been stellar, I don't think I've been bad enough to warrant keeping me probated for now.

(also it would make a cwipple vewwy happy uwu 🥺🥺)

**Comment by NicholasG04** [comment]
it's ur birthday?!

**Comment by woaisthisgit** [comment]
15 07

**Comment by rak1507v3** [comment]
what do you think the 15/07 stands for

**Comment by Bentechy66** [comment]
hbd xx

**Comment by R0w4nS** [comment]
15/07 nick smh

**Comment by NicholasG04** [comment]
damn u

**Comment by NicholasG04** [comment]
u ASSUME I HVE BRAIN

**Comment by rak1507v3** [comment]
omg your initials are rak :O :O :O

**Comment by NicholasG04** [comment]
praise rak

**Comment by R0w4nS** [comment]
also happy birthday rak xx

**Comment by NicholasG04** [comment]
yes i only realised that like a week ago shut up

**Comment by rak1507v3** [comment]
thanks ben and rowan xoxo

**Comment by R0w4nS** [comment]
andy
aaron
augustus

**Comment by R0w4nS** [comment]
am i close

**Comment by R0w4nS** [comment]
np

**Comment by NicholasG04** [comment]
i would go for augustine personally

**Comment by rak1507v3** [comment]
@NicholasG04 OH MY GOD YOUR NAME IS NICHOLASG04 BECAUSE YOUR NAME IS NICHOLAS G AND YOU WERE BORN IN 2004 WHOAAAA

**Comment by NicholasG04** [comment]
happy date of birth owo

**Comment by NicholasG04** [comment]
WAIT WHAT

**Comment by rak1507v3** [comment]
mind: blown

**Comment by NicholasG04** [comment]
ARE YOU SURE?

**Comment by woaisthisgit** [comment]
imagine being a year 11 and being born in 2004 thats honestly sad

**Comment by NicholasG04** [comment]
i've just had 10 emails fly into my inbox

**Comment by R0w4nS** [comment]
adam
alistair
atlascoder

**Comment by R0w4nS** [comment]
what is the a

**Comment by rak1507v3** [comment]
lmao imagine having emails turned on for git

~~oh god oh fuck I think I have emails turned on for git~~

**Comment by NicholasG04** [comment]
a stands for...... kazza

**Comment by NicholasG04** [comment]
i just unsubscribed from the issue lol

**Comment by R0w4nS** [comment]
same

**Comment by rak1507v3** [comment]
@Rowanyeet omg you got it it's atlascoder

**Comment by R0w4nS** [comment]
just got 18 emails

**Comment by woaisthisgit** [comment]
andrews?

**Comment by NicholasG04** [comment]
WHY AM I STILL GETTING THEM AAA

**Comment by rak1507v3** [comment]
lmfao

**Comment by rak1507v3** [comment]
emails go brrrrrrrrrrr

**Comment by NicholasG04** [comment]
OH IT REENABLES EVERY TIME I COMMENT LOL

**Comment by R0w4nS** [comment]
gg

**Comment by rak1507v3** [comment]
emails go brrrrrrrrrrr

**Comment by HEELcaT666** [comment]
brrrr

**Comment by HEELcaT666** [comment]
oh shit now i get emails :notlikethis:

**Comment by NicholasG04** [comment]
rip, guess this isn't happening then
