### ISSUE TITLE
Give weddings@cyberdiscoverycommunity.uk and safeguarding@cyberdiscoverycommunity.uk an inbox

### ISSUE THREAD

**Issue by JoshHeng** [CyberDiscovery/meta#371]
**Description of the issue**
Currently weddings@cyberdiscoverycommunity.uk and safeguarding@cyberdiscoverycommunity.uk are only aliases/forwarders so emails cannot be sent from them. 
As safeguarding is an integral part to Cyber Discovery, it is vital that these important emails can be responded to using the official email. And the same goes for weddings, as they are (generally) a one in a lifetime experience and should provide any potential bridges and grooms with the courtesy of being able to converse with the proper mailbox.

**Proposed solution**
Get inboxes for weddings@cyberdiscoverycommunity.uk and safeguarding@cyberdiscoverycommunity.uk

**Comment by thebeanogamer** [comment]
£4/month/mailbox please

**Comment by n3bb** [comment]
weddings@cyberdiscoverycommunity.uk is useless, this is a server aimed at 13-18 year olds. And as beano said, for £4 a month it really isnt worth it. At the end of the day this is just a discord server, safeguarding is not really a concern as (as far as i know) none of the CD staff have legal responsibility for the safety of any of the server's members.

**Comment by ZomBMage** [comment]
well done you've found the joke

**Comment by JoshHeng** [comment]
What are you using for email? G Suite?

**Comment by n3bb** [comment]
> well done you've found the joke

didnt realise, uh sorry i guess?

**Comment by NicholasG04** [comment]
> What are you using for email? G Suite?

Stupid question, it's Beano so obviously it's Microsoft 365

**Comment by ZomBMage** [comment]
> > What are you using for email? G Suite?
> 
> Stupid question, it's Beano so obviously it's Microsoft 365

s/Microsoft 365/AWS

**Comment by SSAFuze** [comment]
Lets be real, who is getting married on a cyber server. But I do believe an inbox for these emails are vital to provide that extra layer of interactivity between staff and subjects. A PR stunt to pretend you aren’t above the lowly CDzens!

**Comment by SSAFuze** [comment]
Also poor britmonkey, bullied by beanos emails ;-;

**Comment by R0w4nS** [comment]
Are we replacing safety man yet?

**Comment by thebeanogamer** [comment]
> What are you using for email? G Suite?

Microsoft 365

**Comment by R0w4nS** [comment]
5 minutes late mate

**Comment by JoshHeng** [comment]
> 
> 
> > What are you using for email? G Suite?
> 
> Microsoft 365

Can't use use shared mailboxes or something? Or do staff members not have their own inbox anyway

**Comment by thebeanogamer** [comment]
> > 
> > 
> > > What are you using for email? G Suite?
> > 
> > Microsoft 365
> 
> Can't use use shared mailboxes or something? Or do staff members not have their own inbox anyway

Everyone other than me just has a forwarding address, as I'm reusing my personal O365

**Comment by Sh3llcod3** [comment]
> And the same goes for weddings, as they are (generally) a one in a lifetime experience 


ONS would like to know your location: https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/marriagecohabitationandcivilpartnerships/bulletins/marriagesinenglandandwalesprovisional/2017

**Comment by RealJammy** [comment]
imagine safety man just having a read of meta
