### ISSUE TITLE
unban request

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#372]
**Is your feature request related to a problem? Please describe.**
hello,
i would like to request an unban from the discord. i have been banned for about a year and a half at this point, and i think not being in the discord means missing out on important information regarding the programme. i also haven't interacted with many community members for a while, and occasionally miss doing so. i have also grown out of being toxic/edgy a bit.

**Describe the solution you'd like**
an unban, i am reformed

**Describe alternatives you've considered**
didn't think about this

**Comment by jerbob** [comment]
+1

**Comment by alfiejfs** [comment]
![image](https://user-images.githubusercontent.com/42497992/88727837-4bdea180-d128-11ea-8048-5d895228bc0b.png)

Unban zammo

**Comment by Trefonix** [comment]
Hi, sorry for the delay, you should have been DM'd an unban form which we'd like you to fill out.
