### ISSUE TITLE
Add reactions to #cyberstart

### ISSUE THREAD

**Issue by RealJammy** [CyberDiscovery/meta#373]
**Is your feature request related to a problem? Please describe.**
On the 15th of July, a sudo, who I will not name, took reactions away from the #cyberstart channel, promising to add them back soon, but hasn't happened yet.

**Describe the solution you'd like**
Adding reactions to #cyberstart 

**Describe alternatives you've considered**
None, as of yet

**Comment by lightspeedana** [comment]
Balance has been restored and I have returned the reactions.
