### ISSUE TITLE
Stop Botters reign of terror, bring back reactions on cyberstart

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#374]
**Description of the issue**
Bottersnike has yet again removed reactions from cyberstart, we were reacting as we were excited we got reactions back after weeks without when Botters got angry over cheese puns. I feel a different mod should have jurisdiction to remove such reactions as imo Botters is just doing it for no reason, they’ve already done it once before and then engaged in cheese puns.
**Proposed solution**
Your suggested solution to the problem raised above.

Reinstate reactions to Cyberstart and another mod to ask Botters not to keep removing them.
**Additional comments**
If you have anything else to say on the topic, put it here.

I’m sure Botters is nice but this isn’t it.

**Comment by ZomBMage** [comment]
You were spamming reactions, that's why they were disabled. Don't spam reactions, and they don't get disabled!

**Comment by Sh3llcod3** [comment]
Agreed with Bax. If reactions are spammed then we have the right to remove them for as long as required, Botters is just doing his job there. 👍

**Comment by Alpheeexx** [comment]
Reactions have been re-enabled to #cyberstart, please use it respectfully.

**Comment by skiros-habib** [comment]
Wait alphex is a Sudo?

**Comment by Sh3llcod3** [comment]
Yes but also yes. @Skir0s

**Comment by ghost** [comment]
Lol
