### ISSUE TITLE
Hold a server vote on unbanning Rak 

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#375]
**Description of the issue**
It’s clear that Rak is a controversial figure and as such he is banned. As it says in a previous issue, one admin says they ‘wish to only ban as an absolute last resort in the interest of the community as a whole’- I would argue that the active voice of the community continually state that they do not feel it is in the interest of them or Rak. A member said about Rak: ‘Rak is a bit of a cunt but he’s actually very intelligent and knowledgeable’. 
Rak is an elite participant, and was involved in CCC- his ban will only hinder his progress now the program has started. It is important for him to stay in the loop whether he is allowed to comment or not. Members have said that Rak didn’t even do much when he got banned most recently, and the consensus seems to be there was little reason for ban.
Rak is a pillar of this community. His jokes have been a little untasteful, his actions a little hard to swallow. But arguments about him seem to never stop and in those discussions, I have not seen anyone aside from a mod say he shouldn’t come back. It was Rak’s birthday on 15/7. A new year for Rak should symbolise a new start, a maturity. We are confident Rak can do this.
Finally, it seems the mods have a vendetta against Rak. They are the ones arguing that he shouldn’t be unbanned. Rak feels victimised by them, and I believe they are biased against what he has said previously. Rak has a darker sense of humour than most, and things said on the internet, as you should know, are meaningless and do not always reflect the views of the person. The server members know this and know what Rak says can be misinterpreted and not reflective of the real Rak. It is simply not inclusive- as Rak has stated he gives diversity to the server, as a self proclaimed ‘cripple’. Perhaps Rak’s dark humour just reflects an outlet for his pain. 
As such, I believe that the community should decide whether Rak comes back. The last issue raised about Rak was closed by Beano for being ‘too heated’- I don’t constitute ‘too heated’ as being full of people saying to bring Rak back. The community is what the mods want to protect and support- they cannot serve us if we do not get to have a real say.

**Proposed solution**
Allow the community to vote on whether Rak is unbanned. There can even be a campaign, where the mods give a comprehensive side as to why they banned Rak so people can be properly informed.

**Additional comments**
Making the server a more supportive place does not mean censoring people. The world is not supportive and the internet can be a cruel place- but it is important people understand and see that. Mods refusing to give the community a real say on Rak just shows authoritarianism.

**Comment by NicholasG04** [comment]
oh god

may as well close it now

**Comment by Trefonix** [comment]
There are a very vocal minority who are pushing for rak's unban, we do not think this is in the interest of the server as a whole and such this vote will not happen.

**Comment by ghost** [comment]
> oh god
> 
> may as well close it now

Because the mods won’t accept a democratic process? The things he’s said are questionable but everyone has the right to a fair trial and the community should be allowed the real say as to whether they want Rak in the server. I think this is fair 👍

**Comment by Lukew11037** [comment]
NOOOOO I WAS JUST ABOUT TO SAY IN BEFORE ITS CLOSED SMH

**Comment by ZomBMage** [comment]
This isn't a judicial court of law, this is a discord server, it is not a human right that you have access to a discord server.
