### ISSUE TITLE
Time limit on bans

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#376]
**Is your feature request related to a problem? Please describe.**
Some people end up banned when they have done something wrong leading them to miss out. After a time, this is more than enough punishment 

**Describe the solution you'd like**
Set a time limit on bans for example 2 months. If they can’t be fucked with the server they won’t rejoin but others miss out on genuine cyberstart stuff. They can go through an appeal as well however this should only be a short check and not a major decision 

**Describe alternatives you've considered**
You could make the person do a voice call to apologise, showing they are committed to rejoining by actually talking

**Additional context**
Don’t just let people appeal bans and face mods who may have bias

**Comment by Lukew11037** [comment]
in before locked

**Comment by skiros-habib** [comment]
idk i like appeals tbh

**Comment by ghost** [comment]
> idk i like appeals tbh

There could be a less scrutinous appeal stage that merely serves as a gateway

**Comment by n3bb** [comment]
why bother making meta issues its not like mods listen to them

**Comment by n3bb** [comment]
also inb4 closed or locked

**Comment by ghost** [comment]
> why bother making meta issues its not like mods listen to them
> 
> 
> 
> 

I feel like they do. They just don't fix things that ain't broke. Most bans are temp at first and only repeat offenders get permanent bans. And even then they can still be unbanned after some time if they appeal.

**Comment by ghost** [comment]
> > why bother making meta issues its not like mods listen to them
> 
> I feel like they do. They just don't fix things that ain't broke. Most bans are temp at first and only repeat offenders get permanent bans. And even then they can still be unbanned after some time if they appeal.

They don’t listen, they close them for being too heated

**Comment by 0xAda** [comment]
no
