### ISSUE TITLE
IRC Server for CD

### ISSUE THREAD

**Issue by TheGoatedDev** [CyberDiscovery/meta#377]
**Description of the issue**
Have a IRC Server bc 133t H4ck3r m4n.

**Proposed solution**
Beano make a IRC Server

**Additional comments**
If it ain't beano than someone else do it.

**Comment by TheGoatedDev** [comment]
I didn't make it a enhancement idk how to change it.

**Comment by ghost** [comment]
I mean I guess we could

**Comment by n3bb** [comment]
do it beano

**Comment by skiros-habib** [comment]
IRC bridge as well pls

**Comment by alfiejfs** [comment]
why

**Comment by 0xAda** [comment]
why

**Comment by jerbob** [comment]
![crab](https://cdn.discordapp.com/emojis/653904052773584906.gif)
