### ISSUE TITLE
the mod team is not inclusive

### ISSUE THREAD

**Issue by maishams** [CyberDiscovery/meta#378]
hello i have realised somethings
the mods are all discriminant
if you take a look at the mod team they all have something in common - they are all mods; there are no non-mods in the mod team.

i feel this is veryunfair because it means that they believe only mods are worthy of the power they hold

i therefore suggest you add a non mod to the mod team so that the mod team does not consist of only mods because then you are no longer discrimiating against the non mods

i am eager to see the positive change this suggestion will bring

thank you 

maisha 7404 (i can be found in the blue corridor)

**Comment by seagull-pat** [comment]
the blue corridor smells bad

also this would create a paradox that i believe would result in the extermination of all life on earth. your scientists were so preoccupied with whether or not they could, they didn't stop to think if they should

**Comment by woaisthisgit** [comment]
seagull-pat you smell bad

**Comment by pbeart** [comment]
strong disagree

**Comment by maishams** [comment]
seagull i dont think you are taking this seriously,

the issue is not the blue corridor or the scientists, its the predominant prevelant discrimination in the society

please take your nonsence somewhere else

**Comment by ZomBMage** [comment]
This is spam.

**Comment by woaisthisgit** [comment]
no this is mod discrimination in action

**Comment by RealJammy** [comment]
Closing pressing issues like this further highlights the need for non mods in the mod team. This issue is extremely important, and closing it will not help.

**Comment by maishams** [comment]
Dear Bax

This is not spam. It is a prevelant issue that I have brought up. 

You closing this issue shows how normalised this behavior is that you feel this is so unimportant it comes under spam

I will be going to sleep unhappy at the lack of change
Maisha, The 'Non-Mods In The Mod Team' Supporter
