### ISSUE TITLE
ban dyno

### ISSUE THREAD

**Issue by R0w4nS** [CyberDiscovery/meta#380]
**Description of the issue**
dyno is shite and toxic deleting my messages and shit

**Proposed solution**
ban him and replace him

**Additional comments**
no

**Comment by Trefonix** [comment]
I've changed dyno's settings and it will no longer delete messages for being too quick. Don't abuse this or the setting will have to go back on. It will still warn you tho.

**Comment by NicholasG04** [comment]
Thanks Tref, what a G.

**Comment by R0w4nS** [comment]
Decent solution for now - I will close this.
