### ISSUE TITLE
Discord Partner

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#382]
**Explain your question**
https://discord.com/partners

The discord partner program just reopened and we shouldn't apply but we should probably discuss it too.

**Comment by Bentechy66** [comment]
no don't apply aaa

**Comment by thebeanogamer** [comment]
Yes this is a thing we should do. Free level 3 boosts yes yes yum yum. We do meet all their metrics, provided they don't change them again.

![image](https://user-images.githubusercontent.com/3729048/95632280-361d1f00-0a7d-11eb-8ecf-d9ee7ec9fed1.png)

Since this issue was opened, they've closed application again, because of course they have, but when they reopen them we'll need answers to the following questions to apply. 250 characters on each:

* Server Description: Tell us about your server. What is it about? Who is it for?
* What makes your server deserving of Partnership? Take a moment to share what makes your server unique, or tell us something truly special that happened within your community.

I feel like I'll regret asking for this, but suggested drafts would be appreciated.

**Comment by Lukew11037** [comment]
a

**Comment by Lukew11037** [comment]
**Alternatively you have this masterpiece** 


My girlfriend and me have done dating for 5 month. I thought "This girl is very good," and became of love with her.

Yet even so, on this Monday, I comed home and found she as baked all my beans.

Yes, all. Oh brother.

In my cupboard I store several bag of bean, to make soft and to bake on some days, to have a bit of baked bean on my dinner. Or, heck, a lunch too some days.

But on the Monday I find this girlfriend baked all the beans. I say "Why do you bake my beans", and she say something as "I bakes them good to save time, so I bakes them all now."

I am astonished and full of dissmay. I say "I canfr not eat all the beans", she say she is froze many of the beans so as we can unfrozen the on a later day and eat some at a time.

But, if a bean is froze and unfrozed, the very good and very nice flavor of bean is gone far.

A bean is best if baked fresh as a Sunday Pie. Not to be froze and unfroze!

I told my girfriend I am so sad of this, as to my opinion the baking of the beans and to freeze them has ruin all my beans. She say I am "gone haywire" by my enragement and sad manners.

But I hates what she did to my beans.

On the days before Monday I thought "Will we marry the girlfriend? Well it might be so."

But now I am so sad she baked them beans. I am consider to end our relations and not be the boyfriend and girlfriend any more. But, is my idea wrong? Could my girlfriend make promise to not bake the beans? I do not know what doing to do and how to feel forgiving on her.

**Comment by alfiejfs** [comment]
The Cyber Discovery Discord server is an educational Discord Server aimed at those participating in the Cyber Discovery programme. Cyber Discovery itself is a program aimed at 13-19 year olds to introduce students to the world of cyber security, wherein they receive training and complete challenges designed by members of industry. Students whom excel in this program have the opportunity to attend live events and sit paid-for SANS certifications.

Our Discord server is deserving of a Discord Partnership as it fosters a safe environment for those participating in the programme to discuss, work together and learn more about cyber security. A good portion of our server members usually end up meeting at the invitational events, and thus a large majority of our community extends beyond the realms of Discord making it truly something to behold.

Thank you for any consideration
Yours faithfully,
The global standard for moderation and the peak of the human form,
The Cyber Discovery Mod team

**Comment by Lukew11037** [comment]
please can we remove real suggestions here, they dont represent the cd server at all

**Comment by alfiejfs** [comment]
Within regards to the same topic, I really hope we aren't represented by anime profile pictures and privately educated people who live a hard life, so let's remove them too

**Comment by HEELcaT666** [comment]
:(

**Comment by Lukew11037** [comment]
oh no, here we go again. Time for a cd fire **GITHUB EDITION**

**Comment by rak1507v4** [comment]
The Cyber Discovery Discord server is a Discord server aimed at students from the age of 13 to 18 who are involved in the government funded Cyber Discovery program. This server provides support for the students as they undergo professional training in cyber security, fostering a safe and inclusive environment for discussion, education, and friendship.

The moderators in this server, all of them being veterans of the Cyber Discovery program, go out of their way to make it what it is, and put in hundreds of hours worth of work maintaining, updating, and moderating the server to keep it up to their high standards. 

This server has helped hundreds of people to achieve their potentials, and is responsible for the development of young cyber security enthusiasts almost as much as the Cyber Discovery program itself.

Unfortunately, the moderators of this server have a vendetta against the disabled. They stop at nothing to make the lives of anyone with any disability hell, no matter how minor. Be it a twisted ankle, sore throat, broken arm, or complete paralysis, you can be assured the moderators will have sleepless nights thinking of the best ways to torment their poor victims.

The support for eugenics in the moderator's #staff channel rivals that of a Nazi party conference, and leaked images show them relentlessly mocking people for their "impurity" and "inferior genes". Of course, this is somewhat ironic, given that most of the moderators suffer themselves from severe chronic retardation. 

However, we hope you, the discord team, see past these minor flaws, and accept this request for partner. Thank you, thebeanogamer.

**Comment by Lukew11037** [comment]
i can confirm what rak has said as being the full truth with no lies at all, am part of the bullied and have been effected by botters reign of terror
