### ISSUE TITLE
Nitro on the member list

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#383]
**Is your feature request related to a problem? Please describe.**
Nitro boosters need more clout for spending their hard earned money on this server

**Describe the solution you'd like**
Add a nitro booster section to the member list above veteran 2020 but below comm dev.

**Describe alternatives you've considered**
Put nitro booster above root.

**Comment by R0w4nS** [comment]
no

**Comment by NateKomodo** [comment]
no

**Comment by ThisIs0xBC** [comment]
no
http://gph.is/29cUyGT

**Comment by RealJammy** [comment]
no

**Comment by Bottersnike** [comment]
no
