### ISSUE TITLE
Cybersec dead

### ISSUE THREAD

**Issue by 404dcd** [CyberDiscovery/meta#384]
**Description of the issue**
🦀 Elite is kill 🦀 

**Proposed solution**
Rename the server to something ballet related

**Additional comments**
Please oh god Beano

**Comment by thebeanogamer** [comment]
🦀 Elite is kill 🦀

**Comment by n3bb** [comment]
do it
no balls

**Comment by Lukew11037** [comment]
🦀 Elite is kill 🦀
🦀 Cyberdiscovery is kill 🦀
🦀 Cyberdiscovery server is kill 🦀
