### ISSUE TITLE
Suggest an idea for the server. If this doesn’t look right, choose a different type.

### ISSUE THREAD

**Issue by chop0** [CyberDiscovery/meta#385]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chop0** [comment]
wait shit

**Comment by chop0** [comment]
what

**Comment by thebeanogamer** [comment]
what

**Comment by chop0** [comment]
as we say in the  biz, a picture is worth a thousand words
