### ISSUE TITLE
unban rakv3

### ISSUE THREAD

**Issue by n3bb** [CyberDiscovery/meta#390]
**Description of the issue**
rak is banned

**Proposed solution**
unban rak

**Additional comments**
as jammy said, #computer-science just isnt the same without the regular doses of APL
also in general rak is cool
unban him pls

**Comment by 404dcd** [comment]
BEANO before you close this can you please merge my PR because it actually isn't bad

I'm not jack

https://github.com/CyberDiscovery/cyberdisc-bot/pull/610

**Comment by NicholasG04** [comment]
I'd like to share my support for this issue. I really miss Rak as a great person to have a chat with in general.

**Comment by RealJammy** [comment]
quack quack unban rak

**Comment by snebae** [comment]
i don't know rak that well but he also seemed kinda funny in #general so i would support bringing him bacc

**Comment by chop0** [comment]
quack quack unban rak

**Comment by NicholasG04** [comment]
pls can we have Rak back, I miss him

**Comment by 404dcd** [comment]
I miss him too, he's clever and some of the APL stuff fascinates me
