### ISSUE TITLE
Food channel (hear me out)

### ISSUE THREAD

**Issue by 404dcd** [CyberDiscovery/meta#391]
**Is your feature request related to a problem? Please describe.**
Not really. There are a few food pictures each day in general, and I think it would be nice to make another channel in keyboard warriors to contain them. IF THIS IS TOO MANY CHANNELS, I propose merging of linus-1 and linus-2 into just linus. That way, the number of channels would stay the same.

**Describe the solution you'd like**
Make #food, optionally consolidate #linus-1 and #linus-2

**Describe alternatives you've considered**
I mean, you could just not, I'm not forcing you to do anything

**Additional context**
https://cdn.discordapp.com/attachments/411573884597436416/811596116407484416/IMG_20210217_135244.jpg

**Comment by 404dcd** [comment]
You could also delete america which is stale

**Comment by ghost** [comment]
I would like this.

**Comment by RealJammy** [comment]
Alternatively, turn america into food

**Comment by Sh3llcod3** [comment]
food where? 👀

**Comment by Sh3llcod3** [comment]
<div style='vertical-align:top; display:inline;'><span style='vertical-align:top; display:inline;'>food where? </span><img style='vertical-align:top; display:inline;' src="https://user-images.githubusercontent.com/28938427/108240714-02e14f80-7143-11eb-97ca-aa0bb6493c39.png" width="32px" height="auto"></div>

**Comment by seadeef** [comment]
> https://cdn.discordapp.com/attachments/411573884597436416/811596116407484416/IMG_20210217_135244.jpg

Can you even classify this as food though?

**Comment by 404dcd** [comment]
@CyberDiscovery/server-moderator-team @CyberDiscovery/server-admin-team Any progress on this?

**Comment by 0xAda** [comment]
IMO there's already too many channels, maybe delete the server and remake it with just the food channel?

**Comment by RealJammy** [comment]
Open this.
