### ISSUE TITLE
Unban rak

### ISSUE THREAD

**Issue by RealJammy** [CyberDiscovery/meta#394]
**Is your feature request related to a problem? Please describe.**
Unban rak please, stem channels have died without him

**Describe the solution you'd like**
An unbanning of rak.

**Describe alternatives you've considered**
Quarantining rak to the elite and stem channels again

**Additional context**
![ourlegend](https://user-images.githubusercontent.com/57639251/109855082-c556e900-7c4f-11eb-8a2e-c033290689dc.png)
Rak is more spoken of than the kali in CD, showing our love for him. CD doesn't feel complete without rak. Therefore, unban rak please(plus he's super cool and super smart)

**Comment by 404dcd** [comment]
I agree, it doesn't feel complete. Maybe he could start by being quarantined, and then gain access to the rest of the server? We were all good friends of his, I can't imagine his ban is that good for his mental health.

**Comment by NxtDaemon** [comment]
Whist I'm sure _Rak wasn't exactly amazing for the Mods and some of the members_, I think he did more beneficial things than not ; surely there is no harm in allowing him back in to be quarantined + he was very good at either inspiring or off-putting the people who ask for help often.

**Comment by NicholasG04** [comment]
rak is amazing
pls bring back rak
such good fun
i miss rak

**Comment by chop0** [comment]
quack quack unban rak

**Comment by potato-jackson** [comment]
un🅱️an rak

**Comment by chop0** [comment]
^ this.

**Comment by dnzc** [comment]
now that cd is crab
to stop the server from being drab
please, please, please bring back
our god in a wheelchair, rak.

**Comment by R0w4nS** [comment]
hurry up

**Comment by RealJammy** [comment]
rude
