### ISSUE TITLE
Move 100% role above Summer Camp

### ISSUE THREAD

**Issue by dnzc** [CyberDiscovery/meta#395]
**Description of the issue**
So many people have the summer camp role compared to 100% (around 50 vs around 5), it only makes sense.

**Proposed solution**
Move the 100 percent role above the summer camp role

**Additional comments**
If you 100%ed game you probably got into summer camp anyway, and it feels like a bigger achievement.

**Comment by RealJammy** [comment]
As well as this, I propose changing summer camp role colour; it is very similar to the one of 100% completion

**Comment by Trefonix** [comment]
Done
