### ISSUE TITLE
Pick a programming language for this repo

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/meta#4]
We should probably have a programming language for this repo, one with a nice colour/entertaining name.

A list of supported languages and colours can be found here: https://github.com/ozh/github-colors

And no, we're not using BF.

**Comment by jerbob** [comment]
AutoHotKey has a pleasant colour:
![image](https://user-images.githubusercontent.com/25161069/56740763-75f92500-6769-11e9-98cf-a3673ff81945.png)

I propose that @thebeanogamer uploads that AHK script that he used to solve the final assess challenge.

**Comment by thebeanogamer** [comment]
That’s not an awful idea.

**Comment by jb3** [comment]
brainfuck

**Comment by jb3** [comment]
do it I dare you

**Comment by alfiejfs** [comment]
Powershell has a kind of CD-ish colour

![Poweshell](https://camo.githubusercontent.com/1b44619b38de93e317d11f5e63284edb4b2f3660/687474703a2f2f7669612e706c616365686f6c6465722e636f6d2f313438783134382f3031323435362f66666666666626746578743d506f7765725368656c6c)

**Comment by thebeanogamer** [comment]
Resolved by #1

**Comment by thebeanogamer** [comment]
I suspect that `.github` is ignored for this, so the change has not had impact, I'll check this properly before making a PR though.

**Comment by thebeanogamer** [comment]
Correction, the file extension should have been `.hx`, as can be seen here: https://github.com/HaxeFoundation/haxe/blob/68edc60526f461147f945f5a85789413bf0c86ef/std/lua/lib/luv/Loop.hx

**Comment by teamshortcut** [comment]
_whoops, sorry_
