### ISSUE TITLE
make an unhoisted but still coloured version of true 100% for community developers to show off their orange

### ISSUE THREAD

**Issue by Bentechy66** [CyberDiscovery/meta#5]

**Comment by jb3** [comment]
also make community dev not pingable while you're at it

**Comment by jerbob** [comment]
If anyone's not sure what "unhoisted" refers to, @Bentechy66's essentially suggesting that the `True 100%` role is moved above `Community Developers`, and the following setting is **disabled**:

![image](https://user-images.githubusercontent.com/25161069/56824105-7ec32700-684d-11e9-87c6-829e8508c02b.png)

Resulting in:

![image](https://user-images.githubusercontent.com/25161069/56824243-d2ce0b80-684d-11e9-817a-7652ff85c901.png)

**Comment by teamshortcut** [comment]
This seems elitist and tailored for an incredibly specialised usecase...

**Comment by fractalpenguin** [comment]
Moreover, the community developer role colour is inherently better.

**Comment by thebeanogamer** [comment]
This is a purely vanity suggestion, which would worsen the design of the server, make administration harder, and serve no beneficial purpose other than helping your ego.

**Comment by Bentechy66** [comment]
\>still not a problem for mentor
